# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""会計（accounting）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.accounting import models as md
from app.modules.fin.accounting import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.FiscalYear, out_schema=sc.FiscalYearOut, create_schema=sc.FiscalYearCreate, update_schema=sc.FiscalYearUpdate, resource='fiscal-year', search_fields=['name'], order_by='id desc', label='FiscalYear'))
router.include_router(build_crud_router(model=md.AccountingPeriod, out_schema=sc.AccountingPeriodOut, create_schema=sc.AccountingPeriodCreate, update_schema=sc.AccountingPeriodUpdate, resource='accounting-period', search_fields=[], order_by='id desc', label='AccountingPeriod'))
router.include_router(build_crud_router(model=md.JournalEntry, out_schema=sc.JournalEntryOut, create_schema=sc.JournalEntryCreate, update_schema=sc.JournalEntryUpdate, resource='journal-entry', search_fields=['journal_no', 'description'], order_by='entry_date desc', label='JournalEntry'))
router.include_router(build_crud_router(model=md.JournalLine, out_schema=sc.JournalLineOut, create_schema=sc.JournalLineCreate, update_schema=sc.JournalLineUpdate, resource='journal-line', search_fields=['account_name'], order_by='id desc', label='JournalLine'))
router.include_router(build_crud_router(model=md.JournalSource, out_schema=sc.JournalSourceOut, create_schema=sc.JournalSourceCreate, update_schema=sc.JournalSourceUpdate, resource='journal-source', search_fields=[], order_by='created_at desc', label='JournalSource'))

__all__ = ['router']  # entities: FiscalYear, AccountingPeriod, JournalEntry, JournalLine, JournalSource
