# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""会計（accounting）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class FiscalYear(Base):
    __tablename__ = "fin_fiscal_year"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(20), nullable=False, index=True, unique=True)
    name = Column(String(50), nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    status = Column(String(20), default="open")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class AccountingPeriod(Base):
    __tablename__ = "fin_accounting_period"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    fiscal_year_id = Column(Integer, ForeignKey("fin_fiscal_year.id", ondelete="CASCADE"))
    year_month = Column(String(7), nullable=False, index=True)
    status = Column(String(20), default="open")
    closed_at = Column(DateTime)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class JournalEntry(Base):
    __tablename__ = "fin_journal_entry"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    journal_no = Column(String(40), index=True)
    entry_date = Column(Date, nullable=False, index=True)
    period_ym = Column(String(7), index=True)
    entry_type = Column(String(30), default="manual")
    description = Column(String(255))
    total_debit = Column(Numeric(18, 2), default=0)
    total_credit = Column(Numeric(18, 2), default=0)
    status = Column(String(20), index=True, default="draft")
    source_id = Column(BigInteger)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class JournalLine(Base):
    __tablename__ = "fin_journal_line"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    entry_id = Column(BigInteger, ForeignKey("fin_journal_entry.id", ondelete="CASCADE"), nullable=False)
    line_no = Column(Integer, default=1)
    account_code = Column(String(50), index=True)
    account_name = Column(String(100))
    debit = Column(Numeric(18, 2), default=0)
    credit = Column(Numeric(18, 2), default=0)
    tax_code = Column(String(20))
    tax_amount = Column(Numeric(18, 2), default=0)
    department_code = Column(String(50))
    partner_id = Column(Integer)
    remarks = Column(String(255))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class JournalSource(Base):
    __tablename__ = "fin_journal_source"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    source_type = Column(String(40), nullable=False, index=True)
    source_module = Column(String(30))
    source_ref = Column(String(100), index=True)
    event_date = Column(Date)
    amount = Column(Numeric(18, 2), default=0)
    payload_json = Column(Text)
    status = Column(String(20), index=True, default="pending")
    journal_entry_id = Column(BigInteger)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

