# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""会計（accounting）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class FiscalYearCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    status: Optional[str] = None


class FiscalYearUpdate(FiscalYearCreate):
    pass


class FiscalYearOut(FiscalYearCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class FiscalYearPage(BaseModel):
    items: List[FiscalYearOut]
    total: int
    page: int
    page_size: int
    pages: int


class AccountingPeriodCreate(BaseModel):
    fiscal_year_id: Optional[int] = None
    year_month: Optional[str] = None
    status: Optional[str] = None
    closed_at: Optional[datetime] = None


class AccountingPeriodUpdate(AccountingPeriodCreate):
    pass


class AccountingPeriodOut(AccountingPeriodCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class AccountingPeriodPage(BaseModel):
    items: List[AccountingPeriodOut]
    total: int
    page: int
    page_size: int
    pages: int


class JournalEntryCreate(BaseModel):
    journal_no: Optional[str] = None
    entry_date: Optional[date] = None
    period_ym: Optional[str] = None
    entry_type: Optional[str] = None
    description: Optional[str] = None
    total_debit: Optional[float] = None
    total_credit: Optional[float] = None
    status: Optional[str] = None
    source_id: Optional[int] = None


class JournalEntryUpdate(JournalEntryCreate):
    pass


class JournalEntryOut(JournalEntryCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class JournalEntryPage(BaseModel):
    items: List[JournalEntryOut]
    total: int
    page: int
    page_size: int
    pages: int


class JournalLineCreate(BaseModel):
    entry_id: Optional[int] = None
    line_no: Optional[int] = None
    account_code: Optional[str] = None
    account_name: Optional[str] = None
    debit: Optional[float] = None
    credit: Optional[float] = None
    tax_code: Optional[str] = None
    tax_amount: Optional[float] = None
    department_code: Optional[str] = None
    partner_id: Optional[int] = None
    remarks: Optional[str] = None


class JournalLineUpdate(JournalLineCreate):
    pass


class JournalLineOut(JournalLineCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class JournalLinePage(BaseModel):
    items: List[JournalLineOut]
    total: int
    page: int
    page_size: int
    pages: int


class JournalSourceCreate(BaseModel):
    source_type: Optional[str] = None
    source_module: Optional[str] = None
    source_ref: Optional[str] = None
    event_date: Optional[date] = None
    amount: Optional[float] = None
    payload_json: Optional[str] = None
    status: Optional[str] = None
    journal_entry_id: Optional[int] = None


class JournalSourceUpdate(JournalSourceCreate):
    pass


class JournalSourceOut(JournalSourceCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class JournalSourcePage(BaseModel):
    items: List[JournalSourceOut]
    total: int
    page: int
    page_size: int
    pages: int

