SET NAMES utf8mb4;

CREATE TABLE `cutting_plan_items`  (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_id` int NOT NULL,
  `instruction_plan_id` int NULL DEFAULT NULL,
  `source_management_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `product_cd` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `material_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `production_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `planned_quantity` int NOT NULL DEFAULT 0,
  `instruction_production_quantity` int NOT NULL DEFAULT 0 COMMENT '指示計画の生産数',
  `production_lot_size` int NULL DEFAULT NULL,
  `lot_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `take_count` int NULL DEFAULT NULL,
  `cutting_length` decimal(10, 2) NULL DEFAULT NULL,
  `assigned_machine_id` int NULL DEFAULT NULL,
  `assigned_machine` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `sequence_no` int NOT NULL DEFAULT 0,
  `planned_day` date NULL DEFAULT NULL,
  `planned_start` datetime NULL DEFAULT NULL,
  `planned_end` datetime NULL DEFAULT NULL,
  `estimated_minutes` decimal(10, 2) NOT NULL DEFAULT 0.00,
  `efficiency_rate` decimal(10, 2) NULL DEFAULT NULL,
  `setup_time_min` int NULL DEFAULT NULL,
  `is_locked` tinyint(1) NOT NULL DEFAULT 0,
  `publish_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PLANNED',
  `published_cutting_id` int NULL DEFAULT NULL,
  `actual_quantity` int NOT NULL DEFAULT 0,
  `completion_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PLANNED',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_cutting_plan_items_run`(`run_id` ASC) USING BTREE,
  INDEX `idx_cutting_plan_items_machine_seq`(`run_id` ASC, `assigned_machine_id` ASC, `sequence_no` ASC) USING BTREE,
  INDEX `idx_cutting_plan_items_day`(`run_id` ASC, `planned_day` ASC) USING BTREE,
  INDEX `idx_cutting_plan_items_instruction`(`instruction_plan_id` ASC) USING BTREE,
  INDEX `idx_cutting_plan_items_management_code`(`source_management_code` ASC) USING BTREE,
  INDEX `idx_cutting_plan_items_published_cutting`(`published_cutting_id` ASC) USING BTREE,
  CONSTRAINT `fk_cutting_plan_items_run` FOREIGN KEY (`run_id`) REFERENCES `cutting_plan_runs` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '切断計画明細' ROW_FORMAT = Dynamic;
