/**
 * メニュー定義（単一ソース）
 * 新規ルート追加時はここに1件追加し、管理画面で「ルート定義から取り込み」を実行すると menus テーブルに反映される
 */
import { finMenuConfig } from './finMenuConfig'

export interface MenuConfigItem {
  code: string
  name: string
  path?: string
  icon?: string
  parentCode?: string
  sortOrder: number
}

/** 全メニュー定義（親→子の順で並べる） */
export const menuConfig: MenuConfigItem[] = [
  { code: 'DASHBOARD', name: 'ダッシュボード', path: '/dashboard', icon: 'HomeFilled', sortOrder: 0 },
  { code: 'ERP', name: 'ERP管理メニュー', icon: 'OfficeBuilding', sortOrder: 1 },

  // ===== 1. 販売管理 (Sales / SD) =====
  { code: 'ERP_SALES', name: '販売管理(営業)', path: '/erp/sales', icon: 'Sell', parentCode: 'ERP', sortOrder: 1 },
  { code: 'ERP_SALES_HOME', name: '販売ホーム', icon: 'HomeFilled', path: '/erp/sales', parentCode: 'ERP_SALES', sortOrder: 0 },
  { code: 'ERP_SALES_QUOTATION', name: '見積管理', icon: 'Tickets', path: '/erp/sales/quotation', parentCode: 'ERP_SALES', sortOrder: 1 },
  { code: 'ERP_SALES_ORDERS', name: '受注一覧', icon: 'List', path: '/erp/sales/orders', parentCode: 'ERP_SALES', sortOrder: 2 },
  { code: 'ERP_SALES_FORECAST', name: '内示・フォーキャスト', icon: 'TrendCharts', path: '/erp/sales/forecast', parentCode: 'ERP_SALES', sortOrder: 4 },
  { code: 'ERP_SALES_CREDIT', name: '与信管理', icon: 'Wallet', path: '/erp/sales/credit', parentCode: 'ERP_SALES', sortOrder: 5 },
  { code: 'ERP_SALES_CONTRACT', name: '契約単価管理', icon: 'Stamp', path: '/erp/sales/contract-pricing', parentCode: 'ERP_SALES', sortOrder: 6 },
  { code: 'ERP_SALES_SHIPPING', name: '出荷指示', icon: 'Van', path: '/erp/sales/shipping', parentCode: 'ERP_SALES', sortOrder: 7 },
  { code: 'ERP_SALES_RECORDING', name: '売上計上', icon: 'Coin', path: '/erp/sales/recording', parentCode: 'ERP_SALES', sortOrder: 8 },
  { code: 'ERP_SALES_INVOICE', name: '請求書発行', icon: 'Document', path: '/erp/sales/invoice', parentCode: 'ERP_SALES', sortOrder: 9 },
  { code: 'ERP_SALES_CORRECTION', name: '赤黒訂正処理', icon: 'RefreshLeft', path: '/erp/sales/return-correction', parentCode: 'ERP_SALES', sortOrder: 10 },
  { code: 'ERP_SALES_RETURNS', name: '返品管理(RMA)', icon: 'RefreshRight', path: '/erp/sales/returns', parentCode: 'ERP_SALES', sortOrder: 11 },

  // ===== 受注管理 (Order Management) =====
  { code: 'ERP_ORDER', name: '受注管理', path: '/erp/order', icon: 'Notebook', parentCode: 'ERP', sortOrder: 2 },
  { code: 'ERP_ORDER_HOME', name: '受注ホーム', icon: 'HomeFilled', path: '/erp/order', parentCode: 'ERP_ORDER', sortOrder: 0 },
  { code: 'ERP_ORDER_MONTHLY', name: '月受注管理', icon: 'Calendar', path: '/erp/order/monthly', parentCode: 'ERP_ORDER', sortOrder: 1 },
  { code: 'ERP_ORDER_DAILY', name: '日受注管理', icon: 'Calendar', path: '/erp/order/daily', parentCode: 'ERP_ORDER', sortOrder: 2 },
  { code: 'ERP_ORDER_DEST_HIST', name: '納入先別受注履歴', icon: 'Histogram', path: '/erp/order/destination-history', parentCode: 'ERP_ORDER', sortOrder: 3 },

  // ===== 2. 購買・外注管理 (Procurement & Subcontracting) =====
  { code: 'ERP_PURCHASE', name: '購買・外注管理', path: '/erp/purchase', icon: 'ShoppingCart', parentCode: 'ERP', sortOrder: 3 },
  { code: 'ERP_PURCHASE_MATERIAL', name: '材料管理', icon: 'Collection', parentCode: 'ERP_PURCHASE', sortOrder: 1 },
  { code: 'ERP_PURCHASE_MATERIAL_ORDER', name: '材料在庫管理', icon: 'Box', path: '/erp/purchase/material/order', parentCode: 'ERP_PURCHASE_MATERIAL', sortOrder: 1 },
  { code: 'ERP_PURCHASE_MATERIAL_RECEIVING', name: '受入履歴', icon: 'Download', path: '/erp/purchase/material/receiving-history', parentCode: 'ERP_PURCHASE_MATERIAL', sortOrder: 2 },
  { code: 'ERP_PURCHASE_MATERIAL_INSPECTION', name: '受入検品', icon: 'CircleCheck', path: '/erp/purchase/material/receiving-inspection', parentCode: 'ERP_PURCHASE_MATERIAL', sortOrder: 3 },
  { code: 'ERP_PURCHASE_MATERIAL_FORECAST', name: '内示管理', icon: 'TrendCharts', path: '/erp/purchase/material/forecast', parentCode: 'ERP_PURCHASE_MATERIAL', sortOrder: 4 },
  { code: 'ERP_PURCHASE_PART', name: '部品管理', icon: 'Grid', parentCode: 'ERP_PURCHASE', sortOrder: 2 },
  { code: 'ERP_PURCHASE_PART_ORDER', name: '部品在庫管理', icon: 'Box', path: '/erp/purchase/part/order', parentCode: 'ERP_PURCHASE_PART', sortOrder: 1 },
  { code: 'ERP_PURCHASE_PART_RECEIVING', name: '受入履歴', icon: 'Download', path: '/erp/purchase/part/receiving-history', parentCode: 'ERP_PURCHASE_PART', sortOrder: 2 },
  { code: 'ERP_PURCHASE_OUTSOURCING', name: '外注管理', path: '/erp/purchase/outsourcing', icon: 'OfficeBuilding', parentCode: 'ERP_PURCHASE', sortOrder: 3 },
  { code: 'ERP_OUTSOURCING_HOME', name: '外注ホーム', icon: 'HomeFilled', path: '/erp/purchase/outsourcing', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 0 },
  { code: 'ERP_OUTSOURCING_PLATING_ORDER', name: '外注メッキ注文', icon: 'Brush', path: '/erp/purchase/outsourcing/plating-order', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 2 },
  { code: 'ERP_OUTSOURCING_PLATING_RECEIVING', name: '外注メッキ受入', icon: 'Download', path: '/erp/purchase/outsourcing/plating-receiving', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 3 },
  { code: 'ERP_OUTSOURCING_WELDING_ORDER', name: '外注溶接注文', icon: 'Connection', path: '/erp/purchase/outsourcing/welding-order', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 4 },
  { code: 'ERP_OUTSOURCING_WELDING_RECEIVING', name: '外注溶接受入', icon: 'Download', path: '/erp/purchase/outsourcing/welding-receiving', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 5 },
  { code: 'ERP_OUTSOURCING_SUPPLIERS', name: '外注先マスタ', icon: 'User', path: '/erp/purchase/outsourcing/suppliers', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 6 },
  { code: 'ERP_OUTSOURCING_PROCESS_PRODUCTS', name: '外注工程製品', icon: 'Operation', path: '/erp/purchase/outsourcing/process-products', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 7 },
  { code: 'ERP_OUTSOURCING_STOCK', name: '外注在庫', icon: 'Box', path: '/erp/purchase/outsourcing/stock', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 8 },
  { code: 'ERP_OUTSOURCING_SUPPLIED_STOCK', name: '支給材料在庫', icon: 'Goods', path: '/erp/purchase/outsourcing/supplied-material-stock', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 9 },
  { code: 'ERP_OUTSOURCING_USAGE', name: '使用数管理', icon: 'DataLine', path: '/erp/purchase/outsourcing/usage', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 10 },
  { code: 'ERP_OUTSOURCING_MATERIAL_ISSUE', name: '支給材料出庫', icon: 'Upload', path: '/erp/purchase/outsourcing/material-issue', parentCode: 'ERP_PURCHASE_OUTSOURCING', sortOrder: 11 },

  // ===== 3. 在庫管理 (Inventory / WMS) =====
  { code: 'ERP_INVENTORY', name: '在庫管理', path: '/erp/inventory', icon: 'TakeawayBox', parentCode: 'ERP', sortOrder: 5 },
  { code: 'ERP_INVENTORY_HOME', name: '在庫ホーム', icon: 'HomeFilled', path: '/erp/inventory', parentCode: 'ERP_INVENTORY', sortOrder: 0 },
  { code: 'ERP_INVENTORY_LIST', name: '製品在庫照会', icon: 'Goods', path: '/erp/inventory/list', parentCode: 'ERP_INVENTORY', sortOrder: 1 },
  { code: 'ERP_INVENTORY_MATERIAL_LIST', name: '材料在庫照会', icon: 'Collection', path: '/erp/inventory/material-list', parentCode: 'ERP_INVENTORY', sortOrder: 2 },
  { code: 'ERP_INVENTORY_PART_LIST', name: '部品在庫照会', icon: 'Grid', path: '/erp/inventory/part-list', parentCode: 'ERP_INVENTORY', sortOrder: 3 },
  { code: 'ERP_INVENTORY_STOCK_ENTRY', name: '在庫登録管理', icon: 'DocumentAdd', path: '/erp/inventory/stock-entry', parentCode: 'ERP_INVENTORY', sortOrder: 4 },
  { code: 'ERP_INVENTORY_STOCK_TX_LOG', name: '在庫取引記録', icon: 'Notebook', path: '/erp/inventory/stock-transaction-logs', parentCode: 'ERP_INVENTORY', sortOrder: 5 },
  { code: 'ERP_INVENTORY_MANUAL_ENTRY_STATS', name: '実績修正統計', icon: 'DataAnalysis', path: '/erp/inventory/manual-entry-statistics', parentCode: 'ERP_INVENTORY', sortOrder: 5.5 },
  { code: 'ERP_INVENTORY_STOCKTAKE', name: '棚卸管理', icon: 'Files', path: '/erp/inventory/stocktake', parentCode: 'ERP_INVENTORY', sortOrder: 6 },
  { code: 'ERP_INVENTORY_STOCKTAKE_HOME', name: '棚卸管理ホーム', path: '/erp/inventory/stocktake', icon: 'HomeFilled', parentCode: 'ERP_INVENTORY_STOCKTAKE', sortOrder: 0 },
  { code: 'ERP_INVENTORY_STOCKTAKE_LIST', name: '棚卸リスト一覧', path: '/erp/inventory/stocktake/list', icon: 'List', parentCode: 'ERP_INVENTORY_STOCKTAKE', sortOrder: 1 },
  { code: 'ERP_INVENTORY_STOCKTAKE_ENTRY', name: '棚卸登録', path: '/erp/inventory/stocktake/entry', icon: 'DocumentAdd', parentCode: 'ERP_INVENTORY_STOCKTAKE', sortOrder: 2 },
  { code: 'ERP_INVENTORY_STOCKTAKE_STATISTICS', name: '棚卸分析', path: '/erp/inventory/stocktake/statistics', icon: 'DataAnalysis', parentCode: 'ERP_INVENTORY_STOCKTAKE', sortOrder: 3 },
  { code: 'ERP_INVENTORY_STOCKTAKE_VALUE', name: '棚卸金額管理', path: '/erp/inventory/stocktake/value', icon: 'Coin', parentCode: 'ERP_INVENTORY_STOCKTAKE', sortOrder: 4 },
  { code: 'ERP_INVENTORY_STOCKTAKE_CARRYOVER', name: '棚卸繰越管理', path: '/erp/inventory/stocktake/carryover', icon: 'DArrowRight', parentCode: 'ERP_INVENTORY_STOCKTAKE', sortOrder: 5 },

  // ===== 4. 生産管理 (Production Control / PP) =====
  { code: 'ERP_PRODUCTION', name: '生産管理', path: '/erp/production/data-management', icon: 'Cpu', parentCode: 'ERP', sortOrder: 6 },
  { code: 'ERP_PRODUCTION_PLANNING', name: '生産計画', icon: 'Calendar', path: '/erp/production/data-management', parentCode: 'ERP_PRODUCTION', sortOrder: 5 },
  { code: 'ERP_PRODUCTION_DATA', name: '生産データ管理', icon: 'DataBoard', path: '/erp/production/data-management', parentCode: 'ERP_PRODUCTION_PLANNING', sortOrder: 1 },
  { code: 'ERP_PRODUCTION_BASELINE', name: '計画ベースライン', icon: 'Histogram', path: '/erp/production/plan-baseline', parentCode: 'ERP_PRODUCTION_PLANNING', sortOrder: 2 },
  { code: 'ERP_PRODUCTION_PLAN_SCHEDULES', name: '生産スケジュール', icon: 'Calendar', path: '/erp/production/plan-schedules', parentCode: 'ERP_PRODUCTION_PLANNING', sortOrder: 3 },
  { code: 'ERP_PRODUCTION_PROCESS_MACHINE_PLAN', name: '工程别设备别计划', icon: 'Grid', path: '/erp/production/process-machine-plan', parentCode: 'ERP_PRODUCTION_PLANNING', sortOrder: 4.6 },
  { code: 'ERP_PRODUCTION_REQUIREMENTS', name: '生産需要量', icon: 'TrendCharts', path: '/erp/production-requirements/material', parentCode: 'ERP_PRODUCTION', sortOrder: 5.7 },
  { code: 'ERP_PRODUCTION_MAT_REQ', name: '材料需要量', icon: 'Collection', path: '/erp/production-requirements/material', parentCode: 'ERP_PRODUCTION_REQUIREMENTS', sortOrder: 1 },
  { code: 'ERP_PRODUCTION_COMPONENT_REQ', name: '部品需要量', icon: 'Grid', path: '/erp/production-requirements/component', parentCode: 'ERP_PRODUCTION_REQUIREMENTS', sortOrder: 2 },
  { code: 'ERP_PRODUCTION_METRICS', name: '生産指標', icon: 'DataAnalysis', path: '/erp/production/metrics/scrap-rate', parentCode: 'ERP_PRODUCTION', sortOrder: 5.8 },
  { code: 'ERP_PRODUCTION_SCRAP_RATE', name: '廃棄率', icon: 'Delete', path: '/erp/production/metrics/scrap-rate', parentCode: 'ERP_PRODUCTION_METRICS', sortOrder: 1 },
  { code: 'ERP_PRODUCTION_UTILIZATION_RATE', name: '稼働率', icon: 'Odometer', path: '/erp/production/metrics/utilization-rate', parentCode: 'ERP_PRODUCTION_METRICS', sortOrder: 2 },
  { code: 'ERP_PRODUCTION_DEFECT_RATE', name: '不良率', icon: 'Warning', path: '/erp/production/metrics/defect-rate', parentCode: 'ERP_PRODUCTION_METRICS', sortOrder: 3 },
  { code: 'ERP_PRODUCTION_RESULT', name: '生産実績', icon: 'Finished', path: '/erp/production/actual-management', parentCode: 'ERP_PRODUCTION', sortOrder: 8 },
  { code: 'ERP_PRODUCTION_ACTUAL', name: '生産実績管理', icon: 'DocumentChecked', path: '/erp/production/actual-management', parentCode: 'ERP_PRODUCTION_RESULT', sortOrder: 1 },
  { code: 'ERP_PRODUCTION_CONSUME', name: '材料消費実績', icon: 'Goods', path: '/erp/production/consumption', parentCode: 'ERP_PRODUCTION_RESULT', sortOrder: 2 },
  { code: 'ERP_PRODUCTION_PROCESS_ACTUAL', name: '工程別実績', icon: 'Operation', path: '/erp/production/process-actual', parentCode: 'ERP_PRODUCTION_RESULT', sortOrder: 3 },

  // ===== 5. 出荷管理 (Shipping Management) =====
  { code: 'ERP_SHIPPING', name: '出荷管理', path: '/erp/shipping', icon: 'Van', parentCode: 'ERP', sortOrder: 8 },
  { code: 'ERP_SHIPPING_HOME', name: '出荷ホーム', icon: 'HomeFilled', path: '/erp/shipping', parentCode: 'ERP_SHIPPING', sortOrder: 0 },
  { code: 'ERP_SHIPPING_LIST', name: '出荷構成表管理', icon: 'List', path: '/erp/shipping/list', parentCode: 'ERP_SHIPPING', sortOrder: 1 },
  { code: 'ERP_SHIPPING_REPORT', name: '出荷報告書管理', icon: 'Document', path: '/erp/shipping/report', parentCode: 'ERP_SHIPPING', sortOrder: 2 },
  { code: 'ERP_SHIPPING_OVERVIEW', name: '出荷予定表発行', icon: 'Calendar', path: '/erp/shipping/overview', parentCode: 'ERP_SHIPPING', sortOrder: 3 },
  { code: 'ERP_SHIPPING_CONFIRM', name: '出荷確認リスト', icon: 'CircleCheck', path: '/erp/shipping/confirm', parentCode: 'ERP_SHIPPING', sortOrder: 4 },
  { code: 'ERP_SHIPPING_WELDING', name: '出荷管理表', icon: 'Connection', path: '/erp/shipping/welding', parentCode: 'ERP_SHIPPING', sortOrder: 5 },
  { code: 'ERP_SHIPPING_PICKING', name: 'ピッキング管理', icon: 'Pointer', path: '/erp/shipping/picking', parentCode: 'ERP_SHIPPING', sortOrder: 6 },
  { code: 'ERP_SHIPPING_INVENTORY_SHORTAGE', name: '倉庫在庫管理', icon: 'Box', path: '/erp/shipping/inventory-shortage', parentCode: 'ERP_SHIPPING', sortOrder: 7 },
  { code: 'ERP_SHIPPING_ABC', name: 'ABC分析', icon: 'PieChart', path: '/erp/shipping/abc-analysis', parentCode: 'ERP_SHIPPING', sortOrder: 8 },
  { code: 'ERP_SHIPPING_INVENTORY_KPI', name: '在庫KPI・アラート', icon: 'Bell', path: '/erp/shipping/inventory-kpi', parentCode: 'ERP_SHIPPING', sortOrder: 9 },
  { code: 'ERP_SHIPPING_WAREHOUSE_DAILY', name: '倉庫日次在庫', icon: 'Calendar', path: '/erp/shipping/warehouse-daily', parentCode: 'ERP_SHIPPING', sortOrder: 10 },
  { code: 'ERP_QUALITY', name: '品質管理', path: '/erp/quality', icon: 'CircleCheck', parentCode: 'ERP', sortOrder: 9 },
  { code: 'ERP_QUALITY_MATERIAL', name: '材料受入履歴', icon: 'Download', path: '/erp/quality/material-association/receiving-history', parentCode: 'ERP_QUALITY', sortOrder: 1 },
  { code: 'ERP_QUALITY_MATERIAL_TOLERANCE', name: '材料公差管理', icon: 'ScaleToOriginal', path: '/erp/quality/material-association/tolerance-management', parentCode: 'ERP_QUALITY', sortOrder: 1.1 },
  { code: 'ERP_QUALITY_MATERIAL_CUTTING', name: '材料使用取込', icon: 'Scissor', path: '/erp/quality/material-association/cutting-logs', parentCode: 'ERP_QUALITY', sortOrder: 1.15 },
  { code: 'ERP_QUALITY_PRODUCT_MATERIAL', name: '製品材料照会', icon: 'Search', path: '/erp/quality/material-association/product-material', parentCode: 'ERP_QUALITY', sortOrder: 1.2 },
  { code: 'ERP_QUALITY_PRODUCT_MATERIAL_HELP', name: '製品材料照会 操作説明', icon: 'QuestionFilled', path: '/erp/quality/material-association/product-material/help', parentCode: 'ERP_QUALITY', sortOrder: 1.21 },
  { code: 'ERP_QUALITY_PRODUCT', name: '製品関連', icon: 'Goods', path: '/erp/quality/product-association', parentCode: 'ERP_QUALITY', sortOrder: 2 },
  { code: 'ERP_QUALITY_EQUIPMENT', name: 'ローラー使用管理', icon: 'SetUp', path: '/erp/quality/equipment-association', parentCode: 'ERP_QUALITY', sortOrder: 2.5 },

  { code: 'APS', name: 'APS管理メニュー', icon: 'Calendar', sortOrder: 2 },
  { code: 'APS_PRODUCTION_PLAN_CREATE', name: '生産計画作成', icon: 'EditPen', parentCode: 'APS', sortOrder: 1 },
  { code: 'APS_CUTTING_PLANNING', name: '切断計画作成', path: '/aps/cutting-planning', icon: 'Scissor', parentCode: 'APS_PRODUCTION_PLAN_CREATE', sortOrder: 1 },
  { code: 'APS_PLANNING', name: '成型計画作成', icon: 'SetUp', path: '/aps/planning', parentCode: 'APS_PRODUCTION_PLAN_CREATE', sortOrder: 2 },
  { code: 'APS_WELDING_PLANNING', name: '溶接計画作成', path: '/aps/welding-planning', icon: 'Connection', parentCode: 'APS_PRODUCTION_PLAN_CREATE', sortOrder: 3 },
  { code: 'APS_PLATING_PLANNING', name: 'メッキ計画作成', path: '/aps/plating-planning', icon: 'Brush', parentCode: 'APS_PRODUCTION_PLAN_CREATE', sortOrder: 4 },
  { code: 'APS_PRODUCTION_PLAN_VIEW', name: '生産計画一覧', icon: 'View', parentCode: 'APS', sortOrder: 1.5 },
  { code: 'APS_FORMING_PLAN_LIST', name: '成型計画一覧', path: '/aps/planning-list', icon: 'SetUp', parentCode: 'APS_PRODUCTION_PLAN_VIEW', sortOrder: 1 },
  { code: 'APS_WELDING_PLAN_LIST', name: '溶接計画一覧', path: '/aps/welding-planning-list', icon: 'Connection', parentCode: 'APS_PRODUCTION_PLAN_VIEW', sortOrder: 2 },
  { code: 'APS_EQUIPMENT_UTILIZATION_MANAGEMENT', name: '設備稼働管理', icon: 'Odometer', parentCode: 'APS', sortOrder: 3 },
  { code: 'APS_CAPACITY', name: '設備稼働設定', icon: 'Setting', path: '/aps/capacity', parentCode: 'APS_EQUIPMENT_UTILIZATION_MANAGEMENT', sortOrder: 1 },
  { code: 'APS_CAPACITY_MATRIX', name: '設備稼働時間表', icon: 'Grid', path: '/aps/capacity-matrix', parentCode: 'APS_EQUIPMENT_UTILIZATION_MANAGEMENT', sortOrder: 2 },
  { code: 'APS_DAILY_REPORT', name: '日別設備計画表', icon: 'Calendar', path: '/aps/daily-report', parentCode: 'APS_EQUIPMENT_UTILIZATION_MANAGEMENT', sortOrder: 3 },
  { code: 'APS_SCHEDULING', name: 'スケジューリング', icon: 'Timer', path: '/aps/scheduling', parentCode: 'APS', sortOrder: 4 },
  // 非表示（Sidebar から除外）：ロット一覧は成型計画「生産進捗」で代替。ルート /aps/batch-plans は残す。
  // { code: 'APS_BATCH_PLANS', name: 'APSロット計画', path: '/aps/batch-plans', parentCode: 'APS', sortOrder: 5 },
  { code: 'MES', name: 'MES管理メニュー', icon: 'Monitor', sortOrder: 3 },
  { code: 'MES_PRODUCTION_INSTRUCTION', name: '生産指示', icon: 'Tickets', parentCode: 'MES', sortOrder: 0 },
  { code: 'MES_PRODUCTION_INSTR_CUTTING', name: '切断・面取指示', path: '/mes/productionInstruction/cutting', icon: 'Scissor', parentCode: 'MES_PRODUCTION_INSTRUCTION', sortOrder: 1 },
  { code: 'MES_PRODUCTION_INSTR_FORMING', name: '成型指示', path: '/mes/productionInstruction/forming', icon: 'SetUp', parentCode: 'MES_PRODUCTION_INSTRUCTION', sortOrder: 2 },
  { code: 'MES_PRODUCTION_INSTR_WELDING', name: '溶接指示', path: '/mes/productionInstruction/welding', icon: 'Connection', parentCode: 'MES_PRODUCTION_INSTRUCTION', sortOrder: 3 },
  { code: 'MES_PRODUCTION_INSTR_PLATING', name: 'メッキ指示', path: '/mes/productionInstruction/plating', icon: 'Brush', parentCode: 'MES_PRODUCTION_INSTRUCTION', sortOrder: 4 },
  { code: 'MES_ACTUAL_DATA_COLLECTION', name: '実績収集', icon: 'EditPen', parentCode: 'MES', sortOrder: 1 },
  { code: 'MES_PRODUCTION_MONITOR', name: '生産モニター', path: '/mes/actualDataCollection/monitor', icon: 'View', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 0 },
  { code: 'MES_ACTUAL_CUTTING', name: '切断実績収集', path: '/mes/actualDataCollection/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 1 },
  { code: 'MES_ACTUAL_CHAMFERING', name: '面取実績収集', path: '/mes/actualDataCollection/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 2 },
  { code: 'MES_ACTUAL_FORMING', name: '成型実績収集', path: '/mes/actualDataCollection/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 3 },
  { code: 'MES_ACTUAL_PLATING', name: 'メッキ実績収集', path: '/mes/actualDataCollection/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 4 },
  { code: 'MES_ACTUAL_WELDING', name: '溶接実績収集', path: '/mes/actualDataCollection/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 5 },
  { code: 'MES_ACTUAL_INSPECTION', name: '検査実績収集', path: '/mes/actualDataCollection/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_DATA_COLLECTION', sortOrder: 6 },
  { code: 'MES_MONITORING', name: 'モニタリング', icon: 'View', parentCode: 'MES', sortOrder: 1.5 },
  { code: 'MES_MONITOR_INSPECTION', name: '検査モニタ', path: '/mes/monitoring/inspection', icon: 'DocumentChecked', parentCode: 'MES_MONITORING', sortOrder: 1 },
  { code: 'MES_MONITOR_WELDING', name: '溶接モニタ', path: '/mes/monitoring/welding', icon: 'Connection', parentCode: 'MES_MONITORING', sortOrder: 2 },
  { code: 'MES_ACTUAL_COLLECTION_REGISTRATION', name: '実績登録', icon: 'Edit', parentCode: 'MES', sortOrder: 1.8 },
  { code: 'MES_ACTUAL_REG_CUTTING', name: '切断実績登録', path: '/mes/actualCollectionRegistration/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_COLLECTION_REGISTRATION', sortOrder: 1 },
  { code: 'MES_ACTUAL_REG_CHAMFERING', name: '面取実績登録', path: '/mes/actualCollectionRegistration/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_COLLECTION_REGISTRATION', sortOrder: 2 },
  { code: 'MES_ACTUAL_REG_FORMING', name: '成型実績登録', path: '/mes/actualCollectionRegistration/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_COLLECTION_REGISTRATION', sortOrder: 3 },
  { code: 'MES_ACTUAL_REG_PLATING', name: 'メッキ実績登録', path: '/mes/actualCollectionRegistration/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_COLLECTION_REGISTRATION', sortOrder: 4 },
  { code: 'MES_ACTUAL_REG_WELDING', name: '溶接実績登録', path: '/mes/actualCollectionRegistration/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_COLLECTION_REGISTRATION', sortOrder: 5 },
  { code: 'MES_ACTUAL_REG_INSPECTION', name: '検査実績登録', path: '/mes/actualCollectionRegistration/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_COLLECTION_REGISTRATION', sortOrder: 6 },
  { code: 'MES_ACTUAL_ANALYSIS', name: '実績分析項目', icon: 'Histogram', parentCode: 'MES', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', name: '生産性分析', icon: 'TrendCharts', parentCode: 'MES_ACTUAL_ANALYSIS', sortOrder: 1 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY_CUTTING', name: '切断生産性', path: '/mes/actualAnalysis/productivity/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', sortOrder: 1 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY_CHAMFERING', name: '面取生産性', path: '/mes/actualAnalysis/productivity/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY_FORMING', name: '成型生産性', path: '/mes/actualAnalysis/productivity/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', sortOrder: 3 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY_PLATING', name: 'メッキ生産性', path: '/mes/actualAnalysis/productivity/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', sortOrder: 4 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY_WELDING', name: '溶接生産性', path: '/mes/actualAnalysis/productivity/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', sortOrder: 5 },
  { code: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY_INSPECTION', name: '検査生産性', path: '/mes/actualAnalysis/productivity/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_ANALYSIS_PRODUCTIVITY', sortOrder: 6 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION', name: '稼働率分析', icon: 'Odometer', parentCode: 'MES_ACTUAL_ANALYSIS', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION_CUTTING', name: '切断稼働率', path: '/mes/actualAnalysis/utilization/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_ANALYSIS_UTILIZATION', sortOrder: 1 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION_CHAMFERING', name: '面取稼働率', path: '/mes/actualAnalysis/utilization/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_ANALYSIS_UTILIZATION', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION_FORMING', name: '成型稼働率', path: '/mes/actualAnalysis/utilization/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_ANALYSIS_UTILIZATION', sortOrder: 3 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION_PLATING', name: 'メッキ稼働率', path: '/mes/actualAnalysis/utilization/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_ANALYSIS_UTILIZATION', sortOrder: 4 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION_WELDING', name: '溶接稼働率', path: '/mes/actualAnalysis/utilization/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_ANALYSIS_UTILIZATION', sortOrder: 5 },
  { code: 'MES_ACTUAL_ANALYSIS_UTILIZATION_INSPECTION', name: '検査稼働率', path: '/mes/actualAnalysis/utilization/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_ANALYSIS_UTILIZATION', sortOrder: 6 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS', name: '進捗分析', icon: 'DataLine', parentCode: 'MES_ACTUAL_ANALYSIS', sortOrder: 3 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS_CUTTING', name: '切断進捗', path: '/mes/actualAnalysis/progress/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_ANALYSIS_PROGRESS', sortOrder: 1 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS_CHAMFERING', name: '面取進捗', path: '/mes/actualAnalysis/progress/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_ANALYSIS_PROGRESS', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS_FORMING', name: '成型進捗', path: '/mes/actualAnalysis/progress/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_ANALYSIS_PROGRESS', sortOrder: 3 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS_PLATING', name: 'メッキ進捗', path: '/mes/actualAnalysis/progress/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_ANALYSIS_PROGRESS', sortOrder: 4 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS_WELDING', name: '溶接進捗', path: '/mes/actualAnalysis/progress/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_ANALYSIS_PROGRESS', sortOrder: 5 },
  { code: 'MES_ACTUAL_ANALYSIS_PROGRESS_INSPECTION', name: '検査進捗', path: '/mes/actualAnalysis/progress/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_ANALYSIS_PROGRESS', sortOrder: 6 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY', name: '品質分析', icon: 'CircleCheck', parentCode: 'MES_ACTUAL_ANALYSIS', sortOrder: 4 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY_CUTTING', name: '切断品質', path: '/mes/actualAnalysis/quality/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_ANALYSIS_QUALITY', sortOrder: 1 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY_CHAMFERING', name: '面取品質', path: '/mes/actualAnalysis/quality/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_ANALYSIS_QUALITY', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY_FORMING', name: '成型品質', path: '/mes/actualAnalysis/quality/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_ANALYSIS_QUALITY', sortOrder: 3 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY_PLATING', name: 'メッキ品質', path: '/mes/actualAnalysis/quality/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_ANALYSIS_QUALITY', sortOrder: 4 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY_WELDING', name: '溶接品質', path: '/mes/actualAnalysis/quality/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_ANALYSIS_QUALITY', sortOrder: 5 },
  { code: 'MES_ACTUAL_ANALYSIS_QUALITY_INSPECTION', name: '検査品質', path: '/mes/actualAnalysis/quality/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_ANALYSIS_QUALITY', sortOrder: 6 },
  { code: 'MES_ACTUAL_ANALYSIS_COST', name: 'コスト分析', icon: 'Coin', parentCode: 'MES_ACTUAL_ANALYSIS', sortOrder: 5 },
  { code: 'MES_ACTUAL_ANALYSIS_COST_CUTTING', name: '切断コスト', path: '/mes/actualAnalysis/cost/cutting', icon: 'Scissor', parentCode: 'MES_ACTUAL_ANALYSIS_COST', sortOrder: 1 },
  { code: 'MES_ACTUAL_ANALYSIS_COST_CHAMFERING', name: '面取コスト', path: '/mes/actualAnalysis/cost/chamfering', icon: 'Crop', parentCode: 'MES_ACTUAL_ANALYSIS_COST', sortOrder: 2 },
  { code: 'MES_ACTUAL_ANALYSIS_COST_FORMING', name: '成型コスト', path: '/mes/actualAnalysis/cost/forming', icon: 'SetUp', parentCode: 'MES_ACTUAL_ANALYSIS_COST', sortOrder: 3 },
  { code: 'MES_ACTUAL_ANALYSIS_COST_PLATING', name: 'メッキコスト', path: '/mes/actualAnalysis/cost/plating', icon: 'Brush', parentCode: 'MES_ACTUAL_ANALYSIS_COST', sortOrder: 4 },
  { code: 'MES_ACTUAL_ANALYSIS_COST_WELDING', name: '溶接コスト', path: '/mes/actualAnalysis/cost/welding', icon: 'Connection', parentCode: 'MES_ACTUAL_ANALYSIS_COST', sortOrder: 5 },
  { code: 'MES_ACTUAL_ANALYSIS_COST_INSPECTION', name: '検査コスト', path: '/mes/actualAnalysis/cost/inspection', icon: 'DocumentChecked', parentCode: 'MES_ACTUAL_ANALYSIS_COST', sortOrder: 6 },
  { code: 'MASTER', name: 'マスタ管理', icon: 'Files', sortOrder: 4 },
  { code: 'MASTER_LIST', name: 'マスタ', icon: 'Memo', parentCode: 'MASTER', sortOrder: 1 },
  { code: 'MASTER_PRODUCT', name: '製品マスタ', icon: 'Goods', path: '/master/product', parentCode: 'MASTER_LIST', sortOrder: 1 },
  { code: 'MASTER_MATERIAL', name: '材料マスタ', icon: 'Collection', path: '/master/material', parentCode: 'MASTER_LIST', sortOrder: 2 },
  { code: 'MASTER_MATERIAL_INSPECTION', name: '材料検品マスタ', icon: 'CircleCheck', path: '/master/material-inspection', parentCode: 'MASTER_LIST', sortOrder: 2.5 },
  { code: 'MASTER_PART', name: '部品マスタ', icon: 'Grid', path: '/master/part', parentCode: 'MASTER_LIST', sortOrder: 2.75 },
  { code: 'MASTER_SUPPLIER', name: '仕入先マスタ', icon: 'OfficeBuilding', path: '/master/supplier', parentCode: 'MASTER_LIST', sortOrder: 3 },
  { code: 'MASTER_PROCESS', name: '工程マスタ', icon: 'Operation', path: '/master/process', parentCode: 'MASTER_LIST', sortOrder: 4 },
  { code: 'MASTER_PROCESS_ROUTE', name: '工程ルートマスタ', icon: 'Share', path: '/master/process-route', parentCode: 'MASTER_LIST', sortOrder: 5 },
  { code: 'MASTER_PRODUCT_PROCESS_ROUTE', name: '製品ルートマスタ', icon: 'Guide', path: '/master/product-process-route', parentCode: 'MASTER_LIST', sortOrder: 6 },
  { code: 'MASTER_CUSTOMER', name: '顧客マスタ', icon: 'User', path: '/master/customer', parentCode: 'MASTER_LIST', sortOrder: 7 },
  { code: 'MASTER_CARRIER', name: '運送便マスタ', icon: 'Van', path: '/master/carrier', parentCode: 'MASTER_LIST', sortOrder: 8 },
  { code: 'MASTER_MACHINE', name: '設備マスタ', icon: 'Cpu', path: '/master/machine', parentCode: 'MASTER_LIST', sortOrder: 9 },
  { code: 'MASTER_ROLLER_MASTER', name: 'ローラーマスタ', icon: 'SetUp', path: '/master/roller-master', parentCode: 'MASTER_LIST', sortOrder: 9.5 },
  { code: 'MASTER_DESTINATION', name: '納入先マスタ', icon: 'Location', path: '/master/destination', parentCode: 'MASTER_LIST', sortOrder: 10 },
  { code: 'MASTER_DESTINATION_HOLIDAY', name: '納入先休日設定', icon: 'Calendar', path: '/master/destination/holiday', parentCode: 'MASTER_LIST', sortOrder: 11 },
  { code: 'MASTER_COMPANY_WORK_CALENDAR', name: '会社稼働カレンダー', icon: 'Calendar', path: '/master/company-work-calendar', parentCode: 'MASTER_LIST', sortOrder: 12 },
  { code: 'MASTER_INSPECTION_INSPECTOR_WORK_SCHEDULE', name: '検査員所定工時管理', icon: 'Clock', path: '/master/inspection-inspector-work-schedule', parentCode: 'MASTER_LIST', sortOrder: 13 },
  { code: 'MASTER_BOM', name: 'BOM', icon: 'Share', parentCode: 'MASTER', sortOrder: 2 },
  { code: 'MASTER_PRODUCT_PROCESS_BOM', name: '製品工程BOM', icon: 'Share', path: '/master/bom/product-process', parentCode: 'MASTER_BOM', sortOrder: 1 },
  { code: 'MASTER_PRODUCT_MACHINE_CONFIG', name: '製品機器設定', icon: 'Cpu', path: '/master/bom/product-machine-config', parentCode: 'MASTER_BOM', sortOrder: 2 },
  { code: 'MASTER_EQUIPMENT_EFFICIENCY', name: '設備能率管理', icon: 'Odometer', path: '/master/bom/equipment-efficiency', parentCode: 'MASTER_BOM', sortOrder: 3 },
  { code: 'MASTER_ROLLER_BOM', name: 'ローラーBOM管理', icon: 'SetUp', path: '/master/bom/roller-bom', parentCode: 'MASTER_BOM', sortOrder: 3.5 },
  { code: 'MASTER_PRODUCT_BOM_DETAIL', name: '製品BOM表管理', icon: 'List', path: '/master/bom/product-bom', parentCode: 'MASTER_BOM', sortOrder: 4 },
  { code: 'MASTER_PROCESS_PROCESSING_FEE', name: '工程加工費マスタ', icon: 'Coin', path: '/master/bom/process-processing-fee', parentCode: 'MASTER_LIST', sortOrder: 6.5 },
  { code: 'MASTER_PROCESS_DEFECT_ITEMS', name: '工程別不良項目マスタ', icon: 'Warning', path: '/master/bom/process-defect-items', parentCode: 'MASTER_BOM', sortOrder: 5 },
  { code: 'MASTER_UNIT_PRICE', name: '工程別標準原価', icon: 'PriceTag', path: '/master/bom/product-unit-price', parentCode: 'MASTER_BOM', sortOrder: 6 },
  { code: 'OPERATION_MANUALS', name: 'マニュアル', icon: 'Reading', sortOrder: 4.5 },
  { code: 'OP_MANUAL_FORMING', name: '成型工程 生産指示・実績収集', icon: 'SetUp', path: '/operation-manuals/forming-instruction', parentCode: 'OPERATION_MANUALS', sortOrder: 1 },
  { code: 'OP_MANUAL_FORMING_PLANNING', name: '成型工程 計画作成', icon: 'Calendar', path: '/operation-manuals/forming-planning', parentCode: 'OPERATION_MANUALS', sortOrder: 2 },
  { code: 'OP_MANUAL_WELDING', name: '溶接工程 生産指示・実績収集', icon: 'Connection', path: '/operation-manuals/welding-instruction', parentCode: 'OPERATION_MANUALS', sortOrder: 3 },
  { code: 'OP_MANUAL_WELDING_PLANNING', name: '溶接工程 計画作成', icon: 'Calendar', path: '/operation-manuals/welding-planning', parentCode: 'OPERATION_MANUALS', sortOrder: 4 },
  { code: 'OP_MANUAL_CUTTING', name: '切断面取 生産指示・実績収集', icon: 'Scissor', path: '/operation-manuals/cutting-instruction', parentCode: 'OPERATION_MANUALS', sortOrder: 5 },
  { code: 'OP_MANUAL_PLAN_BASELINE', name: '生産計画ベースライン管理', icon: 'Histogram', path: '/operation-manuals/plan-baseline', parentCode: 'OPERATION_MANUALS', sortOrder: 6 },
  { code: 'OP_MANUAL_INSPECTION', name: '検査実績収集', icon: 'DocumentChecked', path: '/operation-manuals/inspection-actual', parentCode: 'OPERATION_MANUALS', sortOrder: 7 },
  { code: 'OP_MANUAL_INSPECTION_REGISTRATION', name: '検査実績収集登録', icon: 'EditPen', path: '/operation-manuals/inspection-actual-registration', parentCode: 'OPERATION_MANUALS', sortOrder: 8 },
  { code: 'OP_MANUAL_INSPECTION_MONITOR', name: '検査モニタ', icon: 'Monitor', path: '/operation-manuals/inspection-monitor', parentCode: 'OPERATION_MANUALS', sortOrder: 9 },
  { code: 'OP_MANUAL_INSPECTION_PRODUCTIVITY', name: '検査工程 — 生産性分析', icon: 'TrendCharts', path: '/operation-manuals/inspection-productivity', parentCode: 'OPERATION_MANUALS', sortOrder: 10 },
  { code: 'SYSTEM', name: 'システム管理', icon: 'Setting', sortOrder: 5 },
  { code: 'SYSTEM_USER', name: 'ユーザー・組織', icon: 'User', parentCode: 'SYSTEM', sortOrder: 1 },
  { code: 'SYSTEM_HOME', name: 'システムホーム', icon: 'HomeFilled', path: '/system', parentCode: 'SYSTEM_USER', sortOrder: 0 },
  { code: 'SYSTEM_USERS', name: 'ユーザー管理', icon: 'UserFilled', path: '/system/users', parentCode: 'SYSTEM_USER', sortOrder: 1 },
  { code: 'SYSTEM_ORG', name: '組織・部門管理', icon: 'OfficeBuilding', path: '/system/organization', parentCode: 'SYSTEM_USER', sortOrder: 2 },
  { code: 'SYSTEM_ROLE', name: '権限・ロール管理', icon: 'Key', path: '/system/roles', parentCode: 'SYSTEM_USER', sortOrder: 3 },
  { code: 'SYSTEM_SETTINGS', name: 'システム設定', icon: 'Tools', parentCode: 'SYSTEM', sortOrder: 2 },
  { code: 'SYSTEM_NUMBERING', name: '採番ルール管理', icon: 'Sort', path: '/system/numbering', parentCode: 'SYSTEM_SETTINGS', sortOrder: 1 },
  { code: 'SYSTEM_WORKFLOW', name: 'ワークフロー設定', icon: 'Connection', path: '/system/workflow', parentCode: 'SYSTEM_SETTINGS', sortOrder: 2 },
  { code: 'SYSTEM_NOTIFICATION', name: '通知センター', icon: 'Bell', path: '/system/notification', parentCode: 'SYSTEM_SETTINGS', sortOrder: 3 },
  { code: 'SYSTEM_REPORTS', name: '報告センター', icon: 'Document', path: '/system/reports', parentCode: 'SYSTEM_SETTINGS', sortOrder: 4 },
  { code: 'SYSTEM_LOGS', name: 'システムログ', icon: 'Notebook', path: '/system/logs', parentCode: 'SYSTEM_SETTINGS', sortOrder: 4 },
  { code: 'SYSTEM_DATA', name: 'データ管理', icon: 'FolderOpened', path: '/system/data', parentCode: 'SYSTEM_SETTINGS', sortOrder: 5 },
  { code: 'SYSTEM_MENUS', name: 'メニュー管理', icon: 'Menu', path: '/system/menus', parentCode: 'SYSTEM_SETTINGS', sortOrder: 6 },
  { code: 'SYSTEM_FILE_WATCHER', name: 'ファイル監視設定', icon: 'View', path: '/system/file-watcher', parentCode: 'SYSTEM_SETTINGS', sortOrder: 7 },
  { code: 'SYSTEM_DATABASE', name: 'データベース', icon: 'Cpu', parentCode: 'SYSTEM', sortOrder: 3 },
  { code: 'SYSTEM_DB_ORDER_DAILY', name: 'order_daily', icon: 'Calendar', path: '/system/database/order/daily', parentCode: 'SYSTEM_DATABASE', sortOrder: 1 },

  // ===== FIN（経理・原価・人事）— finMenuConfig（原価管理含む） =====
  ...finMenuConfig,
]
