<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinHomePage :title="title" :subtitle="subtitle" :cards="cards" />
</template>

<script setup lang="ts">
import FinHomePage from '@/views/fin/components/FinHomePage.vue'
import type { FinHomeCard } from '@/views/fin/components/types'

const title = '会計ホーム'
const subtitle = '会計業務メニュー'
const cards: FinHomeCard[] = [{"title": "仕訳帳", "desc": "仕訳の登録・照会・転記", "path": "/fin/accounting/journals", "icon": "Tickets"}, {"title": "総勘定元帳", "desc": "勘定科目別の取引明細", "path": "/fin/accounting/ledger", "icon": "Notebook"}, {"title": "試算表", "desc": "借方・貸方残高の一覧", "path": "/fin/accounting/trial-balance", "icon": "DataAnalysis"}, {"title": "貸借対照表・PL", "desc": "財務諸表（BS・PL）", "path": "/fin/accounting/statements", "icon": "Histogram"}, {"title": "月次・年次決算", "desc": "期間締め・決算処理", "path": "/fin/accounting/closing", "icon": "Lock"}, {"title": "仕訳取込・連携", "desc": "ERP等からの自動仕訳", "path": "/fin/accounting/import", "icon": "Upload"}]
</script>
