<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinHomePage :title="title" :subtitle="subtitle" :cards="cards" />
</template>

<script setup lang="ts">
import FinHomePage from '@/views/fin/components/FinHomePage.vue'
import type { FinHomeCard } from '@/views/fin/components/types'

const title = 'ホーム'
const subtitle = '経理・原価・人事のトップメニュー'
const cards: FinHomeCard[] = [{"title": "原価管理", "desc": "標準・実際原価・配賦・WIP", "path": "/fin/costing", "icon": "Coin"}, {"title": "会計", "desc": "仕訳・元帳・試算表・決算", "path": "/fin/accounting", "icon": "Notebook"}, {"title": "売上・請求", "desc": "請求書・入金・売掛管理", "path": "/fin/receivables/invoices", "icon": "Wallet"}, {"title": "仕入・支払", "desc": "仕入請求・支払・買掛管理", "path": "/fin/payables/bills", "icon": "CreditCard"}, {"title": "経費精算", "desc": "経費申請・承認", "path": "/fin/expense/applications", "icon": "Coin"}, {"title": "勤怠", "desc": "出退勤・休暇・シフト", "path": "/fin/attendance/clock", "icon": "Timer"}, {"title": "給与", "desc": "給与計算・明細・振込", "path": "/fin/payroll/runs", "icon": "Money"}, {"title": "人事", "desc": "社員・契約・年末調整", "path": "/fin/hr/employees", "icon": "User"}, {"title": "経理マスタ", "desc": "勘定科目・税区分・取引先", "path": "/fin/master/accounts", "icon": "Collection"}, {"title": "従業員ポータル", "desc": "経費・休暇・給与明細（自己サービス）", "path": "/fin/self", "icon": "Avatar"}, {"title": "設定", "desc": "会計設定・承認フロー", "path": "/fin/settings", "icon": "Setting"}]
</script>
