<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinHomePage :title="title" :subtitle="subtitle" :cards="cards" />
</template>

<script setup lang="ts">
import FinHomePage from '@/views/fin/components/FinHomePage.vue'
import type { FinHomeCard } from '@/views/fin/components/types'

const title = 'マイページ'
const subtitle = '従業員向けポータル'
const cards: FinHomeCard[] = [{"title": "経費申請", "desc": "経費精算の申請・照会", "path": "/fin/expense/applications", "icon": "EditPen"}, {"title": "休暇申請", "desc": "休暇の申請・承認状況", "path": "/fin/attendance/leave", "icon": "Calendar"}, {"title": "給与明細", "desc": "給与明細の参照", "path": "/fin/payroll/slips", "icon": "Document"}, {"title": "勤怠記録", "desc": "出退勤の記録", "path": "/fin/attendance/clock", "icon": "Timer"}]
</script>
