#!/usr/bin/env python3
"""
FIN（経理・原価・人事）コードジェネレータ。

docs/fin/fin-domain-manifest.yaml を単一ソースとして、以下を生成する:
  --target db        backend/database/migrations/36_fin_full_schema.sql
  --target backend   backend/app/modules/fin/**（models / schemas / api / __init__）
  --target frontend  frontend/src/views/fin/**（画面ラッパ）
  --target menu      frontend/src/router/finMenuConfig.ts
  --target router    frontend/src/shared/router/finRoutes.ts
  --target locales   frontend/src/locales/fin/{ja,zh,en,vi}.ts
  --target all       上記すべて

依存: PyYAML のみ（Jinja2 不要・純 Python テンプレート）。
生成ファイルは先頭に GENERATED マーカーを持ち、再実行で上書きされる。
手書きの中核ロジック（posting_service / calc_engine / 汎用 Vue コンポーネント等）は対象外。
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "docs" / "fin" / "fin-domain-manifest.yaml"

GEN_PY = "# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND\n"
GEN_TS = "// @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND\n"
GEN_SQL = "-- @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND\n"

AUDIT_OUT = ["created_by", "updated_by", "created_at", "updated_at"]


# --------------------------------------------------------------------------- #
# 型マッピング
# --------------------------------------------------------------------------- #
def sa_type(col: dict) -> str:
    t = col["type"]
    if t == "str":
        return f"String({col.get('len', 255)})"
    if t == "text":
        return "Text"
    if t == "int":
        return "Integer"
    if t == "bigint":
        return "BigInteger"
    if t == "dec":
        return f"Numeric({col.get('p', 18)}, {col.get('s', 2)})"
    if t == "date":
        return "Date"
    if t == "datetime":
        return "DateTime"
    if t == "bool":
        return "Boolean"
    raise ValueError(f"unknown type {t}")


def sql_type(col: dict) -> str:
    # fin_* テーブルの id は BIGINT。FK 参照列も同一型に揃える（MySQL 3780 回避）
    if col.get("fk") and str(col["fk"]).endswith(".id"):
        return "BIGINT"
    t = col["type"]
    if t == "str":
        return f"VARCHAR({col.get('len', 255)})"
    if t == "text":
        return "TEXT"
    if t == "int":
        return "INT"
    if t == "bigint":
        return "BIGINT"
    if t == "dec":
        return f"DECIMAL({col.get('p', 18)}, {col.get('s', 2)})"
    if t == "date":
        return "DATE"
    if t == "datetime":
        return "DATETIME"
    if t == "bool":
        return "TINYINT(1)"
    raise ValueError(f"unknown type {t}")


def py_type(col: dict) -> str:
    t = col["type"]
    if t in ("str", "text"):
        return "str"
    if t in ("int", "bigint"):
        return "int"
    if t == "dec":
        return "float"
    if t == "date":
        return "date"
    if t == "datetime":
        return "datetime"
    if t == "bool":
        return "bool"
    raise ValueError(f"unknown type {t}")


def ts_field_type(col: dict) -> str:
    t = col["type"]
    if t == "bool":
        return "switch"
    if t in ("int", "bigint", "dec"):
        return "number"
    if t == "date":
        return "date"
    if t == "datetime":
        return "datetime"
    return "text"


# --------------------------------------------------------------------------- #
# 命名ヘルパ
# --------------------------------------------------------------------------- #
def resource_slug(table: str) -> str:
    """fin_journal_entry -> journal-entry"""
    name = table[4:] if table.startswith("fin_") else table
    return name.replace("_", "-")


def comp_name(menu_code: str) -> str:
    """FIN_ACCT_JOURNAL -> FinAcctJournal"""
    return "".join(p.capitalize() for p in menu_code.split("_"))


def iter_entities(domain: dict):
    """親 + 子をフラットに列挙。子には parent 情報を付与。"""
    for ent in domain.get("entities", []):
        yield ent, None
        for child in ent.get("children", []):
            yield child, ent


def entity_columns(ent: dict, parent: dict | None):
    """parent_fk を含む全列を返す。"""
    cols = []
    if parent is not None:
        cols.append({
            "name": ent["parent_fk"],
            "type": "bigint",
            "fk": parent["table"] + ".id",
            "on_delete": "CASCADE",
            "nullable": False,
            "comment": "親ID",
        })
    cols.extend(ent.get("columns", []))
    return cols


def editable_columns(ent: dict, parent: dict | None):
    return entity_columns(ent, parent)


# --------------------------------------------------------------------------- #
# SQL COMMENT 日本語化
# --------------------------------------------------------------------------- #
# manifest の英語列挙コメント → 日本語（MySQL COMMENT 用）
_COMMENT_ENUM_JA: dict[str, str] = {
    "open/closed": "状態（open/closed）",
    "open/closing/closed": "状態（open/closing/closed）",
    "manual/sales/purchase/transfer/manufacturing/depreciation/payroll": "種別（手動/売上/仕入/移動/製造/減価償却/給与）",
    "draft/posted/canceled": "状態（下書き/転記済/取消）",
    "fin_journal_source.id": "仕訳ソースID",
    "SALES_POSTED 等": "イベント種別（売上計上等）",
    "erp/expense/payroll": "連携元（ERP/経費/給与）",
    "pending/generated/skipped": "状態（未生成/生成済/スキップ）",
    "draft/issued/paid/overdue": "状態（下書き/発行済/入金済/延滞）",
    "unmatched/matched": "状態（未消込/消込済）",
    "draft/confirmed/paid": "状態（下書き/確定/支払済）",
    "scheduled/paid": "状態（予定/支払済）",
    "draft/submitted/approved/rejected/paid": "状態（下書き/申請中/承認済/却下/支払済）",
    "workday/holiday/company_holiday": "日種別（平日/祝日/会社休日）",
    "HH:MM": "時刻（HH:MM）",
    "normal/late/absent/leave": "状態（正常/遅刻/欠勤/休暇）",
    "submitted/approved/rejected": "状態（申請中/承認済/却下）",
    "earning/deduction": "種別（支給/控除）",
    "draft/calculated/confirmed/paid": "状態（下書き/計算済/確定/支払済）",
    "users.id 連携": "ユーザーID連携",
    "regular/contract/part_time": "雇用形態（正社員/契約/パート）",
    "active/retired": "状態（在籍/退職）",
    "draft/confirmed": "状態（下書き/確定）",
    "asset/liability/equity/revenue/expense": "科目区分（資産/負債/純資産/収益/費用）",
    "taxable/exempt/non_taxable": "税種別（課税/非課税/不課税）",
    "customer/supplier/both": "種別（得意先/仕入先/両方）",
    "ERP customer.id 連携": "ERP顧客ID連携",
    "ERP supplier.id 連携": "ERP仕入先ID連携",
    "ordinary/checking": "口座種別（普通/当座）",
    "税方式 invoice/standard": "税方式（インボイス/標準）",
    "invoice/standard": "税方式（インボイス/標準）",
    "端数処理 round/floor/ceil": "端数処理（四捨五入/切捨/切上）",
    "round/floor/ceil": "端数処理（四捨五入/切捨/切上）",
    "expense/leave/payroll": "対象（経費/休暇/給与）",
    "pending/approved/rejected": "状態（承認待ち/承認済/却下）",
    "freee/yayoi/csv": "出力形式（freee/弥生/CSV）",
    "success/failed": "結果（成功/失敗）",
    "YYYY-MM": "年月（YYYY-MM）",
    "振込/手形/現金": "入金方法（振込/手形/現金）",
    "振込/手形": "支払方法（振込/手形）",
    "元伝票番号/ID": "元伝票番号またはID",
    "生成された仕訳": "生成先仕訳ID",
    "親ID": "親レコードID",
}

_COL_NAME_JA: dict[str, str] = {
    "line_no": "行番号",
    "name": "名称",
    "partner_id": "取引先ID",
    "partner_name": "取引先名",
    "subtotal": "税抜金額",
    "tax_amount": "消費税額",
    "total_amount": "合計金額",
    "paid_amount": "支払済金額",
    "quantity": "数量",
    "unit_price": "単価",
    "amount": "金額",
    "tax_code": "税区分コード",
    "item_name": "品目名",
    "email": "メールアドレス",
    "start_date": "開始日",
    "end_date": "終了日",
    "employee_id": "社員ID",
    "employee_name": "社員名",
    "shift_date": "シフト日",
    "approved_at": "承認日時",
    "remarks": "備考",
    "description": "摘要",
    "title": "件名",
    "reason": "理由",
    "dependents": "扶養人数",
    "version": "バージョン",
    "record_count": "出力件数",
    "file_name": "ファイル名",
    "message": "メッセージ",
    "file_path": "ファイルパス",
    "content_type": "コンテンツ種別",
    "file_size": "ファイルサイズ（バイト）",
    "ref_type": "関連種別",
    "ref_id": "関連ID",
    "flow_code": "承認フローコード",
    "target_type": "対象種別",
    "target_id": "対象ID",
    "current_step": "現在の承認ステップ",
    "export_type": "出力形式",
    "target_period": "対象年月",
    "is_active": "有効フラグ",
    "sort_order": "表示順",
    "pay_item_code": "支給控除項目コード",
    "has_receipt": "領収書添付フラグ",
    "base_currency": "基準通貨",
    "steps_json": "承認ステップ定義（JSON）",
    "payload_json": "連携ペイロード（JSON）",
    "detail_json": "明細（JSON）",
    "account_number": "口座番号",
    "account_holder": "口座名義",
    "approver_id": "承認者ID",
    "bank_account_id": "銀行口座ID",
    "method": "決済方法",
    "allocated_amount": "充当金額",
    "journal_entry_id": "仕訳ID",
    "source_invoice_id": "ERP請求書ID",
    "user_id": "ユーザーID",
    "contract_type": "契約種別",
    "base_salary": "基本給",
    "rate": "税率（%）",
    "kind": "税種別",
    "partner_type": "取引先種別",
    "account_type": "口座種別",
    "gl_account_code": "勘定科目コード",
    "item_type": "項目種別",
    "is_taxable": "課税対象フラグ",
    "is_paid": "有給フラグ",
    "requires_receipt": "領収書必須フラグ",
    "category_code": "経費区分コード",
    "leave_code": "休暇区分コード",
    "shift_code": "シフトコード",
    "source_type": "ソース種別",
    "source_module": "連携元モジュール",
    "source_ref": "元伝票参照",
    "event_date": "事象日",
    "fiscal_start_month": "期首月（1-12）",
    "tax_method": "消費税方式",
    "rounding": "端数処理方式",
    "company_name": "会社名",
    "run_no": "給与計算番号",
    "target_month": "対象年月",
    "pay_date": "支給日",
    "total_gross": "総支給額",
    "total_deduction": "総控除額",
    "total_net": "差引支給額",
    "gross_amount": "総支給額",
    "deduction_amount": "控除合計額",
    "net_amount": "差引支給額",
    "total_income": "給与収入",
    "deduction_total": "所得控除合計",
    "tax_settled": "年調後税額",
    "refund_amount": "還付・追徴額",
    "target_year": "対象年",
    "health_insurance_grade": "健康保険等級",
    "pension_grade": "厚生年金等級",
    "standard_monthly": "標準報酬月額",
    "min_amount": "下限金額",
    "max_amount": "上限金額",
    "tax_amount_col": "源泉税額",
    "days": "日数",
    "closed_at": "締め日時",
    "period_ym": "計上年月",
    "entry_type": "仕訳種別",
    "entry_date": "仕訳日",
    "journal_no": "仕訳番号",
    "application_no": "申請番号",
    "invoice_no": "請求番号",
    "receipt_no": "入金番号",
    "bill_no": "仕入請求番号",
    "payment_no": "支払番号",
    "employee_no": "社員番号",
    "code": "コード",
    "year_month": "年月",
    "fiscal_year_id": "会計年度ID",
    "entry_id": "仕訳ID",
    "invoice_id": "請求書ID",
    "receipt_id": "入金ID",
    "bill_id": "仕入請求ID",
    "payment_id": "支払ID",
    "application_id": "経費申請ID",
    "run_id": "給与計算ID",
    "source_id": "ソースID",
    "customer_id": "顧客ID",
    "supplier_id": "仕入先ID",
    "closing_day": "締め日",
    "payment_terms": "支払条件",
    "calendar_date": "カレンダー日付",
    "day_type": "日種別",
    "work_date": "勤務日",
    "clock_in": "出勤日時",
    "clock_out": "退勤日時",
    "break_minutes": "休憩時間（分）",
    "work_minutes": "実働時間（分）",
    "overtime_minutes": "残業時間（分）",
    "applied_date": "申請日",
    "expense_date": "利用日",
    "invoice_date": "請求日",
    "due_date": "支払期限",
    "receipt_date": "入金日",
    "bill_date": "請求日",
    "payment_date": "支払日",
    "hire_date": "入社日",
    "leave_date": "退社日",
    "account_code": "勘定科目コード",
    "account_name": "勘定科目名",
    "debit": "借方金額",
    "credit": "貸方金額",
    "department_code": "部門コード",
    "parent_code": "親科目コード",
    "default_tax_code": "既定税区分",
    "bank_name": "銀行名",
    "branch_name": "支店名",
    "max_amount_rule": "上限金額",
}

_TABLE_COMMENT_JA: dict[str, str] = {
    "fin_fiscal_year": "会計年度",
    "fin_accounting_period": "会計期間（月次）",
    "fin_journal_entry": "仕訳ヘッダ",
    "fin_journal_line": "仕訳明細",
    "fin_journal_source": "仕訳連携ソース",
    "fin_ar_invoice": "売掛請求書",
    "fin_ar_invoice_line": "売掛請求明細",
    "fin_ar_receipt": "入金",
    "fin_ar_receipt_allocation": "入金消込",
    "fin_ap_bill": "買掛請求",
    "fin_ap_bill_line": "買掛請求明細",
    "fin_ap_payment": "支払",
    "fin_ap_payment_allocation": "支払消込",
    "fin_expense_category": "経費区分",
    "fin_expense_policy_rule": "経費規程",
    "fin_expense_application": "経費申請",
    "fin_expense_line": "経費明細",
    "fin_work_calendar": "勤務カレンダー",
    "fin_shift_pattern": "シフトパターン",
    "fin_employee_shift": "社員シフト",
    "fin_attendance_record": "勤怠記録",
    "fin_leave_type": "休暇区分",
    "fin_leave_request": "休暇申請",
    "fin_pay_item": "支給控除項目",
    "fin_employee_pay_item": "社員別支給控除",
    "fin_social_insurance_profile": "社会保険プロファイル",
    "fin_withholding_tax_table": "源泉徴収税額表",
    "fin_payroll_run": "給与計算",
    "fin_payroll_run_line": "給与明細",
    "fin_employee": "社員",
    "fin_employment_contract": "雇用契約",
    "fin_year_end_adjustment": "年末調整",
    "fin_account": "勘定科目",
    "fin_tax_code": "税区分",
    "fin_partner": "取引先",
    "fin_bank_account": "銀行口座",
    "fin_company_settings": "会社・会計設定",
    "fin_approval_flow": "承認フロー",
    "fin_approval_instance": "承認インスタンス",
    "fin_integration_export_log": "会計連携出力ログ",
    "fin_attachment": "添付ファイル",
}


def _ja_sql_comment(col: dict) -> str:
    """列 COMMENT を日本語に正規化する。"""
    raw = (col.get("comment") or "").strip()
    if raw in _COMMENT_ENUM_JA:
        return _COMMENT_ENUM_JA[raw]
    if raw and "/" not in raw and "." not in raw and not raw.isascii():
        return raw
    if raw:
        # 英語のみの短い列挙はそのまま括弧付きで日本語ラベルを付与
        if "/" in raw or raw.endswith(" 等"):
            return _COMMENT_ENUM_JA.get(raw, f"値（{raw}）")
        if "." in raw:
            return _COMMENT_ENUM_JA.get(raw, raw.replace(".", "の").replace("_", " "))
    name = col["name"]
    if name in _COL_NAME_JA:
        return _COL_NAME_JA[name]
    if name.endswith("_id"):
        base = name[:-3].replace("_", " ")
        return f"{base}ID"
    if name.endswith("_at"):
        return f"{name[:-3].replace('_', ' ')}日時"
    if name.endswith("_date"):
        return f"{name[:-5].replace('_', ' ')}日"
    if name.endswith("_no"):
        return f"{name[:-3].replace('_', ' ')}番号"
    if name.endswith("_json"):
        return f"{name[:-5].replace('_', ' ')}（JSON）"
    if raw:
        return raw
    return name.replace("_", " ")


def _ja_table_comment(table: str, ent: dict, domain: dict) -> str:
    return _TABLE_COMMENT_JA.get(table, ent.get("comment") or domain.get("label", table))


# --------------------------------------------------------------------------- #
# DB 生成
# --------------------------------------------------------------------------- #
def gen_db(m: dict) -> None:
    out = [GEN_SQL,
           "-- =============================================================================",
           "-- FIN（経理・原価・人事）全量スキーマ  (manifest version {})".format(m.get("version")),
           "-- 実行: 02_baseline_full_schema.sql の後。新規DBは bootstrap_full_database.py 推奨。",
           "-- =============================================================================",
           "SET NAMES utf8mb4;",
           ""]

    for domain in m["domains"]:
        out.append(f"-- ------- ドメイン: {domain['id']}（{domain.get('label','')}） -------")
        for ent, parent in iter_entities(domain):
            table = ent["table"]
            cols = entity_columns(ent, parent)
            lines = [f"CREATE TABLE IF NOT EXISTS `{table}` (",
                     "  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',"]
            idx_lines = []
            fk_lines = []
            for c in cols:
                nn = "" if c.get("nullable", True) else " NOT NULL"
                default = ""
                if "default" in c:
                    dv = c["default"]
                    if c["type"] == "bool":
                        default = f" DEFAULT {1 if dv in (True, 'true', 1) else 0}"
                    elif c["type"] in ("int", "bigint", "dec"):
                        default = f" DEFAULT {dv}"
                    else:
                        default = f" DEFAULT '{dv}'"
                ja = _ja_sql_comment(c).replace("'", "''")
                cm = f" COMMENT '{ja}'"
                lines.append(f"  `{c['name']}` {sql_type(c)}{nn}{default}{cm},")
                if c.get("unique"):
                    idx_lines.append(f"  UNIQUE KEY `uq_{table}_{c['name']}` (`{c['name']}`),")
                elif c.get("index") or c.get("fk"):
                    idx_lines.append(f"  KEY `idx_{table}_{c['name']}` (`{c['name']}`),")
                if c.get("fk"):
                    ref_table, ref_col = c["fk"].split(".")
                    od = c.get("on_delete", "SET NULL")
                    fk_lines.append(
                        f"  CONSTRAINT `fk_{table}_{c['name']}` FOREIGN KEY (`{c['name']}`) "
                        f"REFERENCES `{ref_table}` (`{ref_col}`) ON DELETE {od},"
                    )
            lines.append("  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',")
            lines.append("  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',")
            lines.append("  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',")
            lines.append("  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',")
            body = lines + idx_lines + fk_lines
            # 末尾カンマ除去
            body[-1] = body[-1].rstrip(",")
            tbl_comment = _ja_table_comment(table, ent, domain).replace("'", "''")
            body.append(f") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='{tbl_comment}';")
            out.extend(body)
            out.append("")
    out.append(_seed_sql())
    # 既存 migrations は 02..35 を使用済み。04 は cutting と衝突するため次の空き番号 36 を採番。
    _write(ROOT / "backend" / "database" / "migrations" / "36_fin_full_schema.sql", "\n".join(out))


def _seed_sql() -> str:
    accounts = [
        ("100", "現金", "asset"), ("110", "普通預金", "asset"), ("135", "売掛金", "asset"),
        ("140", "棚卸資産", "asset"), ("145", "仕掛品", "asset"), ("146", "製品", "asset"),
        ("170", "建物附属設備", "asset"), ("175", "機械装置", "asset"),
        ("180", "減価償却累計額", "asset"),
        ("305", "買掛金", "liability"), ("310", "未払金", "liability"),
        ("315", "未払費用", "liability"), ("320", "預り金", "liability"),
        ("500", "資本金", "equity"),
        ("600", "売上高", "revenue"),
        ("700", "仕入高", "expense"), ("705", "外注加工費", "expense"),
        ("710", "給与手当", "expense"), ("715", "法定福利費", "expense"),
        ("720", "減価償却費", "expense"), ("730", "旅費交通費", "expense"),
        ("735", "通信費", "expense"), ("740", "消耗品費", "expense"),
        ("745", "会議費", "expense"), ("750", "棚卸差額", "expense"),
    ]
    tax = [
        ("TAX10", "課税仕入10%", "10.000", "taxable"),
        ("TAX8", "軽減税率8%", "8.000", "taxable"),
        ("OUT10", "課税売上10%", "10.000", "taxable"),
        ("EXEMPT", "非課税", "0.000", "exempt"),
        ("NONTAX", "不課税", "0.000", "non_taxable"),
    ]
    pay_items = [
        ("BASE", "基本給", "earning", 1, "710"),
        ("OVERTIME", "時間外手当", "earning", 1, "710"),
        ("COMMUTE", "通勤手当", "earning", 0, "730"),
        ("HEALTH", "健康保険", "deduction", 0, "320"),
        ("PENSION", "厚生年金", "deduction", 0, "320"),
        ("EMPLOY", "雇用保険", "deduction", 0, "320"),
        ("INCOMETAX", "所得税", "deduction", 0, "320"),
        ("RESIDENT", "住民税", "deduction", 0, "320"),
    ]
    s = ["-- ------- 初期データ -------"]
    s.append("INSERT IGNORE INTO `fin_account` (`code`,`name`,`account_type`,`is_active`,`sort_order`) VALUES")
    s.append(",\n".join(
        f"('{c}','{n}','{t}',1,{i})" for i, (c, n, t) in enumerate(accounts)) + ";")
    s.append("INSERT IGNORE INTO `fin_tax_code` (`code`,`name`,`rate`,`kind`,`is_active`) VALUES")
    s.append(",\n".join(
        f"('{c}','{n}',{r},'{k}',1)" for (c, n, r, k) in tax) + ";")
    s.append("INSERT IGNORE INTO `fin_pay_item` (`code`,`name`,`item_type`,`is_taxable`,`account_code`,`is_active`) VALUES")
    s.append(",\n".join(
        f"('{c}','{n}','{t}',{tax_},'{acc}',1)" for (c, n, t, tax_, acc) in pay_items) + ";")
    s.append("INSERT IGNORE INTO `fin_company_settings` (`id`,`company_name`,`fiscal_start_month`,`tax_method`,`base_currency`) "
             "VALUES (1,'Smart-EMAPs 株式会社',4,'invoice','JPY');")
    return "\n".join(s)


# --------------------------------------------------------------------------- #
# backend 生成
# --------------------------------------------------------------------------- #
def gen_backend(m: dict) -> None:
    base = ROOT / "backend" / "app" / "modules" / "fin"
    domain_ids = [d["id"] for d in m["domains"]]

    for domain in m["domains"]:
        d = domain["id"]
        ddir = base / d
        _write(ddir / "__init__.py", GEN_PY)
        _write(ddir / "models.py", _backend_models(domain))
        _write(ddir / "schemas.py", _backend_schemas(domain))
        _write(ddir / "api.py", _backend_api(domain))

    # fin/__init__.py 集約
    inc = []
    imports = []
    for d in domain_ids:
        imports.append(f"from app.modules.fin.{d}.api import router as {d}_router")
        inc.append(f'router.include_router({d}_router, prefix="/{d.replace("_","-")}")')
    init = (GEN_PY
            + '"""FIN（経理・原価・人事）モジュール集約ルーター。"""\n'
            + "from fastapi import APIRouter\n"
            + "\n".join(imports) + "\n\n"
            + "router = APIRouter()\n"
            + "\n".join(inc) + "\n\n"
            + "__all__ = ['router']\n")
    _write(base / "__init__.py", init)

    # common/crud.py（汎用 CRUD・手書き相当の安定ヘルパ。再生成で上書きされても良い内容）
    _write(base / "common" / "__init__.py", GEN_PY)
    _write(base / "common" / "crud.py", _backend_crud_helper())


def _backend_models(domain: dict) -> str:
    out = [GEN_PY,
           f'"""{domain.get("label","")}（{domain["id"]}）SQLAlchemy モデル。"""',
           "from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,",
           "                        Boolean, ForeignKey)",
           "from sqlalchemy.types import Numeric",
           "from sqlalchemy.sql import func",
           "",
           "from app.core.database import Base",
           "",
           ""]
    for ent, parent in iter_entities(domain):
        out.append(f"class {ent['name']}(Base):")
        out.append(f'    __tablename__ = "{ent["table"]}"')
        out.append("")
        out.append("    id = Column(BigInteger, primary_key=True, autoincrement=True)")
        for c in entity_columns(ent, parent):
            args = [sa_type(c)]
            if c.get("fk"):
                ref = c["fk"]
                od = c.get("on_delete", "SET NULL")
                args.append(f'ForeignKey("{ref}", ondelete="{od}")')
            if not c.get("nullable", True):
                args.append("nullable=False")
            if c.get("index") or c.get("unique"):
                args.append("index=True")
            if c.get("unique"):
                args.append("unique=True")
            if "default" in c:
                dv = c["default"]
                if c["type"] == "bool":
                    args.append(f"default={'True' if dv in (True,'true',1) else 'False'}")
                elif c["type"] in ("int", "bigint", "dec"):
                    args.append(f"default={dv}")
                else:
                    args.append(f'default="{dv}"')
            out.append(f"    {c['name']} = Column({', '.join(args)})")
        out.append("    created_by = Column(String(100))")
        out.append("    updated_by = Column(String(100))")
        out.append("    created_at = Column(DateTime, server_default=func.now())")
        out.append("    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())")
        out.append("")
        out.append("")
    return "\n".join(out)


def _backend_schemas(domain: dict) -> str:
    out = [GEN_PY,
           f'"""{domain.get("label","")}（{domain["id"]}）Pydantic スキーマ。"""',
           "from __future__ import annotations",
           "from datetime import date, datetime",
           "from typing import List, Optional",
           "from pydantic import BaseModel, ConfigDict",
           "",
           ""]
    for ent, parent in iter_entities(domain):
        name = ent["name"]
        cols = editable_columns(ent, parent)
        # Create
        out.append(f"class {name}Create(BaseModel):")
        if not cols:
            out.append("    pass")
        for c in cols:
            out.append(f"    {c['name']}: Optional[{py_type(c)}] = None")
        out.append("")
        out.append("")
        # Update（Create と同形）
        out.append(f"class {name}Update({name}Create):")
        out.append("    pass")
        out.append("")
        out.append("")
        # Out
        out.append(f"class {name}Out({name}Create):")
        out.append("    model_config = ConfigDict(from_attributes=True)")
        out.append("    id: int")
        out.append("    created_by: Optional[str] = None")
        out.append("    updated_by: Optional[str] = None")
        out.append("    created_at: Optional[datetime] = None")
        out.append("    updated_at: Optional[datetime] = None")
        out.append("")
        out.append("")
        # Paginated
        out.append(f"class {name}Page(BaseModel):")
        out.append(f"    items: List[{name}Out]")
        out.append("    total: int")
        out.append("    page: int")
        out.append("    page_size: int")
        out.append("    pages: int")
        out.append("")
        out.append("")
    return "\n".join(out)


def _backend_api(domain: dict) -> str:
    names = [ent["name"] for ent, _ in iter_entities(domain)]
    out = [GEN_PY,
           f'"""{domain.get("label","")}（{domain["id"]}）汎用 CRUD API。"""',
           "from fastapi import APIRouter",
           "",
           f"from app.modules.fin.{domain['id']} import models as md",
           f"from app.modules.fin.{domain['id']} import schemas as sc",
           "from app.modules.fin.common.crud import build_crud_router",
           "",
           "router = APIRouter()",
           ""]
    for ent, parent in iter_entities(domain):
        name = ent["name"]
        slug = resource_slug(ent["table"])
        search = _search_fields(ent, parent)
        order_by = ent.get("order_by", "id desc")
        out.append(
            f"router.include_router(build_crud_router("
            f"model=md.{name}, out_schema=sc.{name}Out, create_schema=sc.{name}Create, "
            f"update_schema=sc.{name}Update, resource='{slug}', "
            f"search_fields={search!r}, order_by={order_by!r}, label='{ent.get('comment', name)}'))"
        )
    out.append("")
    out.append(f"__all__ = ['router']  # entities: {', '.join(names)}")
    out.append("")
    return "\n".join(out)


def _search_fields(ent: dict, parent: dict | None):
    fields = []
    for c in entity_columns(ent, parent):
        if c["type"] in ("str", "text") and (
            "name" in c["name"] or "no" in c["name"] or c["name"] in ("description", "title")
        ):
            fields.append(c["name"])
    return fields[:3]


def _backend_crud_helper() -> str:
    return GEN_PY + '''"""FIN 汎用 CRUD ルータービルダー。

manifest 由来の各エンティティに対し、一覧（ページング・等値フィルタ・キーワード検索）、
取得、作成、更新、削除の標準 REST を提供する。中核業務ロジックは各 services/ に実装する。
"""
from typing import List, Optional, Type

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from sqlalchemy import select, func, delete as sa_delete
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.modules.auth.api import verify_token_and_get_user
from app.modules.auth.models import User

RESERVED = {"page", "page_size", "q", "order_by"}


def _coerce(value: str):
    if value in ("true", "false"):
        return value == "true"
    if value.lstrip("-").isdigit():
        return int(value)
    return value


def _apply_order(stmt, model, order_by: Optional[str]):
    if not order_by:
        return stmt.order_by(model.id.desc())
    parts = order_by.split()
    col = getattr(model, parts[0], None)
    if col is None:
        return stmt.order_by(model.id.desc())
    if len(parts) > 1 and parts[1].lower() == "desc":
        return stmt.order_by(col.desc())
    return stmt.order_by(col.asc())


def build_crud_router(
    *,
    model: Type,
    out_schema: Type,
    create_schema: Type,
    update_schema: Type,
    resource: str,
    search_fields: Optional[List[str]] = None,
    order_by: Optional[str] = None,
    label: str = "",
) -> APIRouter:
    router = APIRouter()
    search_fields = search_fields or []

    @router.get(f"/{resource}", summary=f"{label} 一覧")
    async def list_items(
        request: Request,
        page: int = Query(1, ge=1),
        page_size: int = Query(20, ge=1, le=500),
        q: Optional[str] = None,
        order: Optional[str] = Query(None, alias="order_by"),
        db: AsyncSession = Depends(get_db),
        _user: User = Depends(verify_token_and_get_user),
    ):
        stmt = select(model)
        for key, val in request.query_params.items():
            if key in RESERVED:
                continue
            col = getattr(model, key, None)
            if col is not None:
                stmt = stmt.where(col == _coerce(val))
        if q and search_fields:
            from sqlalchemy import or_
            conds = [getattr(model, f).like(f"%{q}%") for f in search_fields]
            stmt = stmt.where(or_(*conds))
        total = (await db.execute(select(func.count()).select_from(stmt.subquery()))).scalar() or 0
        stmt = _apply_order(stmt, model, order or order_by)
        stmt = stmt.offset((page - 1) * page_size).limit(page_size)
        rows = (await db.execute(stmt)).scalars().all()
        return {
            "items": [out_schema.model_validate(r) for r in rows],
            "total": total,
            "page": page,
            "page_size": page_size,
            "pages": (total + page_size - 1) // page_size,
        }

    @router.get(f"/{resource}/{{item_id}}", summary=f"{label} 取得")
    async def get_item(
        item_id: int,
        db: AsyncSession = Depends(get_db),
        _user: User = Depends(verify_token_and_get_user),
    ):
        obj = await db.get(model, item_id)
        if obj is None:
            raise HTTPException(status_code=404, detail=f"{label} が見つかりません")
        return out_schema.model_validate(obj)

    @router.post(f"/{resource}", summary=f"{label} 作成")
    async def create_item(
        payload: create_schema,  # type: ignore
        db: AsyncSession = Depends(get_db),
        user: User = Depends(verify_token_and_get_user),
    ):
        data = payload.model_dump(exclude_unset=True)
        obj = model(**data)
        if hasattr(obj, "created_by"):
            obj.created_by = user.username
            obj.updated_by = user.username
        db.add(obj)
        await db.commit()
        await db.refresh(obj)
        return out_schema.model_validate(obj)

    @router.put(f"/{resource}/{{item_id}}", summary=f"{label} 更新")
    async def update_item(
        item_id: int,
        payload: update_schema,  # type: ignore
        db: AsyncSession = Depends(get_db),
        user: User = Depends(verify_token_and_get_user),
    ):
        obj = await db.get(model, item_id)
        if obj is None:
            raise HTTPException(status_code=404, detail=f"{label} が見つかりません")
        for key, val in payload.model_dump(exclude_unset=True).items():
            setattr(obj, key, val)
        if hasattr(obj, "updated_by"):
            obj.updated_by = user.username
        await db.commit()
        await db.refresh(obj)
        return out_schema.model_validate(obj)

    @router.delete(f"/{resource}/{{item_id}}", summary=f"{label} 削除")
    async def delete_item(
        item_id: int,
        db: AsyncSession = Depends(get_db),
        _user: User = Depends(verify_token_and_get_user),
    ):
        obj = await db.get(model, item_id)
        if obj is None:
            raise HTTPException(status_code=404, detail=f"{label} が見つかりません")
        await db.execute(sa_delete(model).where(model.id == item_id))
        await db.commit()
        return {"message": "削除しました", "id": item_id}

    return router
'''


# --------------------------------------------------------------------------- #
# frontend 画面生成
# --------------------------------------------------------------------------- #
def _menu_leaves(m: dict):
    """path を持つ leaf を (leaf, parent_chain) で列挙。"""
    result = []

    def walk(nodes, chain):
        for n in nodes:
            if n.get("path") and n.get("view"):
                result.append((n, chain))
            if n.get("children"):
                walk(n["children"], chain + [n])
    walk(m["menus"], [])
    return result


def _entity_lookup(m: dict):
    lut = {}
    for domain in m["domains"]:
        for ent, parent in iter_entities(domain):
            lut[(domain["id"], ent["name"])] = (ent, parent, domain)
    return lut


def gen_frontend(m: dict) -> None:
    base = ROOT / "frontend" / "src" / "views" / "fin"
    lut = _entity_lookup(m)
    # home カード用: menu code -> 子leaf
    code_children = {}

    def index(nodes):
        for n in nodes:
            if n.get("children"):
                code_children[n["code"]] = n["children"]
                index(n["children"])
    index(m["menus"])

    for leaf, chain in _menu_leaves(m):
        view = leaf["view"]
        folder = leaf.get("domain") or "home"
        cname = comp_name(leaf["code"])
        path = base / folder / f"{cname}.vue"
        if view == "home":
            content = _vue_home(leaf, code_children, m)
        elif view in ("list", "form"):
            content = _vue_crud(leaf, lut, view)
        elif view == "report":
            content = _vue_report(leaf, lut)
        elif view == "workflow":
            content = _vue_workflow(leaf, lut)
        elif view == "batch":
            content = _vue_batch(leaf, lut)
        else:
            continue
        _write(path, content)


_LABEL_MAP = {
    "status": "ステータス", "code": "コード", "name": "名称", "remarks": "備考",
    "description": "摘要", "amount": "金額", "is_active": "有効",
    "created_at": "作成日時", "updated_at": "更新日時",
}


def _label(col: dict) -> str:
    """技術的な enum コメント（'a/b/c'）や FK 参照（'x.id'）はラベルに使わず、
    既知名マップ or カラム名を人間可読化する。"""
    name = col["name"]
    if name in _LABEL_MAP:
        return _LABEL_MAP[name]
    comment = col.get("comment", "")
    if comment and "/" not in comment and "." not in comment:
        return comment
    if name.endswith("_id"):
        base = name[:-3]
        return _LABEL_MAP.get(base, base.replace("_", " "))
    return name.replace("_", " ")


def _columns_for(ent: dict, parent: dict | None, limit: int = 8):
    cols = []
    for c in entity_columns(ent, parent):
        cols.append({"prop": c["name"], "label": _label(c)})
    return cols[:limit]


def _fields_for(ent: dict, parent: dict | None):
    fields = []
    for c in entity_columns(ent, parent):
        fields.append({
            "prop": c["name"],
            "label": _label(c),
            "type": ts_field_type(c),
            "required": not c.get("nullable", True),
        })
    return fields


def _api_base(leaf: dict) -> str:
    slug = leaf["path"].rstrip("/").split("/")[-1]
    return f"/api/fin/{leaf['domain']}/{slug}"


def _resource_api_base(leaf: dict, ent: dict) -> str:
    return f"/api/fin/{leaf['domain']}/{resource_slug(ent['table'])}"


def _vue_crud(leaf: dict, lut, view: str) -> str:
    ent, parent, domain = lut[(leaf["domain"], leaf["entity"])]
    columns = _columns_for(ent, parent)
    fields = _fields_for(ent, parent)
    api_base = _resource_api_base(leaf, ent)
    comp = "FinFormPage" if view == "form" else "FinCrudPage"
    return ("<!-- @generated by scripts/fin/fin_codegen.py -->\n"
            + "<template>\n"
            + f"  <{comp} :title=\"title\" :api-base=\"apiBase\" :columns=\"columns\" :fields=\"fields\" />\n"
            + "</template>\n\n"
            + "<script setup lang=\"ts\">\n"
            + f"import {comp} from '@/views/fin/components/{comp}.vue'\n"
            + "import type { FinColumn, FinField } from '@/views/fin/components/types'\n\n"
            + f"const title = '{leaf['name']}'\n"
            + f"const apiBase = '{api_base}'\n"
            + f"const columns: FinColumn[] = {json.dumps(columns, ensure_ascii=False)}\n"
            + f"const fields: FinField[] = {json.dumps(fields, ensure_ascii=False)}\n"
            + "</script>\n")


def _vue_report(leaf: dict, lut) -> str:
    ent, parent, domain = lut[(leaf["domain"], leaf["entity"])]
    columns = _columns_for(ent, parent, limit=10)
    api_base = _resource_api_base(leaf, ent)
    return ("<!-- @generated by scripts/fin/fin_codegen.py -->\n"
            + "<template>\n"
            + "  <FinReportPage :title=\"title\" :api-base=\"apiBase\" :columns=\"columns\" />\n"
            + "</template>\n\n"
            + "<script setup lang=\"ts\">\n"
            + "import FinReportPage from '@/views/fin/components/FinReportPage.vue'\n"
            + "import type { FinColumn } from '@/views/fin/components/types'\n\n"
            + f"const title = '{leaf['name']}'\n"
            + f"const apiBase = '{api_base}'\n"
            + f"const columns: FinColumn[] = {json.dumps(columns, ensure_ascii=False)}\n"
            + "</script>\n")


def _vue_workflow(leaf: dict, lut) -> str:
    ent, parent, domain = lut[(leaf["domain"], leaf["entity"])]
    columns = _columns_for(ent, parent)
    api_base = _resource_api_base(leaf, ent)
    return ("<!-- @generated by scripts/fin/fin_codegen.py -->\n"
            + "<template>\n"
            + "  <FinWorkflowPage :title=\"title\" :api-base=\"apiBase\" :columns=\"columns\" />\n"
            + "</template>\n\n"
            + "<script setup lang=\"ts\">\n"
            + "import FinWorkflowPage from '@/views/fin/components/FinWorkflowPage.vue'\n"
            + "import type { FinColumn } from '@/views/fin/components/types'\n\n"
            + f"const title = '{leaf['name']}'\n"
            + f"const apiBase = '{api_base}'\n"
            + f"const columns: FinColumn[] = {json.dumps(columns, ensure_ascii=False)}\n"
            + "</script>\n")


def _vue_batch(leaf: dict, lut) -> str:
    ent, parent, domain = lut[(leaf["domain"], leaf["entity"])]
    columns = _columns_for(ent, parent)
    api_base = _resource_api_base(leaf, ent)
    return ("<!-- @generated by scripts/fin/fin_codegen.py -->\n"
            + "<template>\n"
            + "  <FinBatchPage :title=\"title\" :api-base=\"apiBase\" :columns=\"columns\" />\n"
            + "</template>\n\n"
            + "<script setup lang=\"ts\">\n"
            + "import FinBatchPage from '@/views/fin/components/FinBatchPage.vue'\n"
            + "import type { FinColumn } from '@/views/fin/components/types'\n\n"
            + f"const title = '{leaf['name']}'\n"
            + f"const apiBase = '{api_base}'\n"
            + f"const columns: FinColumn[] = {json.dumps(columns, ensure_ascii=False)}\n"
            + "</script>\n")


def _menu_desc(node: dict) -> str:
    """ホームカード説明文（日本語優先）。"""
    return node.get("desc") or node["name"]


def _vue_home(leaf: dict, code_children: dict, m: dict) -> str:
    home_kind = leaf.get("home")
    # root home: 全 FIN トップ子ドメインをカード化。サブ home: 兄弟 leaf をカード化。
    cards = []
    if home_kind == "fin_root":
        top = code_children.get("FIN", [])
        for n in top:
            if n["code"] in ("FIN_HOME",):
                continue
            first = _first_path(n)
            cards.append({"title": n["name"], "desc": _menu_desc(n),
                          "path": first, "icon": n.get("icon", "Menu")})
    elif home_kind == "self_service":
        cards = [
            {"title": "経費申請", "desc": "経費精算の申請・照会", "path": "/fin/expense/applications", "icon": "EditPen"},
            {"title": "休暇申請", "desc": "休暇の申請・承認状況", "path": "/fin/attendance/leave", "icon": "Calendar"},
            {"title": "給与明細", "desc": "給与明細の参照", "path": "/fin/payroll/slips", "icon": "Document"},
            {"title": "勤怠記録", "desc": "出退勤の記録", "path": "/fin/attendance/clock", "icon": "Timer"},
        ]
    else:
        # leaf の親 code を探し、その子（自分以外）
        parent_code = _parent_code(m["menus"], leaf["code"])
        for n in code_children.get(parent_code, []):
            if n["code"] == leaf["code"] or not n.get("path"):
                continue
            cards.append({"title": n["name"], "desc": _menu_desc(n),
                          "path": n["path"], "icon": n.get("icon", "Menu")})
    subtitle = leaf.get("subtitle") or leaf["name"]
    return ("<!-- @generated by scripts/fin/fin_codegen.py -->\n"
            + "<template>\n"
            + "  <FinHomePage :title=\"title\" :subtitle=\"subtitle\" :cards=\"cards\" />\n"
            + "</template>\n\n"
            + "<script setup lang=\"ts\">\n"
            + "import FinHomePage from '@/views/fin/components/FinHomePage.vue'\n"
            + "import type { FinHomeCard } from '@/views/fin/components/types'\n\n"
            + f"const title = '{leaf['name']}'\n"
            + f"const subtitle = '{subtitle}'\n"
            + f"const cards: FinHomeCard[] = {json.dumps(cards, ensure_ascii=False)}\n"
            + "</script>\n")


def _first_path(node: dict):
    if node.get("path"):
        return node["path"]
    for c in node.get("children", []):
        p = _first_path(c)
        if p:
            return p
    return "/fin"


def _parent_code(nodes, target, parent=None):
    for n in nodes:
        if n["code"] == target:
            return parent
        if n.get("children"):
            r = _parent_code(n["children"], target, n["code"])
            if r:
                return r
    return None


# --------------------------------------------------------------------------- #
# menu / router / locales 生成
# --------------------------------------------------------------------------- #
def gen_menu(m: dict) -> None:
    rows = []
    root_sort = m.get("menu_sort_order", 1.5)

    def emit(node, parent_code, sort):
        item = {"code": node["code"], "name": node["name"]}
        if parent_code:
            item["parentCode"] = parent_code
        if node.get("path"):
            item["path"] = node["path"]
        if node.get("icon"):
            item["icon"] = node["icon"]
        item["sortOrder"] = sort
        rows.append(item)
        for i, child in enumerate(node.get("children", [])):
            emit(child, node["code"], i)

    for top in m["menus"]:
        item = {"code": top["code"], "name": top["name"], "icon": top.get("icon", "Money"),
                "sortOrder": root_sort}
        rows.append(item)
        for i, child in enumerate(top.get("children", [])):
            emit(child, top["code"], i)

    body = ",\n".join("  " + _ts_obj(r) for r in rows)
    content = (GEN_TS
               + "import type { MenuConfigItem } from './menuConfig'\n\n"
               + "/** FIN（経理・原価・人事）メニュー定義。menuConfig.ts から spread される。 */\n"
               + "export const finMenuConfig: MenuConfigItem[] = [\n"
               + body + ",\n]\n")
    _write(ROOT / "frontend" / "src" / "router" / "finMenuConfig.ts", content)


def _ts_obj(d: dict) -> str:
    parts = []
    for k, v in d.items():
        if isinstance(v, str):
            parts.append(f"{k}: '{v}'")
        else:
            parts.append(f"{k}: {v}")
    return "{ " + ", ".join(parts) + " }"


def gen_router(m: dict) -> None:
    lines = []
    for leaf, chain in _menu_leaves(m):
        cname = comp_name(leaf["code"])
        folder = leaf.get("domain") or "home"
        route_path = leaf["path"].lstrip("/")
        lines.append(
            f"  {{ path: '{route_path}', name: '{cname}', "
            f"component: () => import('@/views/fin/{folder}/{cname}.vue'), "
            f"meta: {{ title: '{leaf['name']}', group: 'FIN', requiresAuth: true }} }},"
        )
    # redirects
    for r in m.get("redirects", []):
        lines.append(f"  {{ path: '{r['from'].lstrip('/')}', redirect: '{r['to']}' }},")
    content = (GEN_TS
               + "import type { RouteRecordRaw } from 'vue-router'\n\n"
               + "/** FIN（経理・原価・人事）ルート定義。shared/router/index.ts の MainLayout children に spread される。 */\n"
               + "export const finRoutes: RouteRecordRaw[] = [\n"
               + "\n".join(lines) + "\n]\n")
    _write(ROOT / "frontend" / "src" / "shared" / "router" / "finRoutes.ts", content)


def gen_locales(m: dict) -> None:
    # menu.<CODE> を各言語で
    langs = {"ja": "name", "zh": "name_zh", "en": "name_en", "vi": "name_en"}
    collected = []

    def walk(nodes):
        for n in nodes:
            collected.append(n)
            if n.get("children"):
                walk(n["children"])
    walk(m["menus"])

    locdir = ROOT / "frontend" / "src" / "locales" / "fin"
    for lang, key in langs.items():
        menu_lines = []
        for n in collected:
            label = n.get(key) or n.get("name")
            menu_lines.append(f"    {n['code']}: '{label}',")
        content = (GEN_TS
                   + f"/** FIN locale fragment ({lang})。i18n.ts でベース messages にマージされる。 */\n"
                   + "export default {\n"
                   + "  menu: {\n"
                   + "\n".join(menu_lines) + "\n"
                   + "  },\n"
                   + "  fin: {\n"
                   + "    moduleName: '" + ("経理・原価・人事" if lang == "ja" else "财务·成本·人事" if lang == "zh" else "Finance, Costing & HR") + "',\n"
                   + "  },\n"
                   + "}\n")
        _write(locdir / f"{lang}.ts", content)

    # index.ts
    idx = (GEN_TS
           + "import ja from './ja'\nimport zh from './zh'\nimport en from './en'\nimport vi from './vi'\n\n"
           + "export const finLocales = { ja, zh, en, vi }\n")
    _write(locdir / "index.ts", idx)


# --------------------------------------------------------------------------- #
# IO
# --------------------------------------------------------------------------- #
def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


def main():
    ap = argparse.ArgumentParser(description="FIN code generator")
    ap.add_argument("--target", default="all",
                    help="all|db|backend|frontend|menu|router|locales（カンマ区切り可）")
    args = ap.parse_args()
    m = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))

    targets = args.target.split(",")
    if "all" in targets:
        targets = ["db", "backend", "frontend", "menu", "router", "locales"]

    dispatch = {
        "db": gen_db,
        "backend": gen_backend,
        "frontend": gen_frontend,
        "menu": gen_menu,
        "router": gen_router,
        "locales": gen_locales,
    }
    for t in targets:
        t = t.strip()
        if t not in dispatch:
            raise SystemExit(f"unknown target: {t}")
        print(f"[fin_codegen] target={t}")
        dispatch[t](m)
    print("[fin_codegen] done.")


if __name__ == "__main__":
    main()
