<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '承認フロー'
const apiBase = '/api/fin/settings/approval-flow'
const columns: FinColumn[] = [{"prop": "code", "label": "コード"}, {"prop": "name", "label": "名称"}, {"prop": "target_type", "label": "target type"}, {"prop": "steps_json", "label": "承認ステップ定義"}, {"prop": "is_active", "label": "有効"}]
const fields: FinField[] = [{"prop": "code", "label": "コード", "type": "text", "required": true}, {"prop": "name", "label": "名称", "type": "text", "required": true}, {"prop": "target_type", "label": "target type", "type": "text", "required": false}, {"prop": "steps_json", "label": "承認ステップ定義", "type": "text", "required": false}, {"prop": "is_active", "label": "有効", "type": "switch", "required": false}]
</script>
