<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinFormPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinFormPage from '@/views/fin/components/FinFormPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '会計設定'
const apiBase = '/api/fin/settings/company-settings'
const columns: FinColumn[] = [{"prop": "company_name", "label": "会社名"}, {"prop": "fiscal_start_month", "label": "期首月"}, {"prop": "tax_method", "label": "tax method"}, {"prop": "rounding", "label": "rounding"}, {"prop": "base_currency", "label": "base currency"}]
const fields: FinField[] = [{"prop": "company_name", "label": "会社名", "type": "text", "required": false}, {"prop": "fiscal_start_month", "label": "期首月", "type": "number", "required": false}, {"prop": "tax_method", "label": "tax method", "type": "text", "required": false}, {"prop": "rounding", "label": "rounding", "type": "text", "required": false}, {"prop": "base_currency", "label": "base currency", "type": "text", "required": false}]
</script>
