# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""人事（hr）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.hr import models as md
from app.modules.fin.hr import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.Employee, out_schema=sc.EmployeeOut, create_schema=sc.EmployeeCreate, update_schema=sc.EmployeeUpdate, resource='employee', search_fields=['employee_no', 'name', 'name_kana'], order_by='employee_no', label='Employee'))
router.include_router(build_crud_router(model=md.EmploymentContract, out_schema=sc.EmploymentContractOut, create_schema=sc.EmploymentContractCreate, update_schema=sc.EmploymentContractUpdate, resource='employment-contract', search_fields=[], order_by='start_date desc', label='EmploymentContract'))
router.include_router(build_crud_router(model=md.YearEndAdjustment, out_schema=sc.YearEndAdjustmentOut, create_schema=sc.YearEndAdjustmentCreate, update_schema=sc.YearEndAdjustmentUpdate, resource='year-end-adjustment', search_fields=[], order_by='target_year desc', label='YearEndAdjustment'))

__all__ = ['router']  # entities: Employee, EmploymentContract, YearEndAdjustment
