# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""人事（hr）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class Employee(Base):
    __tablename__ = "fin_employee"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_no = Column(String(30), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    name_kana = Column(String(100))
    user_id = Column(Integer)
    department_code = Column(String(50))
    email = Column(String(200))
    hire_date = Column(Date)
    leave_date = Column(Date)
    employment_type = Column(String(20), default="regular")
    status = Column(String(20), index=True, default="active")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class EmploymentContract(Base):
    __tablename__ = "fin_employment_contract"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True)
    contract_type = Column(String(30))
    start_date = Column(Date, nullable=False)
    end_date = Column(Date)
    base_salary = Column(Numeric(18, 2), default=0)
    remarks = Column(String(255))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class YearEndAdjustment(Base):
    __tablename__ = "fin_year_end_adjustment"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True)
    target_year = Column(Integer, nullable=False, index=True)
    total_income = Column(Numeric(18, 2), default=0)
    deduction_total = Column(Numeric(18, 2), default=0)
    tax_settled = Column(Numeric(18, 2), default=0)
    refund_amount = Column(Numeric(18, 2), default=0)
    status = Column(String(20), default="draft")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

