# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""人事（hr）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class EmployeeCreate(BaseModel):
    employee_no: Optional[str] = None
    name: Optional[str] = None
    name_kana: Optional[str] = None
    user_id: Optional[int] = None
    department_code: Optional[str] = None
    email: Optional[str] = None
    hire_date: Optional[date] = None
    leave_date: Optional[date] = None
    employment_type: Optional[str] = None
    status: Optional[str] = None


class EmployeeUpdate(EmployeeCreate):
    pass


class EmployeeOut(EmployeeCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class EmployeePage(BaseModel):
    items: List[EmployeeOut]
    total: int
    page: int
    page_size: int
    pages: int


class EmploymentContractCreate(BaseModel):
    employee_id: Optional[int] = None
    contract_type: Optional[str] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    base_salary: Optional[float] = None
    remarks: Optional[str] = None


class EmploymentContractUpdate(EmploymentContractCreate):
    pass


class EmploymentContractOut(EmploymentContractCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class EmploymentContractPage(BaseModel):
    items: List[EmploymentContractOut]
    total: int
    page: int
    page_size: int
    pages: int


class YearEndAdjustmentCreate(BaseModel):
    employee_id: Optional[int] = None
    target_year: Optional[int] = None
    total_income: Optional[float] = None
    deduction_total: Optional[float] = None
    tax_settled: Optional[float] = None
    refund_amount: Optional[float] = None
    status: Optional[str] = None


class YearEndAdjustmentUpdate(YearEndAdjustmentCreate):
    pass


class YearEndAdjustmentOut(YearEndAdjustmentCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class YearEndAdjustmentPage(BaseModel):
    items: List[YearEndAdjustmentOut]
    total: int
    page: int
    page_size: int
    pages: int

