# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""経理マスタ（master）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.master import models as md
from app.modules.fin.master import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.Account, out_schema=sc.AccountOut, create_schema=sc.AccountCreate, update_schema=sc.AccountUpdate, resource='account', search_fields=['name'], order_by='code', label='Account'))
router.include_router(build_crud_router(model=md.TaxCode, out_schema=sc.TaxCodeOut, create_schema=sc.TaxCodeCreate, update_schema=sc.TaxCodeUpdate, resource='tax-code', search_fields=['name'], order_by='code', label='TaxCode'))
router.include_router(build_crud_router(model=md.Partner, out_schema=sc.PartnerOut, create_schema=sc.PartnerCreate, update_schema=sc.PartnerUpdate, resource='partner', search_fields=['name'], order_by='code', label='Partner'))
router.include_router(build_crud_router(model=md.BankAccount, out_schema=sc.BankAccountOut, create_schema=sc.BankAccountCreate, update_schema=sc.BankAccountUpdate, resource='bank-account', search_fields=['bank_name', 'branch_name'], order_by='id desc', label='BankAccount'))

__all__ = ['router']  # entities: Account, TaxCode, Partner, BankAccount
