# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""経理マスタ（master）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class Account(Base):
    __tablename__ = "fin_account"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(50), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    account_type = Column(String(20), nullable=False, index=True)
    parent_code = Column(String(50))
    default_tax_code = Column(String(20))
    is_active = Column(Boolean, default=True)
    sort_order = Column(Integer, default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class TaxCode(Base):
    __tablename__ = "fin_tax_code"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(20), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    rate = Column(Numeric(6, 3), default=0)
    kind = Column(String(20), default="taxable")
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class Partner(Base):
    __tablename__ = "fin_partner"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(50), nullable=False, index=True, unique=True)
    name = Column(String(200), nullable=False)
    partner_type = Column(String(20), index=True, default="customer")
    customer_id = Column(Integer)
    supplier_id = Column(Integer)
    closing_day = Column(Integer)
    payment_terms = Column(String(100))
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class BankAccount(Base):
    __tablename__ = "fin_bank_account"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(30), nullable=False, index=True, unique=True)
    bank_name = Column(String(100))
    branch_name = Column(String(100))
    account_type = Column(String(20), default="ordinary")
    account_number = Column(String(30))
    account_holder = Column(String(100))
    gl_account_code = Column(String(50))
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

