# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""経理マスタ（master）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class AccountCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    account_type: Optional[str] = None
    parent_code: Optional[str] = None
    default_tax_code: Optional[str] = None
    is_active: Optional[bool] = None
    sort_order: Optional[int] = None


class AccountUpdate(AccountCreate):
    pass


class AccountOut(AccountCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class AccountPage(BaseModel):
    items: List[AccountOut]
    total: int
    page: int
    page_size: int
    pages: int


class TaxCodeCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    rate: Optional[float] = None
    kind: Optional[str] = None
    is_active: Optional[bool] = None


class TaxCodeUpdate(TaxCodeCreate):
    pass


class TaxCodeOut(TaxCodeCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class TaxCodePage(BaseModel):
    items: List[TaxCodeOut]
    total: int
    page: int
    page_size: int
    pages: int


class PartnerCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    partner_type: Optional[str] = None
    customer_id: Optional[int] = None
    supplier_id: Optional[int] = None
    closing_day: Optional[int] = None
    payment_terms: Optional[str] = None
    is_active: Optional[bool] = None


class PartnerUpdate(PartnerCreate):
    pass


class PartnerOut(PartnerCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class PartnerPage(BaseModel):
    items: List[PartnerOut]
    total: int
    page: int
    page_size: int
    pages: int


class BankAccountCreate(BaseModel):
    code: Optional[str] = None
    bank_name: Optional[str] = None
    branch_name: Optional[str] = None
    account_type: Optional[str] = None
    account_number: Optional[str] = None
    account_holder: Optional[str] = None
    gl_account_code: Optional[str] = None
    is_active: Optional[bool] = None


class BankAccountUpdate(BankAccountCreate):
    pass


class BankAccountOut(BankAccountCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class BankAccountPage(BaseModel):
    items: List[BankAccountOut]
    total: int
    page: int
    page_size: int
    pages: int

