# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""売上・請求（receivables）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.receivables import models as md
from app.modules.fin.receivables import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.ArInvoice, out_schema=sc.ArInvoiceOut, create_schema=sc.ArInvoiceCreate, update_schema=sc.ArInvoiceUpdate, resource='ar-invoice', search_fields=['invoice_no', 'partner_name'], order_by='invoice_date desc', label='ArInvoice'))
router.include_router(build_crud_router(model=md.ArInvoiceLine, out_schema=sc.ArInvoiceLineOut, create_schema=sc.ArInvoiceLineCreate, update_schema=sc.ArInvoiceLineUpdate, resource='ar-invoice-line', search_fields=['item_name'], order_by='id desc', label='ArInvoiceLine'))
router.include_router(build_crud_router(model=md.ArReceipt, out_schema=sc.ArReceiptOut, create_schema=sc.ArReceiptCreate, update_schema=sc.ArReceiptUpdate, resource='ar-receipt', search_fields=['receipt_no'], order_by='receipt_date desc', label='ArReceipt'))
router.include_router(build_crud_router(model=md.ArReceiptAllocation, out_schema=sc.ArReceiptAllocationOut, create_schema=sc.ArReceiptAllocationCreate, update_schema=sc.ArReceiptAllocationUpdate, resource='ar-receipt-allocation', search_fields=[], order_by='id desc', label='ArReceiptAllocation'))

__all__ = ['router']  # entities: ArInvoice, ArInvoiceLine, ArReceipt, ArReceiptAllocation
