# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""売上・請求（receivables）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class ArInvoice(Base):
    __tablename__ = "fin_ar_invoice"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    invoice_no = Column(String(40), index=True)
    partner_id = Column(Integer, index=True)
    partner_name = Column(String(200))
    invoice_date = Column(Date, nullable=False)
    due_date = Column(Date)
    subtotal = Column(Numeric(18, 2), default=0)
    tax_amount = Column(Numeric(18, 2), default=0)
    total_amount = Column(Numeric(18, 2), default=0)
    paid_amount = Column(Numeric(18, 2), default=0)
    status = Column(String(20), index=True, default="draft")
    source_invoice_id = Column(Integer)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ArInvoiceLine(Base):
    __tablename__ = "fin_ar_invoice_line"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    invoice_id = Column(BigInteger, ForeignKey("fin_ar_invoice.id", ondelete="CASCADE"), nullable=False)
    line_no = Column(Integer, default=1)
    item_name = Column(String(200))
    quantity = Column(Numeric(18, 4), default=0)
    unit_price = Column(Numeric(18, 4), default=0)
    tax_code = Column(String(20))
    amount = Column(Numeric(18, 2), default=0)
    account_code = Column(String(50))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ArReceipt(Base):
    __tablename__ = "fin_ar_receipt"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    receipt_no = Column(String(40), index=True)
    partner_id = Column(Integer, index=True)
    receipt_date = Column(Date, nullable=False)
    amount = Column(Numeric(18, 2), default=0)
    method = Column(String(30))
    bank_account_id = Column(Integer)
    status = Column(String(20), index=True, default="unmatched")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ArReceiptAllocation(Base):
    __tablename__ = "fin_ar_receipt_allocation"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    receipt_id = Column(BigInteger, ForeignKey("fin_ar_receipt.id", ondelete="CASCADE"), nullable=False)
    invoice_id = Column(BigInteger, index=True)
    allocated_amount = Column(Numeric(18, 2), default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

