# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""売上・請求（receivables）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class ArInvoiceCreate(BaseModel):
    invoice_no: Optional[str] = None
    partner_id: Optional[int] = None
    partner_name: Optional[str] = None
    invoice_date: Optional[date] = None
    due_date: Optional[date] = None
    subtotal: Optional[float] = None
    tax_amount: Optional[float] = None
    total_amount: Optional[float] = None
    paid_amount: Optional[float] = None
    status: Optional[str] = None
    source_invoice_id: Optional[int] = None


class ArInvoiceUpdate(ArInvoiceCreate):
    pass


class ArInvoiceOut(ArInvoiceCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ArInvoicePage(BaseModel):
    items: List[ArInvoiceOut]
    total: int
    page: int
    page_size: int
    pages: int


class ArInvoiceLineCreate(BaseModel):
    invoice_id: Optional[int] = None
    line_no: Optional[int] = None
    item_name: Optional[str] = None
    quantity: Optional[float] = None
    unit_price: Optional[float] = None
    tax_code: Optional[str] = None
    amount: Optional[float] = None
    account_code: Optional[str] = None


class ArInvoiceLineUpdate(ArInvoiceLineCreate):
    pass


class ArInvoiceLineOut(ArInvoiceLineCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ArInvoiceLinePage(BaseModel):
    items: List[ArInvoiceLineOut]
    total: int
    page: int
    page_size: int
    pages: int


class ArReceiptCreate(BaseModel):
    receipt_no: Optional[str] = None
    partner_id: Optional[int] = None
    receipt_date: Optional[date] = None
    amount: Optional[float] = None
    method: Optional[str] = None
    bank_account_id: Optional[int] = None
    status: Optional[str] = None


class ArReceiptUpdate(ArReceiptCreate):
    pass


class ArReceiptOut(ArReceiptCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ArReceiptPage(BaseModel):
    items: List[ArReceiptOut]
    total: int
    page: int
    page_size: int
    pages: int


class ArReceiptAllocationCreate(BaseModel):
    receipt_id: Optional[int] = None
    invoice_id: Optional[int] = None
    allocated_amount: Optional[float] = None


class ArReceiptAllocationUpdate(ArReceiptAllocationCreate):
    pass


class ArReceiptAllocationOut(ArReceiptAllocationCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ArReceiptAllocationPage(BaseModel):
    items: List[ArReceiptAllocationOut]
    total: int
    page: int
    page_size: int
    pages: int

