-- TABLE: cutting_management
-- 生成元: scripts/export_schema_split.py
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `cutting_management` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'システムID',
  `production_month` date NOT NULL COMMENT '生産月',
  `production_day` date NOT NULL COMMENT '生産日',
  `production_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ライン',
  `cutting_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '切断機（手動指定）',
  `production_sequence` int DEFAULT '0' COMMENT '生産順（同一切断機内の自動並び順、拖拽可変更）',
  `priority_order` int DEFAULT NULL COMMENT '順位',
  `product_cd` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '製品CD',
  `product_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '製品名',
  `planned_quantity` int DEFAULT '0' COMMENT '計画数',
  `start_date` datetime DEFAULT NULL COMMENT '開始期日',
  `end_date` datetime DEFAULT NULL COMMENT '終了期日',
  `production_lot_size` int DEFAULT NULL COMMENT '生産ロット数',
  `lot_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ロットNo.',
  `is_cutting_instructed` tinyint(1) DEFAULT '0' COMMENT '切断指示',
  `has_chamfering_process` tinyint(1) DEFAULT '0' COMMENT '面取工程',
  `is_chamfering_instructed` tinyint(1) DEFAULT '0' COMMENT '面取指示',
  `has_sw_process` tinyint(1) DEFAULT '0' COMMENT 'SW工程',
  `is_sw_instructed` tinyint(1) DEFAULT '0' COMMENT 'SW指示',
  `actual_production_quantity` int DEFAULT '0' COMMENT '生産数',
  `defect_qty` int DEFAULT '0' COMMENT '不良数',
  `take_count` int DEFAULT NULL COMMENT '取数',
  `cutting_length` decimal(10,2) DEFAULT NULL COMMENT '切断長',
  `chamfering_length` decimal(10,2) DEFAULT NULL COMMENT '面取長',
  `developed_length` decimal(10,2) DEFAULT NULL COMMENT '展開長',
  `scrap_length` decimal(10,2) DEFAULT NULL COMMENT '端材長さ(mm)',
  `material_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原材料',
  `material_manufacturer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '材料メーカー',
  `standard_specification` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '規格',
  `management_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '管理コード',
  `aps_batch_plan_id` int DEFAULT NULL COMMENT 'APS ロット（aps_batch_plans.id）参照',
  `production_completed_check` tinyint(1) NOT NULL DEFAULT '0' COMMENT '生産完了チェック',
  `material_usage_reflected` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '未反映' COMMENT '使用材料が material_usage_record に反映済みか（反映済/未反映）',
  `use_material_stock_sub` tinyint(1) NOT NULL DEFAULT '0' COMMENT '使用サブ在庫（0=反映対象, 1=対象外・material_stock_subで手動）',
  `usage_count` decimal(10,4) NOT NULL DEFAULT '1.0000' COMMENT '材料使用数（1=1本, <1=他行と同一本を按分）',
  `mes_production_started_at` datetime DEFAULT NULL COMMENT 'MES切断実績収集・生産開始日時',
  `mes_production_ended_at` datetime DEFAULT NULL COMMENT 'MES切断実績収集・生産終了日時',
  `mes_net_production_sec` int DEFAULT NULL COMMENT 'MES净生産秒数(一時停止除く,段取除く)',
  `mes_paused_accum_sec` int DEFAULT NULL COMMENT 'MES一時停止累計秒数(一時停止〜再開の合計)',
  `mes_production_is_paused` tinyint(1) DEFAULT NULL COMMENT 'MES稼働計測:1=一時停止中,0=稼働中,NULL=未開始/終了済',
  `mes_setup_time_min` int DEFAULT NULL COMMENT 'MES段取時間(分)',
  `mes_saw_blade_exchange_min` int DEFAULT NULL COMMENT 'MES鋸刃交換時間(分)',
  `mes_repair_min` int DEFAULT NULL COMMENT 'MES修理時間(分)',
  `mes_operator_user_id` int DEFAULT NULL COMMENT 'MES作業者(users.id)',
  `mes_scanned_code` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MES切断実績・バーコード/QR読取',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `remarks` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '備考',
  `cd` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (right(`management_code`,5)) VIRTUAL COMMENT 'CD(管理コード後5位)',
  PRIMARY KEY (`id`),
  KEY `idx_production_day` (`production_day`),
  KEY `idx_product_cd` (`product_cd`),
  KEY `idx_management_code` (`management_code`),
  KEY `idx_production_month` (`production_month`),
  KEY `idx_cutting_machine` (`cutting_machine`),
  KEY `idx_production_sequence` (`production_sequence`),
  KEY `idx_cutting_aps_batch_plan_id` (`aps_batch_plan_id`),
  CONSTRAINT `fk_cutting_management_aps_batch_plan` FOREIGN KEY (`aps_batch_plan_id`) REFERENCES `aps_batch_plans` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='切断指示';

SET FOREIGN_KEY_CHECKS = 1;
