-- TABLE: production_summarys
-- 生成元: scripts/export_schema_split.py
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `production_summarys` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID（自動採番）',
  `route_cd` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工程グループコード',
  `product_cd` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '製品コード',
  `product_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '製品名',
  `date` date NOT NULL COMMENT '日付',
  `day_of_week` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '曜日',
  `order_quantity` int DEFAULT '0' COMMENT '受注数',
  `forecast_quantity` int DEFAULT '0' COMMENT '内示数',
  `safety_stock` int DEFAULT '0' COMMENT '安全在庫',
  `cutting_carry_over` int DEFAULT '0' COMMENT '切断繰越',
  `cutting_actual` int DEFAULT '0' COMMENT '切断実績',
  `cutting_defect` int DEFAULT '0' COMMENT '切断不良',
  `cutting_scrap` int DEFAULT '0' COMMENT '切断廃棄',
  `cutting_on_hold` int DEFAULT '0' COMMENT '切断保留品',
  `cutting_inventory` int DEFAULT '0' COMMENT '切断在庫',
  `cutting_trend` int DEFAULT '0' COMMENT '切断推移',
  `cutting_production_date` date DEFAULT NULL COMMENT '切断生産日',
  `cutting_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '切断機',
  `cutting_plan` int DEFAULT '0' COMMENT '切断計画',
  `cutting_actual_plan` int DEFAULT '0' COMMENT '切断実計',
  `cutting_actual_plan_trend` int DEFAULT '0' COMMENT '切断実計推移',
  `chamfering_carry_over` int DEFAULT '0' COMMENT '面取繰越',
  `chamfering_actual` int DEFAULT '0' COMMENT '面取実績',
  `chamfering_defect` int DEFAULT '0' COMMENT '面取不良',
  `chamfering_scrap` int DEFAULT '0' COMMENT '面取廃棄',
  `chamfering_on_hold` int DEFAULT '0' COMMENT '面取保留品',
  `chamfering_inventory` int DEFAULT '0' COMMENT '面取在庫',
  `chamfering_trend` int DEFAULT '0' COMMENT '面取推移',
  `chamfering_production_date` date DEFAULT NULL COMMENT '面取生産日',
  `chamfering_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '面取機',
  `chamfering_plan` int DEFAULT '0' COMMENT '面取計画',
  `sw_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'sw機',
  `sw_plan` int DEFAULT NULL COMMENT 'sw計画',
  `chamfering_actual_plan` int DEFAULT '0' COMMENT '面取実計',
  `chamfering_actual_plan_trend` int DEFAULT '0' COMMENT '面取実計推移',
  `molding_carry_over` int DEFAULT '0' COMMENT '成型繰越',
  `molding_actual` int DEFAULT '0' COMMENT '成型実績',
  `molding_defect` int DEFAULT '0' COMMENT '成型不良',
  `molding_scrap` int DEFAULT '0' COMMENT '成型廃棄',
  `molding_on_hold` int DEFAULT '0' COMMENT '成型保留品',
  `molding_inventory` int DEFAULT '0' COMMENT '成型在庫',
  `molding_trend` int DEFAULT '0' COMMENT '成型推移',
  `molding_production_date` date DEFAULT NULL COMMENT '成型生産日',
  `molding_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '成型機',
  `molding_plan` int DEFAULT '0' COMMENT '成型計画',
  `molding_actual_plan` int DEFAULT '0' COMMENT '成型実計',
  `molding_actual_plan_trend` int DEFAULT '0' COMMENT '成型実計推移',
  `plating_carry_over` int DEFAULT '0' COMMENT 'メッキ繰越',
  `plating_actual` int DEFAULT '0' COMMENT 'メッキ実績',
  `plating_defect` int DEFAULT '0' COMMENT 'メッキ不良',
  `plating_scrap` int DEFAULT '0' COMMENT 'メッキ廃棄',
  `plating_on_hold` int DEFAULT '0' COMMENT 'メッキ保留品',
  `plating_inventory` int DEFAULT '0' COMMENT 'メッキ在庫',
  `plating_trend` int DEFAULT '0' COMMENT 'メッキ推移',
  `plating_production_date` date DEFAULT NULL COMMENT 'メッキ生産日',
  `plating_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'メッキ治具',
  `plating_plan` int DEFAULT '0' COMMENT 'メッキ計画',
  `plating_actual_plan` int DEFAULT '0' COMMENT 'メッキ実計',
  `plating_actual_plan_trend` int DEFAULT '0' COMMENT 'メッキ実計推移',
  `welding_carry_over` int DEFAULT '0' COMMENT '溶接繰越',
  `welding_actual` int DEFAULT '0' COMMENT '溶接実績',
  `welding_defect` int DEFAULT '0' COMMENT '溶接不良',
  `welding_scrap` int DEFAULT '0' COMMENT '溶接廃棄',
  `welding_on_hold` int DEFAULT '0' COMMENT '溶接保留品',
  `welding_inventory` int DEFAULT '0' COMMENT '溶接在庫',
  `welding_trend` int DEFAULT '0' COMMENT '溶接推移',
  `welding_production_date` date DEFAULT NULL COMMENT '溶接生産日',
  `welding_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '溶接機',
  `welding_plan` int DEFAULT '0' COMMENT '溶接計画',
  `welding_actual_plan` int DEFAULT '0' COMMENT '溶接実計',
  `welding_actual_plan_trend` int DEFAULT '0' COMMENT '溶接実計推移',
  `inspection_carry_over` int DEFAULT '0' COMMENT '検査繰越',
  `inspection_actual` int DEFAULT '0' COMMENT '検査実績',
  `inspection_defect` int DEFAULT '0' COMMENT '検査不良',
  `inspection_scrap` int DEFAULT '0' COMMENT '検査廃棄',
  `inspection_on_hold` int DEFAULT '0' COMMENT '検査保留品',
  `inspection_inventory` int DEFAULT '0' COMMENT '検査在庫',
  `inspection_trend` int DEFAULT '0' COMMENT '検査推移',
  `inspection_production_date` date DEFAULT NULL COMMENT '検査生産日',
  `inspector_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '検査員',
  `inspection_plan` int DEFAULT '0' COMMENT '検査計画',
  `inspection_actual_plan` int DEFAULT '0' COMMENT '検査実計',
  `inspection_actual_plan_trend` int DEFAULT '0' COMMENT '検査実計推移',
  `warehouse_carry_over` int DEFAULT '0' COMMENT '倉庫繰越',
  `warehouse_actual` int DEFAULT '0' COMMENT '倉庫実績',
  `warehouse_defect` int DEFAULT '0' COMMENT '倉庫不良',
  `warehouse_scrap` int DEFAULT '0' COMMENT '倉庫廃棄',
  `warehouse_on_hold` int DEFAULT '0' COMMENT '倉庫保留品',
  `warehouse_inventory` int DEFAULT '0' COMMENT '倉庫在庫',
  `warehouse_trend` int DEFAULT '0' COMMENT '倉庫推移',
  `outsourced_warehouse_carry_over` int DEFAULT '0' COMMENT '外注倉庫繰越',
  `outsourced_warehouse_actual` int DEFAULT '0' COMMENT '外注倉庫実績',
  `outsourced_warehouse_defect` int DEFAULT '0' COMMENT '外注倉庫不良',
  `outsourced_warehouse_scrap` int DEFAULT '0' COMMENT '外注倉庫廃棄',
  `outsourced_warehouse_on_hold` int DEFAULT '0' COMMENT '外注倉庫保留品',
  `outsourced_warehouse_plan` int DEFAULT NULL COMMENT '外注倉庫計画',
  `outsourced_warehouse_inventory` int DEFAULT '0' COMMENT '外注倉庫在庫',
  `outsourced_warehouse_trend` int DEFAULT '0' COMMENT '外注倉庫推移',
  `outsourced_plating_carry_over` int DEFAULT '0' COMMENT '外注メッキ繰越',
  `outsourced_plating_actual` int DEFAULT '0' COMMENT '外注メッキ実績',
  `outsourced_plating_defect` int DEFAULT '0' COMMENT '外注メッキ不良',
  `outsourced_plating_scrap` int DEFAULT '0' COMMENT '外注メッキ廃棄',
  `outsourced_plating_on_hold` int DEFAULT '0' COMMENT '外注メッキ保留品',
  `outsourced_plating_inventory` int DEFAULT '0' COMMENT '外注メッキ在庫',
  `outsourced_plating_production_date` date DEFAULT NULL COMMENT '外注メッキ生産日',
  `outsourced_plating_trend` int DEFAULT '0' COMMENT '外注メッキ推移',
  `outsourced_plating_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '外注メッキ先',
  `outsourced_plating_plan` int DEFAULT '0' COMMENT '外注メッキ計画',
  `outsourced_plating_actual_plan` int DEFAULT '0' COMMENT '外注メッキ実計',
  `outsourced_plating_actual_plan_trend` int DEFAULT '0' COMMENT '外注メッキ実計推移',
  `outsourced_welding_carry_over` int DEFAULT '0' COMMENT '外注溶接繰越',
  `outsourced_welding_actual` int DEFAULT '0' COMMENT '外注溶接実績',
  `outsourced_welding_defect` int DEFAULT '0' COMMENT '外注溶接不良',
  `outsourced_welding_scrap` int DEFAULT '0' COMMENT '外注溶接廃棄',
  `outsourced_welding_on_hold` int DEFAULT '0' COMMENT '外注溶接保留品',
  `outsourced_welding_inventory` int DEFAULT '0' COMMENT '外注溶接在庫',
  `outsourced_welding_production_date` date DEFAULT NULL COMMENT '外注溶接生産日',
  `outsourced_welding_trend` int DEFAULT '0' COMMENT '外注溶接推移',
  `outsourced_welding_machine` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '外注溶接先',
  `outsourced_welding_plan` int DEFAULT '0' COMMENT '外注溶接計画',
  `outsourced_welding_actual_plan` int DEFAULT '0' COMMENT '外注溶接実計',
  `outsourced_welding_actual_plan_trend` int DEFAULT '0' COMMENT '外注溶接実計推移',
  `pre_welding_inspection_carry_over` int DEFAULT '0' COMMENT '溶接前検査繰越',
  `pre_welding_inspection_actual` int DEFAULT '0' COMMENT '溶接前検査実績',
  `pre_welding_inspection_defect` int DEFAULT '0' COMMENT '溶接前検査不良',
  `pre_welding_inspection_scrap` int DEFAULT '0' COMMENT '溶接前検査廃棄',
  `pre_welding_inspection_on_hold` int DEFAULT '0' COMMENT '溶接前検査保留品',
  `pre_welding_inspection_inventory` int DEFAULT '0' COMMENT '溶接前検査在庫',
  `pre_welding_inspection_trend` int DEFAULT '0' COMMENT '溶接前検査推移',
  `pre_inspection_carry_over` int DEFAULT '0' COMMENT '外注支給前繰越',
  `pre_inspection_actual` int DEFAULT '0' COMMENT '外注支給前実績',
  `pre_inspection_scrap` int DEFAULT '0' COMMENT '外注支給前廃棄',
  `pre_inspection_inventory` int DEFAULT '0' COMMENT '外注支給前在庫',
  `pre_inspection_trend` int DEFAULT '0' COMMENT '外注支給前推移',
  `pre_outsourcing_carry_over` int DEFAULT '0' COMMENT '外注検査前繰越',
  `pre_outsourcing_actual` int DEFAULT '0' COMMENT '外注検査前実績',
  `pre_outsourcing_scrap` int DEFAULT '0' COMMENT '外注検査前廃棄',
  `pre_outsourcing_inventory` int DEFAULT '0' COMMENT '外注検査前在庫',
  `pre_outsourcing_trend` int DEFAULT '0' COMMENT '外注検査前推移',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_date_product` (`date`,`product_cd`) USING BTREE,
  KEY `idx_date` (`date`) USING BTREE,
  KEY `idx_product_cd` (`product_cd`) USING BTREE,
  KEY `idx_route_cd` (`route_cd`) USING BTREE,
  KEY `idx_date_product` (`date`,`product_cd`) USING BTREE,
  KEY `idx_cutting_machine` (`cutting_machine`) USING BTREE,
  KEY `idx_chamfering_machine` (`chamfering_machine`) USING BTREE,
  KEY `idx_molding_machine` (`molding_machine`) USING BTREE,
  KEY `idx_plating_machine` (`plating_machine`) USING BTREE,
  KEY `idx_welding_machine` (`welding_machine`) USING BTREE,
  KEY `idx_inspector_machine` (`inspector_machine`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='生産実績サマリーデータ';

SET FOREIGN_KEY_CHECKS = 1;
