/** 工場レイアウト画面は言語設定に関係なく日本語で表示する。 */
const ja = {
  title: '工場レイアウト',
  view: '表示',
  edit: '編集',
  save: 'レイアウト保存',
  exportPdf: 'PDF出力',
  exported: 'PDFを出力しました',
  exportFailed: 'PDFの出力に失敗しました',
  exportedAt: '出力日時',
  saved: 'レイアウトを保存しました',
  saveFailed: '保存に失敗しました',
  create: '新規レイアウト',
  createTitle: '新規レイアウト',
  name: '名称',
  nameRequired: '名称を入力してください',
  created: '作成しました',
  deleteLayout: 'レイアウト削除',
  deleteLayoutConfirm: 'このレイアウトと、設備・通路・材料置き場を削除しますか？',
  deleted: '削除しました',
  empty: '工場レイアウトがありません',
  emptyHint: 'レイアウトを作成し、設備・通路・材料置き場をドラッグしてください。',
  palette: '追加',
  paletteHint: '図へドラッグ。空白をドラッグで範囲選択、Space で移動。ダブルクリックで内容を編集。',
  editContentHint: 'ダブルクリックで詳細を開き、名称などを編集できます',
  undo: '元に戻す',
  redo: 'やり直す',
  copy: 'コピー',
  paste: '貼り付け',
  duplicate: '複製',
  duplicateObject: 'オブジェクト複製',
  objectCopied: 'コピーしました（Ctrl+V で貼り付け）',
  objectDuplicated: 'オブジェクトを複製しました',
  duplicateLayout: 'レイアウト複製',
  duplicated: 'レイアウトを複製しました',
  copySuffix: 'コピー',
  rename: '名前変更',
  renamed: '名称を更新しました',
  canvasSettings: 'キャンバス',
  canvasWidth: '幅',
  canvasHeight: '高さ',
  gridSize: 'グリッド',
  align: '整列',
  alignLeft: '左揃え',
  alignHCenter: '左右中央',
  alignRight: '右揃え',
  alignTop: '上揃え',
  alignVCenter: '上下中央',
  alignBottom: '下揃え',
  distributeH: '左右に分布',
  distributeV: '上下に分布',
  forward: '前面へ',
  backward: '背面へ',
  toFront: '最前面',
  toBack: '最背面',
  rotate: '90°回転',
  rotation: '角度',
  lock: 'ロック',
  unlock: 'ロック解除',
  lockedMark: '鍵',
  lockedSkip: 'ロック中のオブジェクトは削除・移動できません',
  group: 'グループ化',
  ungroup: 'グループ解除',
  snap: 'グリッド吸着',
  grid: 'グリッド表示',
  selectAll: 'すべて選択',
  selectSame: '同じ種別を選択',
  zoomSelection: '選択に合わせる',
  shortcuts: 'ショートカット',
  layers: 'レイヤー',
  selection: '選択',
  selectionCount: '{n} 件選択',
  position: '位置',
  size: 'サイズ',
  nudgeHint: '矢印キーで微調整、Shift で大きく移動',
  panHint: 'Space を押しながらドラッグで移動',
  shiftHint: 'Shift で追加選択',
  legend: '凡例',
  zoomFit: '全体',
  fullscreen: '全画面',
  exitFullscreen: '全画面解除',
  detail: '詳細',
  type: '種別',
  label: '名称',
  bindMachine: '設備',
  bindLocation: '庫位',
  locationPlaceholder: '庫位を選択または入力',
  unbound: '未設定',
  status: '状態',
  message: '説明',
  source: 'データ元',
  sourceMock: '模擬',
  sourcePlc: 'PLC',
  updatedAt: '更新時刻',
  applyStatus: '模擬状態を適用',
  statusSaved: '状態を更新しました',
  statusFailed: '状態の更新に失敗しました',
  statusNeedSave: '先にレイアウトを保存してから模擬状態を設定してください',
  plcLocked: 'PLC の状態はここでは変更できません',
  deleteObject: '削除',
  loadFailed: '読み込みに失敗しました',
  unsavedSwitch: '未保存の変更があります。切り替えると破棄されます。続行しますか？',
  fill: '塗り',
  border: '枠線',
  opacity: '不透明度',
  useStatusColor: '状態色に戻す',
  clearBorder: '枠線なし',
  styleHint: '塗りを未設定にすると、状態の色を使います。',
  cancel: 'キャンセル',
  confirm: '確認',
  hoverSoon: '表示内容は後日追加予定',
  enterWorkshop: '開く',
  workshopUnlinked: '未接続',
  backToParent: '戻る',
  createChildLayout: '新規作成',
  childLayout: '内部レイアウト',
  childLayoutSelect: 'レイアウト指定',
  childLayoutNone: '未指定',
  childLayoutHint: '既存の加工区レイアウトを選ぶか、新規作成できます。',
  childLayoutCreated: '内部レイアウトを作成しました',
  sectionBasic: '基本',
  sectionGeometry: '位置・サイズ',
  sectionStyle: 'スタイル',
  sectionStatus: '状態',
  kindSite: '総図',
  kindWorkshop: '加工区',
  typeName: {
    machine: '設備',
    aisle: '通路',
    material_zone: '材料置き場',
    workshop: '加工区',
  },
  statusName: {
    running: '稼働',
    idle: '待機',
    alarm: '警報',
    maintenance: '保全',
    offline: 'オフライン',
    open: '通行可',
    blocked: '閉鎖',
    stocked: '在庫あり',
    empty: '空',
    low: '不足',
  },
} as const

export function fl(path: string, vars?: Record<string, string | number>): string {
  const parts = path.split('.')
  let current: unknown = ja
  for (const part of parts) {
    if (!current || typeof current !== 'object' || !(part in current)) return path
    current = (current as Record<string, unknown>)[part]
  }
  let text = typeof current === 'string' ? current : path
  if (vars) {
    for (const [key, value] of Object.entries(vars)) {
      text = text.replaceAll(`{${key}}`, String(value))
    }
  }
  return text
}
