"""
production_summarys テーブルモデル（生産実績サマリーデータ）
"""
from sqlalchemy import Column, Integer, String, Date
from app.core.database import Base


class ProductionSummary(Base):
    """生産実績サマリーデータ"""
    __tablename__ = "production_summarys"

    id = Column(Integer, primary_key=True, autoincrement=True, comment="ID（自動採番）")
    route_cd = Column(String(50), comment="工程グループコード")
    product_cd = Column(String(50), comment="製品コード")
    product_name = Column(String(255), comment="製品名")
    date = Column(Date, nullable=False, comment="日付")
    day_of_week = Column(String(10), comment="曜日")
    order_quantity = Column(Integer, default=0, comment="受注数")
    forecast_quantity = Column(Integer, default=0, comment="内示数")
    safety_stock = Column(Integer, default=0, comment="安全在庫")
    # 切断
    cutting_carry_over = Column(Integer, default=0)
    cutting_actual = Column(Integer, default=0)
    cutting_defect = Column(Integer, default=0)
    cutting_scrap = Column(Integer, default=0)
    cutting_on_hold = Column(Integer, default=0)
    cutting_inventory = Column(Integer, default=0)
    cutting_trend = Column(Integer, default=0)
    cutting_production_date = Column(Date)
    cutting_machine = Column(String(50))
    cutting_plan = Column(Integer, default=0)
    cutting_actual_plan = Column(Integer, default=0)
    cutting_actual_plan_trend = Column(Integer, default=0)
    # 面取
    chamfering_carry_over = Column(Integer, default=0)
    chamfering_actual = Column(Integer, default=0)
    chamfering_defect = Column(Integer, default=0)
    chamfering_scrap = Column(Integer, default=0)
    chamfering_on_hold = Column(Integer, default=0)
    chamfering_inventory = Column(Integer, default=0)
    chamfering_trend = Column(Integer, default=0)
    chamfering_production_date = Column(Date)
    chamfering_machine = Column(String(50))
    chamfering_plan = Column(Integer, default=0)
    chamfering_actual_plan = Column(Integer, default=0)
    chamfering_actual_plan_trend = Column(Integer, default=0)
    # 成型
    molding_carry_over = Column(Integer, default=0)
    molding_actual = Column(Integer, default=0)
    molding_defect = Column(Integer, default=0)
    molding_scrap = Column(Integer, default=0)
    molding_on_hold = Column(Integer, default=0)
    molding_inventory = Column(Integer, default=0)
    molding_trend = Column(Integer, default=0)
    molding_production_date = Column(Date)
    molding_machine = Column(String(50))
    molding_plan = Column(Integer, default=0)
    molding_actual_plan = Column(Integer, default=0)
    molding_actual_plan_trend = Column(Integer, default=0)
    # メッキ
    plating_carry_over = Column(Integer, default=0)
    plating_actual = Column(Integer, default=0)
    plating_defect = Column(Integer, default=0)
    plating_scrap = Column(Integer, default=0)
    plating_on_hold = Column(Integer, default=0)
    plating_inventory = Column(Integer, default=0)
    plating_trend = Column(Integer, default=0)
    plating_production_date = Column(Date)
    plating_machine = Column(String(50))
    plating_plan = Column(Integer, default=0)
    plating_actual_plan = Column(Integer, default=0)
    plating_actual_plan_trend = Column(Integer, default=0)
    # 溶接
    welding_carry_over = Column(Integer, default=0)
    welding_actual = Column(Integer, default=0)
    welding_defect = Column(Integer, default=0)
    welding_scrap = Column(Integer, default=0)
    welding_on_hold = Column(Integer, default=0)
    welding_inventory = Column(Integer, default=0)
    welding_trend = Column(Integer, default=0)
    welding_production_date = Column(Date)
    welding_machine = Column(String(50))
    welding_plan = Column(Integer, default=0)
    welding_actual_plan = Column(Integer, default=0)
    welding_actual_plan_trend = Column(Integer, default=0)
    # 検査
    inspection_carry_over = Column(Integer, default=0)
    inspection_actual = Column(Integer, default=0)
    inspection_defect = Column(Integer, default=0)
    inspection_scrap = Column(Integer, default=0)
    inspection_on_hold = Column(Integer, default=0)
    inspection_inventory = Column(Integer, default=0)
    inspection_trend = Column(Integer, default=0)
    inspection_production_date = Column(Date)
    inspector_machine = Column(String(50))
    inspection_plan = Column(Integer, default=0)
    inspection_actual_plan = Column(Integer, default=0)
    inspection_actual_plan_trend = Column(Integer, default=0)
    # 倉庫
    warehouse_carry_over = Column(Integer, default=0)
    warehouse_actual = Column(Integer, default=0)
    warehouse_defect = Column(Integer, default=0)
    warehouse_scrap = Column(Integer, default=0)
    warehouse_on_hold = Column(Integer, default=0)
    warehouse_inventory = Column(Integer, default=0)
    warehouse_trend = Column(Integer, default=0)
    # 外注倉庫
    outsourced_warehouse_carry_over = Column(Integer, default=0)
    outsourced_warehouse_actual = Column(Integer, default=0)
    outsourced_warehouse_defect = Column(Integer, default=0)
    outsourced_warehouse_scrap = Column(Integer, default=0)
    outsourced_warehouse_on_hold = Column(Integer, default=0)
    outsourced_warehouse_inventory = Column(Integer, default=0)
    outsourced_warehouse_trend = Column(Integer, default=0)
    # 外注メッキ
    outsourced_plating_carry_over = Column(Integer, default=0)
    outsourced_plating_actual = Column(Integer, default=0)
    outsourced_plating_defect = Column(Integer, default=0)
    outsourced_plating_scrap = Column(Integer, default=0)
    outsourced_plating_on_hold = Column(Integer, default=0)
    outsourced_plating_inventory = Column(Integer, default=0)
    outsourced_plating_production_date = Column(Date)
    outsourced_plating_trend = Column(Integer, default=0)
    outsourced_plating_machine = Column(String(50))
    outsourced_plating_plan = Column(Integer, default=0)
    outsourced_plating_actual_plan = Column(Integer, default=0)
    outsourced_plating_actual_plan_trend = Column(Integer, default=0)
    # 外注溶接
    outsourced_welding_carry_over = Column(Integer, default=0)
    outsourced_welding_actual = Column(Integer, default=0)
    outsourced_welding_defect = Column(Integer, default=0)
    outsourced_welding_scrap = Column(Integer, default=0)
    outsourced_welding_on_hold = Column(Integer, default=0)
    outsourced_welding_inventory = Column(Integer, default=0)
    outsourced_welding_production_date = Column(Date)
    outsourced_welding_trend = Column(Integer, default=0)
    outsourced_welding_machine = Column(String(50))
    outsourced_welding_plan = Column(Integer, default=0)
    outsourced_welding_actual_plan = Column(Integer, default=0)
    outsourced_welding_actual_plan_trend = Column(Integer, default=0)
    # 溶接前検査
    pre_welding_inspection_carry_over = Column(Integer, default=0)
    pre_welding_inspection_actual = Column(Integer, default=0)
    pre_welding_inspection_defect = Column(Integer, default=0)
    pre_welding_inspection_scrap = Column(Integer, default=0)
    pre_welding_inspection_on_hold = Column(Integer, default=0)
    pre_welding_inspection_inventory = Column(Integer, default=0)
    pre_welding_inspection_trend = Column(Integer, default=0)
    # 外注支給前
    pre_inspection_carry_over = Column(Integer, default=0)
    pre_inspection_actual = Column(Integer, default=0)
    pre_inspection_scrap = Column(Integer, default=0)
    pre_inspection_inventory = Column(Integer, default=0)
    pre_inspection_trend = Column(Integer, default=0)
    # 外注検査前
    pre_outsourcing_carry_over = Column(Integer, default=0)
    pre_outsourcing_actual = Column(Integer, default=0)
    pre_outsourcing_scrap = Column(Integer, default=0)
    pre_outsourcing_inventory = Column(Integer, default=0)
    pre_outsourcing_trend = Column(Integer, default=0)
