"""
production_summarys テーブルモデル（生産実績サマリーデータ）
"""
from sqlalchemy import Boolean, Column, Date, DateTime, Integer, String
from sqlalchemy.sql import func
from app.core.database import Base


class ProductionSummary(Base):
    """生産実績サマリーデータ"""
    __tablename__ = "production_summarys"

    id = Column(Integer, primary_key=True, autoincrement=True, comment="ID（自動採番）")
    route_cd = Column(String(50), comment="工程グループコード")
    product_cd = Column(String(50), comment="製品コード")
    product_name = Column(String(255), comment="製品名")
    date = Column(Date, nullable=False, comment="日付")
    day_of_week = Column(String(10), comment="曜日")
    order_quantity = Column(Integer, default=0, comment="受注数")
    forecast_quantity = Column(Integer, default=0, comment="内示数")
    safety_stock = Column(Integer, default=0, comment="安全在庫")
    # 切断
    cutting_carry_over = Column(Integer, default=0)
    cutting_actual = Column(Integer, default=0)
    cutting_defect = Column(Integer, default=0)
    cutting_scrap = Column(Integer, default=0)
    cutting_on_hold = Column(Integer, default=0)
    cutting_inventory = Column(Integer, default=0)
    cutting_trend = Column(Integer, default=0)
    cutting_production_date = Column(Date)
    cutting_machine = Column(String(50))
    cutting_plan = Column(Integer, default=0)
    cutting_actual_plan = Column(Integer, default=0)
    cutting_actual_plan_trend = Column(Integer, default=0)
    # 面取
    chamfering_carry_over = Column(Integer, default=0)
    chamfering_actual = Column(Integer, default=0)
    chamfering_defect = Column(Integer, default=0)
    chamfering_scrap = Column(Integer, default=0)
    chamfering_on_hold = Column(Integer, default=0)
    chamfering_inventory = Column(Integer, default=0)
    chamfering_trend = Column(Integer, default=0)
    chamfering_production_date = Column(Date)
    chamfering_machine = Column(String(50))
    sw_machine = Column(String(100))
    sw_plan = Column(Integer, default=0)
    chamfering_plan = Column(Integer, default=0)
    chamfering_actual_plan = Column(Integer, default=0)
    chamfering_actual_plan_trend = Column(Integer, default=0)
    # 成型
    molding_carry_over = Column(Integer, default=0)
    molding_actual = Column(Integer, default=0)
    molding_defect = Column(Integer, default=0)
    molding_scrap = Column(Integer, default=0)
    molding_on_hold = Column(Integer, default=0)
    molding_inventory = Column(Integer, default=0)
    molding_trend = Column(Integer, default=0)
    molding_production_date = Column(Date)
    molding_machine = Column(String(50))
    molding_plan = Column(Integer, default=0)
    molding_actual_plan = Column(Integer, default=0)
    molding_actual_plan_trend = Column(Integer, default=0)
    # メッキ
    plating_carry_over = Column(Integer, default=0)
    plating_actual = Column(Integer, default=0)
    plating_defect = Column(Integer, default=0)
    plating_scrap = Column(Integer, default=0)
    plating_on_hold = Column(Integer, default=0)
    plating_inventory = Column(Integer, default=0)
    plating_trend = Column(Integer, default=0)
    plating_production_date = Column(Date)
    plating_machine = Column(String(50))
    plating_plan = Column(Integer, default=0)
    plating_actual_plan = Column(Integer, default=0)
    plating_actual_plan_trend = Column(Integer, default=0)
    # 溶接
    welding_carry_over = Column(Integer, default=0)
    welding_actual = Column(Integer, default=0)
    welding_defect = Column(Integer, default=0)
    welding_scrap = Column(Integer, default=0)
    welding_on_hold = Column(Integer, default=0)
    welding_inventory = Column(Integer, default=0)
    welding_trend = Column(Integer, default=0)
    welding_production_date = Column(Date)
    welding_machine = Column(String(50))
    welding_plan = Column(Integer, default=0)
    welding_actual_plan = Column(Integer, default=0)
    welding_actual_plan_trend = Column(Integer, default=0)
    # 検査
    inspection_carry_over = Column(Integer, default=0)
    inspection_actual = Column(Integer, default=0)
    inspection_defect = Column(Integer, default=0)
    inspection_scrap = Column(Integer, default=0)
    inspection_on_hold = Column(Integer, default=0)
    inspection_inventory = Column(Integer, default=0)
    inspection_trend = Column(Integer, default=0)
    inspection_production_date = Column(Date)
    inspector_machine = Column(String(50))
    inspection_plan = Column(Integer, default=0)
    inspection_actual_plan = Column(Integer, default=0)
    inspection_actual_plan_trend = Column(Integer, default=0)
    # 倉庫
    warehouse_carry_over = Column(Integer, default=0)
    warehouse_actual = Column(Integer, default=0)
    warehouse_defect = Column(Integer, default=0)
    warehouse_scrap = Column(Integer, default=0)
    warehouse_on_hold = Column(Integer, default=0)
    warehouse_inventory = Column(Integer, default=0)
    warehouse_trend = Column(Integer, default=0)
    # 外注倉庫
    outsourced_warehouse_carry_over = Column(Integer, default=0)
    outsourced_warehouse_actual = Column(Integer, default=0)
    outsourced_warehouse_defect = Column(Integer, default=0)
    outsourced_warehouse_scrap = Column(Integer, default=0)
    outsourced_warehouse_on_hold = Column(Integer, default=0)
    outsourced_warehouse_inventory = Column(Integer, default=0)
    outsourced_warehouse_trend = Column(Integer, default=0)
    outsourced_warehouse_plan = Column(Integer, default=0)
    # 外注メッキ
    outsourced_plating_carry_over = Column(Integer, default=0)
    outsourced_plating_actual = Column(Integer, default=0)
    outsourced_plating_defect = Column(Integer, default=0)
    outsourced_plating_scrap = Column(Integer, default=0)
    outsourced_plating_on_hold = Column(Integer, default=0)
    outsourced_plating_inventory = Column(Integer, default=0)
    outsourced_plating_production_date = Column(Date)
    outsourced_plating_trend = Column(Integer, default=0)
    outsourced_plating_machine = Column(String(50))
    outsourced_plating_plan = Column(Integer, default=0)
    outsourced_plating_actual_plan = Column(Integer, default=0)
    outsourced_plating_actual_plan_trend = Column(Integer, default=0)
    # 外注溶接
    outsourced_welding_carry_over = Column(Integer, default=0)
    outsourced_welding_actual = Column(Integer, default=0)
    outsourced_welding_defect = Column(Integer, default=0)
    outsourced_welding_scrap = Column(Integer, default=0)
    outsourced_welding_on_hold = Column(Integer, default=0)
    outsourced_welding_inventory = Column(Integer, default=0)
    outsourced_welding_production_date = Column(Date)
    outsourced_welding_trend = Column(Integer, default=0)
    outsourced_welding_machine = Column(String(50))
    outsourced_welding_plan = Column(Integer, default=0)
    outsourced_welding_actual_plan = Column(Integer, default=0)
    outsourced_welding_actual_plan_trend = Column(Integer, default=0)
    # 溶接前検査
    pre_welding_inspection_carry_over = Column(Integer, default=0)
    pre_welding_inspection_actual = Column(Integer, default=0)
    pre_welding_inspection_defect = Column(Integer, default=0)
    pre_welding_inspection_scrap = Column(Integer, default=0)
    pre_welding_inspection_on_hold = Column(Integer, default=0)
    pre_welding_inspection_inventory = Column(Integer, default=0)
    pre_welding_inspection_trend = Column(Integer, default=0)
    # 外注支給前
    pre_inspection_carry_over = Column(Integer, default=0)
    pre_inspection_actual = Column(Integer, default=0)
    pre_inspection_scrap = Column(Integer, default=0)
    pre_inspection_inventory = Column(Integer, default=0)
    pre_inspection_trend = Column(Integer, default=0)
    # 外注検査前
    pre_outsourcing_carry_over = Column(Integer, default=0)
    pre_outsourcing_actual = Column(Integer, default=0)
    pre_outsourcing_scrap = Column(Integer, default=0)
    pre_outsourcing_inventory = Column(Integer, default=0)
    pre_outsourcing_trend = Column(Integer, default=0)


class LotForecastAttribution(Base):
    """管理コード → 日内示归属"""
    __tablename__ = "lot_forecast_attribution"

    id = Column(Integer, primary_key=True, autoincrement=True)
    management_code = Column(String(100))
    aps_batch_plan_id = Column(Integer)
    instruction_plan_id = Column(Integer)
    product_cd = Column(String(50), nullable=False)
    canonical_product_cd = Column(String(50), nullable=False)
    demand_product_cd = Column(String(50))
    destination_cd = Column(String(50))
    process_key = Column(String(32), nullable=False)
    source_date = Column(Date)
    forecast_attribution_date = Column(Date)
    attributed_qty = Column(Integer, nullable=False, default=0)
    method = Column(String(32), nullable=False, default="FIFO_DEMAND")
    allocation_rule = Column(String(32))
    attribution_mode = Column(String(16), nullable=False, default="PLAN")
    confidence = Column(String(16), nullable=False, default="HIGH")
    source_entity = Column(String(32))
    source_entity_id = Column(Integer)
    run_id = Column(String(64), nullable=False)
    is_current = Column(Boolean, nullable=False, default=True)
    computed_at = Column(DateTime, server_default=func.now())


class LotProcessStatusOverride(Base):
    """管理コードの切断完了・成型完了手動指定（帰属再計算と独立）"""
    __tablename__ = "lot_process_status_override"

    id = Column(Integer, primary_key=True, autoincrement=True)
    management_code = Column(String(100), nullable=False, unique=True)
    aps_batch_plan_id = Column(Integer)
    cutting_completed = Column(Boolean)
    molding_completed = Column(Boolean)
    remark = Column(String(500))
    updated_by = Column(Integer)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
