<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '経費区分・規程'
const apiBase = '/api/fin/expense/expense-policy-rule'
const columns: FinColumn[] = [{"prop": "category_code", "label": "経費区分"}, {"prop": "name", "label": "名称"}, {"prop": "max_amount", "label": "上限金額"}, {"prop": "requires_receipt", "label": "領収書必須"}, {"prop": "remarks", "label": "備考"}]
const fields: FinField[] = [{"prop": "category_code", "label": "経費区分", "type": "text", "required": false}, {"prop": "name", "label": "名称", "type": "text", "required": false}, {"prop": "max_amount", "label": "上限金額", "type": "number", "required": false}, {"prop": "requires_receipt", "label": "領収書必須", "type": "switch", "required": false}, {"prop": "remarks", "label": "備考", "type": "text", "required": false}]
</script>
