<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '経費申請'
const apiBase = '/api/fin/expense/expense-application'
const columns: FinColumn[] = [{"prop": "application_no", "label": "申請番号"}, {"prop": "employee_id", "label": "申請者"}, {"prop": "employee_name", "label": "employee name"}, {"prop": "applied_date", "label": "申請日"}, {"prop": "title", "label": "件名"}, {"prop": "total_amount", "label": "total amount"}, {"prop": "status", "label": "ステータス"}, {"prop": "approver_id", "label": "承認者"}]
const fields: FinField[] = [{"prop": "application_no", "label": "申請番号", "type": "text", "required": false}, {"prop": "employee_id", "label": "申請者", "type": "number", "required": false}, {"prop": "employee_name", "label": "employee name", "type": "text", "required": false}, {"prop": "applied_date", "label": "申請日", "type": "date", "required": true}, {"prop": "title", "label": "件名", "type": "text", "required": false}, {"prop": "total_amount", "label": "total amount", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}, {"prop": "approver_id", "label": "承認者", "type": "number", "required": false}, {"prop": "approved_at", "label": "approved at", "type": "datetime", "required": false}]
</script>
