<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinWorkflowPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinWorkflowPage from '@/views/fin/components/FinWorkflowPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '承認'
const apiBase = '/api/fin/expense/expense-application'
const columns: FinColumn[] = [{"prop": "application_no", "label": "申請番号"}, {"prop": "employee_id", "label": "申請者"}, {"prop": "employee_name", "label": "employee name"}, {"prop": "applied_date", "label": "申請日"}, {"prop": "title", "label": "件名"}, {"prop": "total_amount", "label": "total amount"}, {"prop": "status", "label": "ステータス"}, {"prop": "approver_id", "label": "承認者"}]
</script>
