<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinBatchPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinBatchPage from '@/views/fin/components/FinBatchPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '振込データ'
const apiBase = '/api/fin/payroll/payroll-run'
const columns: FinColumn[] = [{"prop": "run_no", "label": "給与計算番号"}, {"prop": "target_month", "label": "対象年月"}, {"prop": "pay_date", "label": "支給日"}, {"prop": "status", "label": "ステータス"}, {"prop": "total_gross", "label": "総支給"}, {"prop": "total_deduction", "label": "総控除"}, {"prop": "total_net", "label": "差引支給"}]
</script>
