<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '支給控除項目'
const apiBase = '/api/fin/payroll/pay-item'
const columns: FinColumn[] = [{"prop": "code", "label": "コード"}, {"prop": "name", "label": "名称"}, {"prop": "item_type", "label": "item type"}, {"prop": "is_taxable", "label": "課税対象"}, {"prop": "account_code", "label": "仕訳科目"}, {"prop": "is_active", "label": "有効"}]
const fields: FinField[] = [{"prop": "code", "label": "コード", "type": "text", "required": true}, {"prop": "name", "label": "名称", "type": "text", "required": true}, {"prop": "item_type", "label": "item type", "type": "text", "required": false}, {"prop": "is_taxable", "label": "課税対象", "type": "switch", "required": false}, {"prop": "account_code", "label": "仕訳科目", "type": "text", "required": false}, {"prop": "is_active", "label": "有効", "type": "switch", "required": false}]
</script>
