<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinReportPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinReportPage from '@/views/fin/components/FinReportPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '給与明細'
const apiBase = '/api/fin/payroll/payroll-run-line'
const columns: FinColumn[] = [{"prop": "run_id", "label": "親ID"}, {"prop": "employee_id", "label": "employee"}, {"prop": "employee_name", "label": "employee name"}, {"prop": "gross_amount", "label": "総支給"}, {"prop": "deduction_amount", "label": "控除合計"}, {"prop": "net_amount", "label": "差引支給"}, {"prop": "detail_json", "label": "項目別明細"}]
</script>
