# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""連携（integration）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.integration import models as md
from app.modules.fin.integration import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.IntegrationExportLog, out_schema=sc.IntegrationExportLogOut, create_schema=sc.IntegrationExportLogCreate, update_schema=sc.IntegrationExportLogUpdate, resource='integration-export-log', search_fields=['file_name'], order_by='created_at desc', label='IntegrationExportLog'))

__all__ = ['router']  # entities: IntegrationExportLog
