# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""連携（integration）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class IntegrationExportLogCreate(BaseModel):
    export_type: Optional[str] = None
    target_period: Optional[str] = None
    record_count: Optional[int] = None
    file_name: Optional[str] = None
    status: Optional[str] = None
    message: Optional[str] = None


class IntegrationExportLogUpdate(IntegrationExportLogCreate):
    pass


class IntegrationExportLogOut(IntegrationExportLogCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class IntegrationExportLogPage(BaseModel):
    items: List[IntegrationExportLogOut]
    total: int
    page: int
    page_size: int
    pages: int

