<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinReportPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinReportPage from '@/views/fin/components/FinReportPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '買掛年齢表'
const apiBase = '/api/fin/payables/ap-bill'
const columns: FinColumn[] = [{"prop": "bill_no", "label": "仕入請求番号"}, {"prop": "partner_id", "label": "仕入先"}, {"prop": "partner_name", "label": "partner name"}, {"prop": "bill_date", "label": "請求日"}, {"prop": "due_date", "label": "支払期限"}, {"prop": "subtotal", "label": "subtotal"}, {"prop": "tax_amount", "label": "tax amount"}, {"prop": "total_amount", "label": "total amount"}, {"prop": "paid_amount", "label": "paid amount"}, {"prop": "status", "label": "ステータス"}]
</script>
