<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '仕入請求'
const apiBase = '/api/fin/payables/ap-bill'
const columns: FinColumn[] = [{"prop": "bill_no", "label": "仕入請求番号"}, {"prop": "partner_id", "label": "仕入先"}, {"prop": "partner_name", "label": "partner name"}, {"prop": "bill_date", "label": "請求日"}, {"prop": "due_date", "label": "支払期限"}, {"prop": "subtotal", "label": "subtotal"}, {"prop": "tax_amount", "label": "tax amount"}, {"prop": "total_amount", "label": "total amount"}]
const fields: FinField[] = [{"prop": "bill_no", "label": "仕入請求番号", "type": "text", "required": false}, {"prop": "partner_id", "label": "仕入先", "type": "number", "required": false}, {"prop": "partner_name", "label": "partner name", "type": "text", "required": false}, {"prop": "bill_date", "label": "請求日", "type": "date", "required": true}, {"prop": "due_date", "label": "支払期限", "type": "date", "required": false}, {"prop": "subtotal", "label": "subtotal", "type": "number", "required": false}, {"prop": "tax_amount", "label": "tax amount", "type": "number", "required": false}, {"prop": "total_amount", "label": "total amount", "type": "number", "required": false}, {"prop": "paid_amount", "label": "paid amount", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}]
</script>
