<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '支払'
const apiBase = '/api/fin/payables/ap-payment'
const columns: FinColumn[] = [{"prop": "payment_no", "label": "支払番号"}, {"prop": "partner_id", "label": "partner"}, {"prop": "payment_date", "label": "支払日"}, {"prop": "amount", "label": "金額"}, {"prop": "method", "label": "method"}, {"prop": "bank_account_id", "label": "出金口座"}, {"prop": "status", "label": "ステータス"}]
const fields: FinField[] = [{"prop": "payment_no", "label": "支払番号", "type": "text", "required": false}, {"prop": "partner_id", "label": "partner", "type": "number", "required": false}, {"prop": "payment_date", "label": "支払日", "type": "date", "required": true}, {"prop": "amount", "label": "金額", "type": "number", "required": false}, {"prop": "method", "label": "method", "type": "text", "required": false}, {"prop": "bank_account_id", "label": "出金口座", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}]
</script>
