# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""給与（payroll）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.payroll import models as md
from app.modules.fin.payroll import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.PayItem, out_schema=sc.PayItemOut, create_schema=sc.PayItemCreate, update_schema=sc.PayItemUpdate, resource='pay-item', search_fields=['name'], order_by='id desc', label='PayItem'))
router.include_router(build_crud_router(model=md.EmployeePayItem, out_schema=sc.EmployeePayItemOut, create_schema=sc.EmployeePayItemCreate, update_schema=sc.EmployeePayItemUpdate, resource='employee-pay-item', search_fields=[], order_by='id desc', label='EmployeePayItem'))
router.include_router(build_crud_router(model=md.SocialInsuranceProfile, out_schema=sc.SocialInsuranceProfileOut, create_schema=sc.SocialInsuranceProfileCreate, update_schema=sc.SocialInsuranceProfileUpdate, resource='social-insurance-profile', search_fields=[], order_by='id desc', label='SocialInsuranceProfile'))
router.include_router(build_crud_router(model=md.WithholdingTaxTable, out_schema=sc.WithholdingTaxTableOut, create_schema=sc.WithholdingTaxTableCreate, update_schema=sc.WithholdingTaxTableUpdate, resource='withholding-tax-table', search_fields=[], order_by='id desc', label='WithholdingTaxTable'))
router.include_router(build_crud_router(model=md.PayrollRun, out_schema=sc.PayrollRunOut, create_schema=sc.PayrollRunCreate, update_schema=sc.PayrollRunUpdate, resource='payroll-run', search_fields=['run_no'], order_by='target_month desc', label='PayrollRun'))
router.include_router(build_crud_router(model=md.PayrollRunLine, out_schema=sc.PayrollRunLineOut, create_schema=sc.PayrollRunLineCreate, update_schema=sc.PayrollRunLineUpdate, resource='payroll-run-line', search_fields=['employee_name'], order_by='id desc', label='PayrollRunLine'))

__all__ = ['router']  # entities: PayItem, EmployeePayItem, SocialInsuranceProfile, WithholdingTaxTable, PayrollRun, PayrollRunLine
