# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""給与（payroll）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class PayItem(Base):
    __tablename__ = "fin_pay_item"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(30), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    item_type = Column(String(20), default="earning")
    is_taxable = Column(Boolean, default=True)
    account_code = Column(String(50))
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class EmployeePayItem(Base):
    __tablename__ = "fin_employee_pay_item"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True)
    pay_item_code = Column(String(30))
    amount = Column(Numeric(18, 2), default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class SocialInsuranceProfile(Base):
    __tablename__ = "fin_social_insurance_profile"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True, unique=True)
    health_insurance_grade = Column(Integer)
    pension_grade = Column(Integer)
    standard_monthly = Column(Numeric(18, 2), default=0)
    dependents = Column(Integer, default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class WithholdingTaxTable(Base):
    __tablename__ = "fin_withholding_tax_table"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    version = Column(String(20), index=True)
    min_amount = Column(Numeric(18, 2), default=0)
    max_amount = Column(Numeric(18, 2))
    dependents = Column(Integer, default=0)
    tax_amount = Column(Numeric(18, 2), default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class PayrollRun(Base):
    __tablename__ = "fin_payroll_run"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    run_no = Column(String(40), index=True)
    target_month = Column(String(7), nullable=False, index=True)
    pay_date = Column(Date)
    status = Column(String(20), index=True, default="draft")
    total_gross = Column(Numeric(18, 2), default=0)
    total_deduction = Column(Numeric(18, 2), default=0)
    total_net = Column(Numeric(18, 2), default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class PayrollRunLine(Base):
    __tablename__ = "fin_payroll_run_line"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    run_id = Column(BigInteger, ForeignKey("fin_payroll_run.id", ondelete="CASCADE"), nullable=False)
    employee_id = Column(Integer, index=True)
    employee_name = Column(String(100))
    gross_amount = Column(Numeric(18, 2), default=0)
    deduction_amount = Column(Numeric(18, 2), default=0)
    net_amount = Column(Numeric(18, 2), default=0)
    detail_json = Column(Text)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

