# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""給与（payroll）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class PayItemCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    item_type: Optional[str] = None
    is_taxable: Optional[bool] = None
    account_code: Optional[str] = None
    is_active: Optional[bool] = None


class PayItemUpdate(PayItemCreate):
    pass


class PayItemOut(PayItemCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class PayItemPage(BaseModel):
    items: List[PayItemOut]
    total: int
    page: int
    page_size: int
    pages: int


class EmployeePayItemCreate(BaseModel):
    employee_id: Optional[int] = None
    pay_item_code: Optional[str] = None
    amount: Optional[float] = None


class EmployeePayItemUpdate(EmployeePayItemCreate):
    pass


class EmployeePayItemOut(EmployeePayItemCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class EmployeePayItemPage(BaseModel):
    items: List[EmployeePayItemOut]
    total: int
    page: int
    page_size: int
    pages: int


class SocialInsuranceProfileCreate(BaseModel):
    employee_id: Optional[int] = None
    health_insurance_grade: Optional[int] = None
    pension_grade: Optional[int] = None
    standard_monthly: Optional[float] = None
    dependents: Optional[int] = None


class SocialInsuranceProfileUpdate(SocialInsuranceProfileCreate):
    pass


class SocialInsuranceProfileOut(SocialInsuranceProfileCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class SocialInsuranceProfilePage(BaseModel):
    items: List[SocialInsuranceProfileOut]
    total: int
    page: int
    page_size: int
    pages: int


class WithholdingTaxTableCreate(BaseModel):
    version: Optional[str] = None
    min_amount: Optional[float] = None
    max_amount: Optional[float] = None
    dependents: Optional[int] = None
    tax_amount: Optional[float] = None


class WithholdingTaxTableUpdate(WithholdingTaxTableCreate):
    pass


class WithholdingTaxTableOut(WithholdingTaxTableCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class WithholdingTaxTablePage(BaseModel):
    items: List[WithholdingTaxTableOut]
    total: int
    page: int
    page_size: int
    pages: int


class PayrollRunCreate(BaseModel):
    run_no: Optional[str] = None
    target_month: Optional[str] = None
    pay_date: Optional[date] = None
    status: Optional[str] = None
    total_gross: Optional[float] = None
    total_deduction: Optional[float] = None
    total_net: Optional[float] = None


class PayrollRunUpdate(PayrollRunCreate):
    pass


class PayrollRunOut(PayrollRunCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class PayrollRunPage(BaseModel):
    items: List[PayrollRunOut]
    total: int
    page: int
    page_size: int
    pages: int


class PayrollRunLineCreate(BaseModel):
    run_id: Optional[int] = None
    employee_id: Optional[int] = None
    employee_name: Optional[str] = None
    gross_amount: Optional[float] = None
    deduction_amount: Optional[float] = None
    net_amount: Optional[float] = None
    detail_json: Optional[str] = None


class PayrollRunLineUpdate(PayrollRunLineCreate):
    pass


class PayrollRunLineOut(PayrollRunLineCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class PayrollRunLinePage(BaseModel):
    items: List[PayrollRunLineOut]
    total: int
    page: int
    page_size: int
    pages: int

