# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""共通（common）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.common import models as md
from app.modules.fin.common import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.Attachment, out_schema=sc.AttachmentOut, create_schema=sc.AttachmentCreate, update_schema=sc.AttachmentUpdate, resource='attachment', search_fields=['file_name'], order_by='created_at desc', label='Attachment'))

__all__ = ['router']  # entities: Attachment
