# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND
"""FIN 汎用 CRUD ルータービルダー。

manifest 由来の各エンティティに対し、一覧（ページング・等値フィルタ・キーワード検索）、
取得、作成、更新、削除の標準 REST を提供する。中核業務ロジックは各 services/ に実装する。
"""
from typing import List, Optional, Type

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from sqlalchemy import select, func, delete as sa_delete
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.modules.auth.api import verify_token_and_get_user
from app.modules.auth.models import User

RESERVED = {"page", "page_size", "q", "order_by"}


def _coerce(value: str):
    if value in ("true", "false"):
        return value == "true"
    if value.lstrip("-").isdigit():
        return int(value)
    return value


def _apply_order(stmt, model, order_by: Optional[str]):
    if not order_by:
        return stmt.order_by(model.id.desc())
    parts = order_by.split()
    col = getattr(model, parts[0], None)
    if col is None:
        return stmt.order_by(model.id.desc())
    if len(parts) > 1 and parts[1].lower() == "desc":
        return stmt.order_by(col.desc())
    return stmt.order_by(col.asc())


def build_crud_router(
    *,
    model: Type,
    out_schema: Type,
    create_schema: Type,
    update_schema: Type,
    resource: str,
    search_fields: Optional[List[str]] = None,
    order_by: Optional[str] = None,
    label: str = "",
) -> APIRouter:
    router = APIRouter()
    search_fields = search_fields or []

    @router.get(f"/{resource}", summary=f"{label} 一覧")
    async def list_items(
        request: Request,
        page: int = Query(1, ge=1),
        page_size: int = Query(20, ge=1, le=500),
        q: Optional[str] = None,
        order: Optional[str] = Query(None, alias="order_by"),
        db: AsyncSession = Depends(get_db),
        _user: User = Depends(verify_token_and_get_user),
    ):
        stmt = select(model)
        for key, val in request.query_params.items():
            if key in RESERVED:
                continue
            col = getattr(model, key, None)
            if col is not None:
                stmt = stmt.where(col == _coerce(val))
        if q and search_fields:
            from sqlalchemy import or_
            conds = [getattr(model, f).like(f"%{q}%") for f in search_fields]
            stmt = stmt.where(or_(*conds))
        total = (await db.execute(select(func.count()).select_from(stmt.subquery()))).scalar() or 0
        stmt = _apply_order(stmt, model, order or order_by)
        stmt = stmt.offset((page - 1) * page_size).limit(page_size)
        rows = (await db.execute(stmt)).scalars().all()
        return {
            "items": [out_schema.model_validate(r) for r in rows],
            "total": total,
            "page": page,
            "page_size": page_size,
            "pages": (total + page_size - 1) // page_size,
        }

    @router.get(f"/{resource}/{{item_id}}", summary=f"{label} 取得")
    async def get_item(
        item_id: int,
        db: AsyncSession = Depends(get_db),
        _user: User = Depends(verify_token_and_get_user),
    ):
        obj = await db.get(model, item_id)
        if obj is None:
            raise HTTPException(status_code=404, detail=f"{label} が見つかりません")
        return out_schema.model_validate(obj)

    @router.post(f"/{resource}", summary=f"{label} 作成")
    async def create_item(
        payload: create_schema,  # type: ignore
        db: AsyncSession = Depends(get_db),
        user: User = Depends(verify_token_and_get_user),
    ):
        data = payload.model_dump(exclude_unset=True)
        obj = model(**data)
        if hasattr(obj, "created_by"):
            obj.created_by = user.username
            obj.updated_by = user.username
        db.add(obj)
        await db.commit()
        await db.refresh(obj)
        return out_schema.model_validate(obj)

    @router.put(f"/{resource}/{{item_id}}", summary=f"{label} 更新")
    async def update_item(
        item_id: int,
        payload: update_schema,  # type: ignore
        db: AsyncSession = Depends(get_db),
        user: User = Depends(verify_token_and_get_user),
    ):
        obj = await db.get(model, item_id)
        if obj is None:
            raise HTTPException(status_code=404, detail=f"{label} が見つかりません")
        for key, val in payload.model_dump(exclude_unset=True).items():
            setattr(obj, key, val)
        if hasattr(obj, "updated_by"):
            obj.updated_by = user.username
        await db.commit()
        await db.refresh(obj)
        return out_schema.model_validate(obj)

    @router.delete(f"/{resource}/{{item_id}}", summary=f"{label} 削除")
    async def delete_item(
        item_id: int,
        db: AsyncSession = Depends(get_db),
        _user: User = Depends(verify_token_and_get_user),
    ):
        obj = await db.get(model, item_id)
        if obj is None:
            raise HTTPException(status_code=404, detail=f"{label} が見つかりません")
        await db.execute(sa_delete(model).where(model.id == item_id))
        await db.commit()
        return {"message": "削除しました", "id": item_id}

    return router
