# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""共通（common）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class AttachmentCreate(BaseModel):
    ref_type: Optional[str] = None
    ref_id: Optional[int] = None
    file_name: Optional[str] = None
    file_path: Optional[str] = None
    content_type: Optional[str] = None
    file_size: Optional[int] = None


class AttachmentUpdate(AttachmentCreate):
    pass


class AttachmentOut(AttachmentCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class AttachmentPage(BaseModel):
    items: List[AttachmentOut]
    total: int
    page: int
    page_size: int
    pages: int

