# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""経費精算（expense）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.expense import models as md
from app.modules.fin.expense import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.ExpenseCategory, out_schema=sc.ExpenseCategoryOut, create_schema=sc.ExpenseCategoryCreate, update_schema=sc.ExpenseCategoryUpdate, resource='expense-category', search_fields=['name'], order_by='id desc', label='ExpenseCategory'))
router.include_router(build_crud_router(model=md.ExpensePolicyRule, out_schema=sc.ExpensePolicyRuleOut, create_schema=sc.ExpensePolicyRuleCreate, update_schema=sc.ExpensePolicyRuleUpdate, resource='expense-policy-rule', search_fields=['name'], order_by='id desc', label='ExpensePolicyRule'))
router.include_router(build_crud_router(model=md.ExpenseApplication, out_schema=sc.ExpenseApplicationOut, create_schema=sc.ExpenseApplicationCreate, update_schema=sc.ExpenseApplicationUpdate, resource='expense-application', search_fields=['application_no', 'employee_name', 'title'], order_by='applied_date desc', label='ExpenseApplication'))
router.include_router(build_crud_router(model=md.ExpenseLine, out_schema=sc.ExpenseLineOut, create_schema=sc.ExpenseLineCreate, update_schema=sc.ExpenseLineUpdate, resource='expense-line', search_fields=['description'], order_by='id desc', label='ExpenseLine'))

__all__ = ['router']  # entities: ExpenseCategory, ExpensePolicyRule, ExpenseApplication, ExpenseLine
