# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""経費精算（expense）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class ExpenseCategory(Base):
    __tablename__ = "fin_expense_category"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(30), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    account_code = Column(String(50))
    tax_code = Column(String(20))
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ExpensePolicyRule(Base):
    __tablename__ = "fin_expense_policy_rule"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    category_code = Column(String(30), index=True)
    name = Column(String(100))
    max_amount = Column(Numeric(18, 2))
    requires_receipt = Column(Boolean, default=True)
    remarks = Column(String(255))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ExpenseApplication(Base):
    __tablename__ = "fin_expense_application"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    application_no = Column(String(40), index=True)
    employee_id = Column(Integer, index=True)
    employee_name = Column(String(100))
    applied_date = Column(Date, nullable=False)
    title = Column(String(200))
    total_amount = Column(Numeric(18, 2), default=0)
    status = Column(String(20), index=True, default="draft")
    approver_id = Column(Integer)
    approved_at = Column(DateTime)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ExpenseLine(Base):
    __tablename__ = "fin_expense_line"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    application_id = Column(BigInteger, ForeignKey("fin_expense_application.id", ondelete="CASCADE"), nullable=False)
    line_no = Column(Integer, default=1)
    expense_date = Column(Date)
    category_code = Column(String(30))
    description = Column(String(255))
    amount = Column(Numeric(18, 2), default=0)
    tax_code = Column(String(20))
    has_receipt = Column(Boolean, default=False)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

