# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""経費精算（expense）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class ExpenseCategoryCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    account_code: Optional[str] = None
    tax_code: Optional[str] = None
    is_active: Optional[bool] = None


class ExpenseCategoryUpdate(ExpenseCategoryCreate):
    pass


class ExpenseCategoryOut(ExpenseCategoryCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ExpenseCategoryPage(BaseModel):
    items: List[ExpenseCategoryOut]
    total: int
    page: int
    page_size: int
    pages: int


class ExpensePolicyRuleCreate(BaseModel):
    category_code: Optional[str] = None
    name: Optional[str] = None
    max_amount: Optional[float] = None
    requires_receipt: Optional[bool] = None
    remarks: Optional[str] = None


class ExpensePolicyRuleUpdate(ExpensePolicyRuleCreate):
    pass


class ExpensePolicyRuleOut(ExpensePolicyRuleCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ExpensePolicyRulePage(BaseModel):
    items: List[ExpensePolicyRuleOut]
    total: int
    page: int
    page_size: int
    pages: int


class ExpenseApplicationCreate(BaseModel):
    application_no: Optional[str] = None
    employee_id: Optional[int] = None
    employee_name: Optional[str] = None
    applied_date: Optional[date] = None
    title: Optional[str] = None
    total_amount: Optional[float] = None
    status: Optional[str] = None
    approver_id: Optional[int] = None
    approved_at: Optional[datetime] = None


class ExpenseApplicationUpdate(ExpenseApplicationCreate):
    pass


class ExpenseApplicationOut(ExpenseApplicationCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ExpenseApplicationPage(BaseModel):
    items: List[ExpenseApplicationOut]
    total: int
    page: int
    page_size: int
    pages: int


class ExpenseLineCreate(BaseModel):
    application_id: Optional[int] = None
    line_no: Optional[int] = None
    expense_date: Optional[date] = None
    category_code: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[float] = None
    tax_code: Optional[str] = None
    has_receipt: Optional[bool] = None


class ExpenseLineUpdate(ExpenseLineCreate):
    pass


class ExpenseLineOut(ExpenseLineCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ExpenseLinePage(BaseModel):
    items: List[ExpenseLineOut]
    total: int
    page: int
    page_size: int
    pages: int

