-- 製品工程BOM (Product Process BOM)
CREATE TABLE IF NOT EXISTS `product_process_bom` (
  `product_cd` int NOT NULL COMMENT '製品CD',
  `product_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '製品名',
  `min_stock_days` int NULL DEFAULT NULL COMMENT '最低在庫日数',
  `safety_stock_days` int NULL DEFAULT NULL COMMENT '安全在庫日数',
  `material_process` tinyint(1) NULL DEFAULT NULL COMMENT '材料 (工程)',
  `material_process_lt` int NULL DEFAULT NULL COMMENT '材料工程LT',
  `cuting_process` tinyint(1) NULL DEFAULT NULL COMMENT '切断 (工程)',
  `cuting_process_lt` int NULL DEFAULT NULL COMMENT '切断工程LT',
  `chamfering_process` tinyint(1) NULL DEFAULT NULL COMMENT '面取 (工程)',
  `chamfering_process_lt` int NULL DEFAULT NULL COMMENT '面取工程LT',
  `swaging_process` tinyint(1) NULL DEFAULT NULL COMMENT 'SW (工程)',
  `swaging_process_lt` int NULL DEFAULT NULL COMMENT 'SW工程LT',
  `forming_process` tinyint(1) NULL DEFAULT NULL COMMENT '成型 (工程)',
  `forming_process_lt` int NULL DEFAULT NULL COMMENT '成型工程LT',
  `plating_process` tinyint(1) NULL DEFAULT NULL COMMENT 'メッキ (工程)',
  `plating_process_lt` int NULL DEFAULT NULL COMMENT 'メッキ工程LT',
  `outsourced_plating_process` tinyint(1) NULL DEFAULT NULL COMMENT '外注メッキ (工程)',
  `outsourced_plating_process_lt` int NULL DEFAULT NULL COMMENT '外注メッキ工程LT',
  `welding_process` tinyint(1) NULL DEFAULT NULL COMMENT '溶接 (工程)',
  `welding_process_lt` int NULL DEFAULT NULL COMMENT '溶接工程LT',
  `outsourced_welding_process` tinyint(1) NULL DEFAULT NULL COMMENT '外注溶接 (工程)',
  `outsourced_welding_process_lt` int NULL DEFAULT NULL COMMENT '外注溶接工程LT',
  `inspection_process` tinyint(1) NULL DEFAULT NULL COMMENT '検査 (工程)',
  `inspection_process_lt` int NULL DEFAULT NULL COMMENT '検査工程LT',
  `outsourced_warehouse_process` tinyint(1) NULL DEFAULT NULL COMMENT '外注倉庫 (工程)',
  `outsourced_warehouse_process_lt` int NULL DEFAULT NULL COMMENT '外注検査工程LT',
  `pre_plating_welding` tinyint(1) NULL DEFAULT NULL COMMENT 'メッキ前溶接 (工程)',
  `post_inspection_welding` tinyint(1) NULL DEFAULT NULL COMMENT '検査後溶接 (工程)',
  `post_inspection_welding_lt` int NULL DEFAULT NULL COMMENT '検査後溶接工程LT',
  `is_discontinued` tinyint(1) NULL DEFAULT NULL COMMENT '終息',
  PRIMARY KEY (`product_cd`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '製品工程BOM (Product Process BOM)' ROW_FORMAT = Dynamic;
