-- 切断計画作成：計画Run、明細、時間帯スライス

CREATE TABLE IF NOT EXISTS `cutting_plan_runs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `production_month` date NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `generated_at` datetime NULL DEFAULT NULL,
  `published_at` datetime NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cutting_plan_runs_month` (`production_month`),
  KEY `idx_cutting_plan_runs_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='切断計画Run';

CREATE TABLE IF NOT EXISTS `cutting_plan_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_id` int NOT NULL,
  `instruction_plan_id` int NULL DEFAULT NULL,
  `source_management_code` varchar(100) NULL DEFAULT NULL,
  `product_cd` varchar(50) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `material_name` varchar(255) NULL DEFAULT NULL,
  `production_line` varchar(50) NULL DEFAULT NULL,
  `planned_quantity` int NOT NULL DEFAULT 0,
  `production_lot_size` int NULL DEFAULT NULL,
  `lot_number` varchar(100) NULL DEFAULT NULL,
  `take_count` int NULL DEFAULT NULL,
  `cutting_length` decimal(10,2) NULL DEFAULT NULL,
  `assigned_machine_id` int NULL DEFAULT NULL,
  `assigned_machine` varchar(100) NULL DEFAULT NULL,
  `sequence_no` int NOT NULL DEFAULT 0,
  `planned_day` date NULL DEFAULT NULL,
  `planned_start` datetime NULL DEFAULT NULL,
  `planned_end` datetime NULL DEFAULT NULL,
  `estimated_minutes` decimal(10,2) NOT NULL DEFAULT 0,
  `efficiency_rate` decimal(10,2) NULL DEFAULT NULL,
  `setup_time_min` int NULL DEFAULT NULL,
  `is_locked` tinyint(1) NOT NULL DEFAULT 0,
  `publish_status` varchar(20) NOT NULL DEFAULT 'PLANNED',
  `published_cutting_id` int NULL DEFAULT NULL,
  `actual_quantity` int NOT NULL DEFAULT 0,
  `completion_status` varchar(20) NOT NULL DEFAULT 'PLANNED',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_cutting_plan_items_run` (`run_id`),
  KEY `idx_cutting_plan_items_machine_seq` (`run_id`, `assigned_machine_id`, `sequence_no`),
  KEY `idx_cutting_plan_items_day` (`run_id`, `planned_day`),
  KEY `idx_cutting_plan_items_instruction` (`instruction_plan_id`),
  KEY `idx_cutting_plan_items_management_code` (`source_management_code`),
  KEY `idx_cutting_plan_items_published_cutting` (`published_cutting_id`),
  CONSTRAINT `fk_cutting_plan_items_run` FOREIGN KEY (`run_id`) REFERENCES `cutting_plan_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='切断計画明細';

CREATE TABLE IF NOT EXISTS `cutting_plan_slices` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_id` int NOT NULL,
  `item_id` bigint NOT NULL,
  `machine_id` int NULL DEFAULT NULL,
  `assigned_machine` varchar(100) NULL DEFAULT NULL,
  `work_date` date NOT NULL,
  `period_start` time NOT NULL,
  `period_end` time NOT NULL,
  `planned_qty` int NOT NULL DEFAULT 0,
  `sort_order` int NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_cutting_plan_slices_run_day` (`run_id`, `work_date`),
  KEY `idx_cutting_plan_slices_item` (`item_id`),
  KEY `idx_cutting_plan_slices_machine` (`machine_id`, `work_date`),
  CONSTRAINT `fk_cutting_plan_slices_run` FOREIGN KEY (`run_id`) REFERENCES `cutting_plan_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cutting_plan_slices_item` FOREIGN KEY (`item_id`) REFERENCES `cutting_plan_items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='切断計画時間帯スライス';
