-- @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

-- =============================================================================
-- FIN（経理・人事）全量スキーマ  (manifest version 1)
-- 実行: 02_baseline_full_schema.sql の後。新規DBは bootstrap_full_database.py 推奨。
-- =============================================================================
SET NAMES utf8mb4;

-- ------- ドメイン: accounting（会計） -------
CREATE TABLE IF NOT EXISTS `fin_fiscal_year` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(20) NOT NULL COMMENT '会計年度コード',
  `name` VARCHAR(50) NOT NULL COMMENT '名称',
  `start_date` DATE NOT NULL COMMENT '期首',
  `end_date` DATE NOT NULL COMMENT '期末',
  `status` VARCHAR(20) DEFAULT 'open' COMMENT '状態（open/closed）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_fiscal_year_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会計年度';

CREATE TABLE IF NOT EXISTS `fin_accounting_period` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `fiscal_year_id` BIGINT COMMENT '会計年度',
  `year_month` VARCHAR(7) NOT NULL COMMENT '年月（YYYY-MM）',
  `status` VARCHAR(20) DEFAULT 'open' COMMENT '状態（open/closing/closed）',
  `closed_at` DATETIME COMMENT '締め日時',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_accounting_period_fiscal_year_id` (`fiscal_year_id`),
  KEY `idx_fin_accounting_period_year_month` (`year_month`),
  CONSTRAINT `fk_fin_accounting_period_fiscal_year_id` FOREIGN KEY (`fiscal_year_id`) REFERENCES `fin_fiscal_year` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会計期間（月次）';

CREATE TABLE IF NOT EXISTS `fin_journal_entry` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `journal_no` VARCHAR(40) COMMENT '仕訳番号',
  `entry_date` DATE NOT NULL COMMENT '仕訳日',
  `period_ym` VARCHAR(7) COMMENT '計上年月',
  `entry_type` VARCHAR(30) DEFAULT 'manual' COMMENT '種別（手動/売上/仕入/移動/製造/減価償却/給与）',
  `description` VARCHAR(255) COMMENT '摘要',
  `total_debit` DECIMAL(18, 2) DEFAULT 0 COMMENT '借方合計',
  `total_credit` DECIMAL(18, 2) DEFAULT 0 COMMENT '貸方合計',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状態（下書き/転記済/取消）',
  `source_id` BIGINT COMMENT '仕訳ソースID',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_journal_entry_journal_no` (`journal_no`),
  KEY `idx_fin_journal_entry_entry_date` (`entry_date`),
  KEY `idx_fin_journal_entry_period_ym` (`period_ym`),
  KEY `idx_fin_journal_entry_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仕訳ヘッダ';

CREATE TABLE IF NOT EXISTS `fin_journal_line` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `entry_id` BIGINT NOT NULL COMMENT '親レコードID',
  `line_no` INT DEFAULT 1 COMMENT '行番号',
  `account_code` VARCHAR(50) COMMENT '勘定科目',
  `account_name` VARCHAR(100) COMMENT '科目名',
  `debit` DECIMAL(18, 2) DEFAULT 0 COMMENT '借方',
  `credit` DECIMAL(18, 2) DEFAULT 0 COMMENT '貸方',
  `tax_code` VARCHAR(20) COMMENT '税区分',
  `tax_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '消費税額',
  `department_code` VARCHAR(50) COMMENT '部門',
  `partner_id` INT COMMENT '取引先',
  `remarks` VARCHAR(255) COMMENT '備考',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_journal_line_entry_id` (`entry_id`),
  KEY `idx_fin_journal_line_account_code` (`account_code`),
  CONSTRAINT `fk_fin_journal_line_entry_id` FOREIGN KEY (`entry_id`) REFERENCES `fin_journal_entry` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仕訳明細';

CREATE TABLE IF NOT EXISTS `fin_journal_source` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `source_type` VARCHAR(40) NOT NULL COMMENT 'イベント種別（売上計上等）',
  `source_module` VARCHAR(30) COMMENT '連携元（ERP/経費/給与）',
  `source_ref` VARCHAR(100) COMMENT '元伝票番号またはID',
  `event_date` DATE COMMENT '事象日',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '金額',
  `payload_json` TEXT COMMENT '連携ペイロード',
  `status` VARCHAR(20) DEFAULT 'pending' COMMENT '状態（未生成/生成済/スキップ）',
  `journal_entry_id` BIGINT COMMENT '生成先仕訳ID',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_journal_source_source_type` (`source_type`),
  KEY `idx_fin_journal_source_source_ref` (`source_ref`),
  KEY `idx_fin_journal_source_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仕訳連携ソース';

-- ------- ドメイン: receivables（売上・請求） -------
CREATE TABLE IF NOT EXISTS `fin_ar_invoice` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `invoice_no` VARCHAR(40) COMMENT '請求番号',
  `partner_id` INT COMMENT '取引先',
  `partner_name` VARCHAR(200) COMMENT '取引先名',
  `invoice_date` DATE NOT NULL COMMENT '請求日',
  `due_date` DATE COMMENT '支払期限',
  `subtotal` DECIMAL(18, 2) DEFAULT 0 COMMENT '税抜',
  `tax_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '消費税',
  `total_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '税込合計',
  `paid_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '入金済',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状態（下書き/発行済/入金済/延滞）',
  `source_invoice_id` INT COMMENT 'ERP 請求書連携',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ar_invoice_invoice_no` (`invoice_no`),
  KEY `idx_fin_ar_invoice_partner_id` (`partner_id`),
  KEY `idx_fin_ar_invoice_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='売掛請求書';

CREATE TABLE IF NOT EXISTS `fin_ar_invoice_line` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `invoice_id` BIGINT NOT NULL COMMENT '親レコードID',
  `line_no` INT DEFAULT 1 COMMENT '行番号',
  `item_name` VARCHAR(200) COMMENT '品目',
  `quantity` DECIMAL(18, 4) DEFAULT 0 COMMENT '数量',
  `unit_price` DECIMAL(18, 4) DEFAULT 0 COMMENT '単価',
  `tax_code` VARCHAR(20) COMMENT '税区分コード',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '金額',
  `account_code` VARCHAR(50) COMMENT '売上科目',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ar_invoice_line_invoice_id` (`invoice_id`),
  CONSTRAINT `fk_fin_ar_invoice_line_invoice_id` FOREIGN KEY (`invoice_id`) REFERENCES `fin_ar_invoice` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='売掛請求明細';

CREATE TABLE IF NOT EXISTS `fin_ar_receipt` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `receipt_no` VARCHAR(40) COMMENT '入金番号',
  `partner_id` INT COMMENT '取引先ID',
  `receipt_date` DATE NOT NULL COMMENT '入金日',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '入金額',
  `method` VARCHAR(30) COMMENT '入金方法（振込/手形/現金）',
  `bank_account_id` INT COMMENT '入金口座',
  `status` VARCHAR(20) DEFAULT 'unmatched' COMMENT '状態（未消込/消込済）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ar_receipt_receipt_no` (`receipt_no`),
  KEY `idx_fin_ar_receipt_partner_id` (`partner_id`),
  KEY `idx_fin_ar_receipt_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='入金';

CREATE TABLE IF NOT EXISTS `fin_ar_receipt_allocation` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `receipt_id` BIGINT NOT NULL COMMENT '親レコードID',
  `invoice_id` BIGINT COMMENT '消込対象請求',
  `allocated_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '充当額',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ar_receipt_allocation_receipt_id` (`receipt_id`),
  KEY `idx_fin_ar_receipt_allocation_invoice_id` (`invoice_id`),
  CONSTRAINT `fk_fin_ar_receipt_allocation_receipt_id` FOREIGN KEY (`receipt_id`) REFERENCES `fin_ar_receipt` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='入金消込';

-- ------- ドメイン: payables（仕入・支払） -------
CREATE TABLE IF NOT EXISTS `fin_ap_bill` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `bill_no` VARCHAR(40) COMMENT '仕入請求番号',
  `partner_id` INT COMMENT '仕入先',
  `partner_name` VARCHAR(200) COMMENT '取引先名',
  `bill_date` DATE NOT NULL COMMENT '請求日',
  `due_date` DATE COMMENT '支払期限',
  `subtotal` DECIMAL(18, 2) DEFAULT 0 COMMENT '税抜金額',
  `tax_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '消費税額',
  `total_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '合計金額',
  `paid_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '支払済金額',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状態（下書き/確定/支払済）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ap_bill_bill_no` (`bill_no`),
  KEY `idx_fin_ap_bill_partner_id` (`partner_id`),
  KEY `idx_fin_ap_bill_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='買掛請求';

CREATE TABLE IF NOT EXISTS `fin_ap_bill_line` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `bill_id` BIGINT NOT NULL COMMENT '親レコードID',
  `line_no` INT DEFAULT 1 COMMENT '行番号',
  `item_name` VARCHAR(200) COMMENT '品目名',
  `quantity` DECIMAL(18, 4) DEFAULT 0 COMMENT '数量',
  `unit_price` DECIMAL(18, 4) DEFAULT 0 COMMENT '単価',
  `tax_code` VARCHAR(20) COMMENT '税区分コード',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '金額',
  `account_code` VARCHAR(50) COMMENT '値（費用/仕入科目）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ap_bill_line_bill_id` (`bill_id`),
  CONSTRAINT `fk_fin_ap_bill_line_bill_id` FOREIGN KEY (`bill_id`) REFERENCES `fin_ap_bill` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='買掛請求明細';

CREATE TABLE IF NOT EXISTS `fin_ap_payment` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `payment_no` VARCHAR(40) COMMENT '支払番号',
  `partner_id` INT COMMENT '取引先ID',
  `payment_date` DATE NOT NULL COMMENT '支払日',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '金額',
  `method` VARCHAR(30) COMMENT '支払方法（振込/手形）',
  `bank_account_id` INT COMMENT '出金口座',
  `status` VARCHAR(20) DEFAULT 'scheduled' COMMENT '状態（予定/支払済）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ap_payment_payment_no` (`payment_no`),
  KEY `idx_fin_ap_payment_partner_id` (`partner_id`),
  KEY `idx_fin_ap_payment_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支払';

CREATE TABLE IF NOT EXISTS `fin_ap_payment_allocation` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `payment_id` BIGINT NOT NULL COMMENT '親レコードID',
  `bill_id` BIGINT COMMENT '消込対象仕入請求',
  `allocated_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '充当金額',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_ap_payment_allocation_payment_id` (`payment_id`),
  KEY `idx_fin_ap_payment_allocation_bill_id` (`bill_id`),
  CONSTRAINT `fk_fin_ap_payment_allocation_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `fin_ap_payment` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支払消込';

-- ------- ドメイン: expense（経費精算） -------
CREATE TABLE IF NOT EXISTS `fin_expense_category` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(30) NOT NULL COMMENT '経費区分コード',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `account_code` VARCHAR(50) COMMENT '対応勘定科目',
  `tax_code` VARCHAR(20) COMMENT '税区分コード',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_expense_category_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='経費区分';

CREATE TABLE IF NOT EXISTS `fin_expense_policy_rule` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `category_code` VARCHAR(30) COMMENT '経費区分',
  `name` VARCHAR(100) COMMENT 'ルール名',
  `max_amount` DECIMAL(18, 2) COMMENT '上限金額',
  `requires_receipt` TINYINT(1) DEFAULT 1 COMMENT '領収書必須',
  `remarks` VARCHAR(255) COMMENT '備考',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_expense_policy_rule_category_code` (`category_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='経費規程';

CREATE TABLE IF NOT EXISTS `fin_expense_application` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `application_no` VARCHAR(40) COMMENT '申請番号',
  `employee_id` INT COMMENT '申請者',
  `employee_name` VARCHAR(100) COMMENT '社員名',
  `applied_date` DATE NOT NULL COMMENT '申請日',
  `title` VARCHAR(200) COMMENT '件名',
  `total_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '合計金額',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状態（下書き/申請中/承認済/却下/支払済）',
  `approver_id` INT COMMENT '承認者',
  `approved_at` DATETIME COMMENT '承認日時',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_expense_application_application_no` (`application_no`),
  KEY `idx_fin_expense_application_employee_id` (`employee_id`),
  KEY `idx_fin_expense_application_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='経費申請';

CREATE TABLE IF NOT EXISTS `fin_expense_line` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `application_id` BIGINT NOT NULL COMMENT '親レコードID',
  `line_no` INT DEFAULT 1 COMMENT '行番号',
  `expense_date` DATE COMMENT '利用日',
  `category_code` VARCHAR(30) COMMENT '経費区分',
  `description` VARCHAR(255) COMMENT '摘要',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '金額',
  `tax_code` VARCHAR(20) COMMENT '税区分コード',
  `has_receipt` TINYINT(1) DEFAULT 0 COMMENT '領収書添付フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_expense_line_application_id` (`application_id`),
  CONSTRAINT `fk_fin_expense_line_application_id` FOREIGN KEY (`application_id`) REFERENCES `fin_expense_application` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='経費明細';

-- ------- ドメイン: attendance（勤怠） -------
CREATE TABLE IF NOT EXISTS `fin_work_calendar` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `calendar_date` DATE NOT NULL COMMENT '日付',
  `day_type` VARCHAR(20) DEFAULT 'workday' COMMENT '日種別（平日/祝日/会社休日）',
  `name` VARCHAR(100) COMMENT '祝日名等',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_work_calendar_calendar_date` (`calendar_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='勤務カレンダー';

CREATE TABLE IF NOT EXISTS `fin_shift_pattern` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(30) NOT NULL COMMENT 'シフトコード',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `start_time` VARCHAR(5) COMMENT '時刻（HH:MM）',
  `end_time` VARCHAR(5) COMMENT '時刻（HH:MM）',
  `break_minutes` INT DEFAULT 60 COMMENT '休憩分',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_shift_pattern_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='シフトパターン';

CREATE TABLE IF NOT EXISTS `fin_employee_shift` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員ID',
  `shift_date` DATE NOT NULL COMMENT 'シフト日',
  `shift_code` VARCHAR(30) COMMENT 'シフト',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_employee_shift_employee_id` (`employee_id`),
  KEY `idx_fin_employee_shift_shift_date` (`shift_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社員シフト';

CREATE TABLE IF NOT EXISTS `fin_attendance_record` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員',
  `employee_name` VARCHAR(100) COMMENT '社員名',
  `work_date` DATE NOT NULL COMMENT '勤務日',
  `clock_in` DATETIME COMMENT '出勤',
  `clock_out` DATETIME COMMENT '退勤',
  `break_minutes` INT DEFAULT 0 COMMENT '休憩分',
  `work_minutes` INT DEFAULT 0 COMMENT '実働分',
  `overtime_minutes` INT DEFAULT 0 COMMENT '残業分',
  `status` VARCHAR(20) DEFAULT 'normal' COMMENT '状態（正常/遅刻/欠勤/休暇）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_attendance_record_employee_id` (`employee_id`),
  KEY `idx_fin_attendance_record_work_date` (`work_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='勤怠記録';

CREATE TABLE IF NOT EXISTS `fin_leave_type` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(30) NOT NULL COMMENT '休暇コード',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `is_paid` TINYINT(1) DEFAULT 1 COMMENT '有給',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_leave_type_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='休暇区分';

CREATE TABLE IF NOT EXISTS `fin_leave_request` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員ID',
  `employee_name` VARCHAR(100) COMMENT '社員名',
  `leave_code` VARCHAR(30) COMMENT '休暇区分',
  `start_date` DATE NOT NULL COMMENT '開始日',
  `end_date` DATE NOT NULL COMMENT '終了日',
  `days` DECIMAL(6, 2) DEFAULT 0 COMMENT '日数',
  `reason` VARCHAR(255) COMMENT '理由',
  `status` VARCHAR(20) DEFAULT 'submitted' COMMENT '状態（申請中/承認済/却下）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_leave_request_employee_id` (`employee_id`),
  KEY `idx_fin_leave_request_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='休暇申請';

-- ------- ドメイン: payroll（給与） -------
CREATE TABLE IF NOT EXISTS `fin_pay_item` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(30) NOT NULL COMMENT '支給控除項目コード',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `item_type` VARCHAR(20) DEFAULT 'earning' COMMENT '種別（支給/控除）',
  `is_taxable` TINYINT(1) DEFAULT 1 COMMENT '課税対象',
  `account_code` VARCHAR(50) COMMENT '仕訳科目',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_pay_item_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支給控除項目';

CREATE TABLE IF NOT EXISTS `fin_employee_pay_item` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員ID',
  `pay_item_code` VARCHAR(30) COMMENT '支給控除項目コード',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '固定額',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_employee_pay_item_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社員別支給控除';

CREATE TABLE IF NOT EXISTS `fin_social_insurance_profile` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員ID',
  `health_insurance_grade` INT COMMENT '健康保険等級',
  `pension_grade` INT COMMENT '厚生年金等級',
  `standard_monthly` DECIMAL(18, 2) DEFAULT 0 COMMENT '標準報酬月額',
  `dependents` INT DEFAULT 0 COMMENT '扶養人数',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_social_insurance_profile_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社会保険プロファイル';

CREATE TABLE IF NOT EXISTS `fin_withholding_tax_table` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `version` VARCHAR(20) COMMENT '税表バージョン',
  `min_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '下限',
  `max_amount` DECIMAL(18, 2) COMMENT '上限',
  `dependents` INT DEFAULT 0 COMMENT '扶養人数',
  `tax_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '源泉税額',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_withholding_tax_table_version` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='源泉徴収税額表';

CREATE TABLE IF NOT EXISTS `fin_payroll_run` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `run_no` VARCHAR(40) COMMENT '給与計算番号',
  `target_month` VARCHAR(7) NOT NULL COMMENT '対象年月',
  `pay_date` DATE COMMENT '支給日',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状態（下書き/計算済/確定/支払済）',
  `total_gross` DECIMAL(18, 2) DEFAULT 0 COMMENT '総支給',
  `total_deduction` DECIMAL(18, 2) DEFAULT 0 COMMENT '総控除',
  `total_net` DECIMAL(18, 2) DEFAULT 0 COMMENT '差引支給',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_payroll_run_run_no` (`run_no`),
  KEY `idx_fin_payroll_run_target_month` (`target_month`),
  KEY `idx_fin_payroll_run_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='給与計算';

CREATE TABLE IF NOT EXISTS `fin_payroll_run_line` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `run_id` BIGINT NOT NULL COMMENT '親レコードID',
  `employee_id` INT COMMENT '社員ID',
  `employee_name` VARCHAR(100) COMMENT '社員名',
  `gross_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '総支給',
  `deduction_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '控除合計',
  `net_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '差引支給',
  `detail_json` TEXT COMMENT '項目別明細',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_payroll_run_line_run_id` (`run_id`),
  KEY `idx_fin_payroll_run_line_employee_id` (`employee_id`),
  CONSTRAINT `fk_fin_payroll_run_line_run_id` FOREIGN KEY (`run_id`) REFERENCES `fin_payroll_run` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='給与明細';

-- ------- ドメイン: hr（人事） -------
CREATE TABLE IF NOT EXISTS `fin_employee` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_no` VARCHAR(30) NOT NULL COMMENT '社員番号',
  `name` VARCHAR(100) NOT NULL COMMENT '氏名',
  `name_kana` VARCHAR(100) COMMENT 'カナ',
  `user_id` INT COMMENT 'ユーザーID連携',
  `department_code` VARCHAR(50) COMMENT '部門',
  `email` VARCHAR(200) COMMENT 'メールアドレス',
  `hire_date` DATE COMMENT '入社日',
  `leave_date` DATE COMMENT '退社日',
  `employment_type` VARCHAR(20) DEFAULT 'regular' COMMENT '雇用形態（正社員/契約/パート）',
  `status` VARCHAR(20) DEFAULT 'active' COMMENT '状態（在籍/退職）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_employee_employee_no` (`employee_no`),
  KEY `idx_fin_employee_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社員';

CREATE TABLE IF NOT EXISTS `fin_employment_contract` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員ID',
  `contract_type` VARCHAR(30) COMMENT '契約種別',
  `start_date` DATE NOT NULL COMMENT '開始日',
  `end_date` DATE COMMENT '終了日',
  `base_salary` DECIMAL(18, 2) DEFAULT 0 COMMENT '基本給',
  `remarks` VARCHAR(255) COMMENT '備考',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_employment_contract_employee_id` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='雇用契約';

CREATE TABLE IF NOT EXISTS `fin_year_end_adjustment` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `employee_id` INT COMMENT '社員ID',
  `target_year` INT NOT NULL COMMENT '対象年',
  `total_income` DECIMAL(18, 2) DEFAULT 0 COMMENT '給与収入',
  `deduction_total` DECIMAL(18, 2) DEFAULT 0 COMMENT '所得控除合計',
  `tax_settled` DECIMAL(18, 2) DEFAULT 0 COMMENT '年調後税額',
  `refund_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '値（還付/追徴）',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状態（下書き/確定）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_year_end_adjustment_employee_id` (`employee_id`),
  KEY `idx_fin_year_end_adjustment_target_year` (`target_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='年末調整';

-- ------- ドメイン: master（経理マスタ） -------
CREATE TABLE IF NOT EXISTS `fin_account` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(50) NOT NULL COMMENT '勘定科目コード',
  `name` VARCHAR(100) NOT NULL COMMENT '科目名',
  `account_type` VARCHAR(20) NOT NULL COMMENT '科目区分（資産/負債/純資産/収益/費用）',
  `parent_code` VARCHAR(50) COMMENT '親科目',
  `default_tax_code` VARCHAR(20) COMMENT '既定税区分',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `sort_order` INT DEFAULT 0 COMMENT '表示順',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_account_code` (`code`),
  KEY `idx_fin_account_account_type` (`account_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='勘定科目';

CREATE TABLE IF NOT EXISTS `fin_tax_code` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(20) NOT NULL COMMENT '税区分コード',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `rate` DECIMAL(6, 3) DEFAULT 0 COMMENT '税率(%)',
  `kind` VARCHAR(20) DEFAULT 'taxable' COMMENT '税種別（課税/非課税/不課税）',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_tax_code_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='税区分';

CREATE TABLE IF NOT EXISTS `fin_partner` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(50) NOT NULL COMMENT '取引先コード',
  `name` VARCHAR(200) NOT NULL COMMENT '名称',
  `partner_type` VARCHAR(20) DEFAULT 'customer' COMMENT '種別（得意先/仕入先/両方）',
  `customer_id` INT COMMENT 'ERP顧客ID連携',
  `supplier_id` INT COMMENT 'ERP仕入先ID連携',
  `closing_day` INT COMMENT '締め日',
  `payment_terms` VARCHAR(100) COMMENT '支払条件',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_partner_code` (`code`),
  KEY `idx_fin_partner_partner_type` (`partner_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='取引先';

CREATE TABLE IF NOT EXISTS `fin_bank_account` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(30) NOT NULL COMMENT '口座コード',
  `bank_name` VARCHAR(100) COMMENT '銀行名',
  `branch_name` VARCHAR(100) COMMENT '支店名',
  `account_type` VARCHAR(20) DEFAULT 'ordinary' COMMENT '口座種別（普通/当座）',
  `account_number` VARCHAR(30) COMMENT '口座番号',
  `account_holder` VARCHAR(100) COMMENT '口座名義',
  `gl_account_code` VARCHAR(50) COMMENT '対応勘定科目',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_bank_account_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='銀行口座';

-- ------- ドメイン: settings（設定） -------
CREATE TABLE IF NOT EXISTS `fin_company_settings` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `company_name` VARCHAR(200) COMMENT '会社名',
  `fiscal_start_month` INT DEFAULT 4 COMMENT '期首月',
  `tax_method` VARCHAR(20) DEFAULT 'invoice' COMMENT '税方式（インボイス/標準）',
  `rounding` VARCHAR(20) DEFAULT 'round' COMMENT '端数処理（四捨五入/切捨/切上）',
  `base_currency` VARCHAR(10) DEFAULT 'JPY' COMMENT '基準通貨',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会社・会計設定';

CREATE TABLE IF NOT EXISTS `fin_approval_flow` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `code` VARCHAR(30) NOT NULL COMMENT 'フローコード',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `target_type` VARCHAR(30) COMMENT '対象（経費/休暇/給与）',
  `steps_json` TEXT COMMENT '承認ステップ定義',
  `is_active` TINYINT(1) DEFAULT 1 COMMENT '有効フラグ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  UNIQUE KEY `uq_fin_approval_flow_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='承認フロー';

CREATE TABLE IF NOT EXISTS `fin_approval_instance` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `flow_code` VARCHAR(30) COMMENT '承認フローコード',
  `target_type` VARCHAR(30) COMMENT '対象種別',
  `target_id` BIGINT COMMENT '対象ID',
  `current_step` INT DEFAULT 0 COMMENT '現在の承認ステップ',
  `status` VARCHAR(20) DEFAULT 'pending' COMMENT '状態（承認待ち/承認済/却下）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_approval_instance_flow_code` (`flow_code`),
  KEY `idx_fin_approval_instance_target_id` (`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='承認インスタンス';

-- ------- ドメイン: integration（連携） -------
CREATE TABLE IF NOT EXISTS `fin_integration_export_log` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `export_type` VARCHAR(30) COMMENT '出力形式（freee/弥生/CSV）',
  `target_period` VARCHAR(7) COMMENT '対象年月',
  `record_count` INT DEFAULT 0 COMMENT '出力件数',
  `file_name` VARCHAR(255) COMMENT 'ファイル名',
  `status` VARCHAR(20) DEFAULT 'success' COMMENT '結果（成功/失敗）',
  `message` VARCHAR(500) COMMENT 'メッセージ',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_integration_export_log_export_type` (`export_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会計連携出力ログ';

-- ------- ドメイン: common（共通） -------
CREATE TABLE IF NOT EXISTS `fin_attachment` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `ref_type` VARCHAR(40) COMMENT '関連種別',
  `ref_id` BIGINT COMMENT '関連ID',
  `file_name` VARCHAR(255) COMMENT 'ファイル名',
  `file_path` VARCHAR(500) COMMENT 'ファイルパス',
  `content_type` VARCHAR(100) COMMENT 'コンテンツ種別',
  `file_size` BIGINT DEFAULT 0 COMMENT 'ファイルサイズ（バイト）',
  `created_by` VARCHAR(100) DEFAULT NULL COMMENT '作成者',
  `updated_by` VARCHAR(100) DEFAULT NULL COMMENT '更新者',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  KEY `idx_fin_attachment_ref_type` (`ref_type`),
  KEY `idx_fin_attachment_ref_id` (`ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='添付ファイル';

-- ------- 初期データ -------
INSERT IGNORE INTO `fin_account` (`code`,`name`,`account_type`,`is_active`,`sort_order`) VALUES
('100','現金','asset',1,0),
('110','普通預金','asset',1,1),
('135','売掛金','asset',1,2),
('140','棚卸資産','asset',1,3),
('145','仕掛品','asset',1,4),
('146','製品','asset',1,5),
('170','建物附属設備','asset',1,6),
('175','機械装置','asset',1,7),
('180','減価償却累計額','asset',1,8),
('305','買掛金','liability',1,9),
('310','未払金','liability',1,10),
('315','未払費用','liability',1,11),
('320','預り金','liability',1,12),
('500','資本金','equity',1,13),
('600','売上高','revenue',1,14),
('700','仕入高','expense',1,15),
('705','外注加工費','expense',1,16),
('710','給与手当','expense',1,17),
('715','法定福利費','expense',1,18),
('720','減価償却費','expense',1,19),
('730','旅費交通費','expense',1,20),
('735','通信費','expense',1,21),
('740','消耗品費','expense',1,22),
('745','会議費','expense',1,23),
('750','棚卸差額','expense',1,24);
INSERT IGNORE INTO `fin_tax_code` (`code`,`name`,`rate`,`kind`,`is_active`) VALUES
('TAX10','課税仕入10%',10.000,'taxable',1),
('TAX8','軽減税率8%',8.000,'taxable',1),
('OUT10','課税売上10%',10.000,'taxable',1),
('EXEMPT','非課税',0.000,'exempt',1),
('NONTAX','不課税',0.000,'non_taxable',1);
INSERT IGNORE INTO `fin_pay_item` (`code`,`name`,`item_type`,`is_taxable`,`account_code`,`is_active`) VALUES
('BASE','基本給','earning',1,'710',1),
('OVERTIME','時間外手当','earning',1,'710',1),
('COMMUTE','通勤手当','earning',0,'730',1),
('HEALTH','健康保険','deduction',0,'320',1),
('PENSION','厚生年金','deduction',0,'320',1),
('EMPLOY','雇用保険','deduction',0,'320',1),
('INCOMETAX','所得税','deduction',0,'320',1),
('RESIDENT','住民税','deduction',0,'320',1);
INSERT IGNORE INTO `fin_company_settings` (`id`,`company_name`,`fiscal_start_month`,`tax_method`,`base_currency`) VALUES (1,'Smart-EMAPs 株式会社',4,'invoice','JPY');