<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '請求書'
const apiBase = '/api/fin/receivables/ar-invoice'
const columns: FinColumn[] = [{"prop": "invoice_no", "label": "請求番号"}, {"prop": "partner_id", "label": "取引先"}, {"prop": "partner_name", "label": "取引先名"}, {"prop": "invoice_date", "label": "請求日"}, {"prop": "due_date", "label": "支払期限"}, {"prop": "subtotal", "label": "税抜"}, {"prop": "tax_amount", "label": "消費税"}, {"prop": "total_amount", "label": "税込合計"}]
const fields: FinField[] = [{"prop": "invoice_no", "label": "請求番号", "type": "text", "required": false}, {"prop": "partner_id", "label": "取引先", "type": "number", "required": false}, {"prop": "partner_name", "label": "取引先名", "type": "text", "required": false}, {"prop": "invoice_date", "label": "請求日", "type": "date", "required": true}, {"prop": "due_date", "label": "支払期限", "type": "date", "required": false}, {"prop": "subtotal", "label": "税抜", "type": "number", "required": false}, {"prop": "tax_amount", "label": "消費税", "type": "number", "required": false}, {"prop": "total_amount", "label": "税込合計", "type": "number", "required": false}, {"prop": "paid_amount", "label": "入金済", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}, {"prop": "source_invoice_id", "label": "ERP 請求書連携", "type": "number", "required": false}]
</script>
