<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '入金・消込'
const apiBase = '/api/fin/receivables/ar-receipt'
const columns: FinColumn[] = [{"prop": "receipt_no", "label": "入金番号"}, {"prop": "partner_id", "label": "partner"}, {"prop": "receipt_date", "label": "入金日"}, {"prop": "amount", "label": "金額"}, {"prop": "method", "label": "method"}, {"prop": "bank_account_id", "label": "入金口座"}, {"prop": "status", "label": "ステータス"}]
const fields: FinField[] = [{"prop": "receipt_no", "label": "入金番号", "type": "text", "required": false}, {"prop": "partner_id", "label": "partner", "type": "number", "required": false}, {"prop": "receipt_date", "label": "入金日", "type": "date", "required": true}, {"prop": "amount", "label": "金額", "type": "number", "required": false}, {"prop": "method", "label": "method", "type": "text", "required": false}, {"prop": "bank_account_id", "label": "入金口座", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}]
</script>
