<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinReportPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinReportPage from '@/views/fin/components/FinReportPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '売掛年齢表'
const apiBase = '/api/fin/receivables/ar-invoice'
const columns: FinColumn[] = [{"prop": "invoice_no", "label": "請求番号"}, {"prop": "partner_id", "label": "取引先"}, {"prop": "partner_name", "label": "取引先名"}, {"prop": "invoice_date", "label": "請求日"}, {"prop": "due_date", "label": "支払期限"}, {"prop": "subtotal", "label": "税抜"}, {"prop": "tax_amount", "label": "消費税"}, {"prop": "total_amount", "label": "税込合計"}, {"prop": "paid_amount", "label": "入金済"}, {"prop": "status", "label": "ステータス"}]
</script>
