<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '雇用契約'
const apiBase = '/api/fin/hr/employment-contract'
const columns: FinColumn[] = [{"prop": "employee_id", "label": "employee"}, {"prop": "contract_type", "label": "契約種別"}, {"prop": "start_date", "label": "start date"}, {"prop": "end_date", "label": "end date"}, {"prop": "base_salary", "label": "基本給"}, {"prop": "remarks", "label": "備考"}]
const fields: FinField[] = [{"prop": "employee_id", "label": "employee", "type": "number", "required": false}, {"prop": "contract_type", "label": "契約種別", "type": "text", "required": false}, {"prop": "start_date", "label": "start date", "type": "date", "required": true}, {"prop": "end_date", "label": "end date", "type": "date", "required": false}, {"prop": "base_salary", "label": "基本給", "type": "number", "required": false}, {"prop": "remarks", "label": "備考", "type": "text", "required": false}]
</script>
