<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '社員'
const apiBase = '/api/fin/hr/employee'
const columns: FinColumn[] = [{"prop": "employee_no", "label": "社員番号"}, {"prop": "name", "label": "名称"}, {"prop": "name_kana", "label": "カナ"}, {"prop": "user_id", "label": "user"}, {"prop": "department_code", "label": "部門"}, {"prop": "email", "label": "email"}, {"prop": "hire_date", "label": "入社日"}, {"prop": "leave_date", "label": "退社日"}]
const fields: FinField[] = [{"prop": "employee_no", "label": "社員番号", "type": "text", "required": true}, {"prop": "name", "label": "名称", "type": "text", "required": true}, {"prop": "name_kana", "label": "カナ", "type": "text", "required": false}, {"prop": "user_id", "label": "user", "type": "number", "required": false}, {"prop": "department_code", "label": "部門", "type": "text", "required": false}, {"prop": "email", "label": "email", "type": "text", "required": false}, {"prop": "hire_date", "label": "入社日", "type": "date", "required": false}, {"prop": "leave_date", "label": "退社日", "type": "date", "required": false}, {"prop": "employment_type", "label": "employment type", "type": "text", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}]
</script>
