<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '年末調整'
const apiBase = '/api/fin/hr/year-end-adjustment'
const columns: FinColumn[] = [{"prop": "employee_id", "label": "employee"}, {"prop": "target_year", "label": "対象年"}, {"prop": "total_income", "label": "給与収入"}, {"prop": "deduction_total", "label": "所得控除合計"}, {"prop": "tax_settled", "label": "年調後税額"}, {"prop": "refund_amount", "label": "refund amount"}, {"prop": "status", "label": "ステータス"}]
const fields: FinField[] = [{"prop": "employee_id", "label": "employee", "type": "number", "required": false}, {"prop": "target_year", "label": "対象年", "type": "number", "required": true}, {"prop": "total_income", "label": "給与収入", "type": "number", "required": false}, {"prop": "deduction_total", "label": "所得控除合計", "type": "number", "required": false}, {"prop": "tax_settled", "label": "年調後税額", "type": "number", "required": false}, {"prop": "refund_amount", "label": "refund amount", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}]
</script>
