<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '仕訳帳'
const apiBase = '/api/fin/accounting/journal-entry'
const columns: FinColumn[] = [{"prop": "journal_no", "label": "仕訳番号"}, {"prop": "entry_date", "label": "仕訳日"}, {"prop": "period_ym", "label": "計上年月"}, {"prop": "entry_type", "label": "entry type"}, {"prop": "description", "label": "摘要"}, {"prop": "total_debit", "label": "借方合計"}, {"prop": "total_credit", "label": "貸方合計"}, {"prop": "status", "label": "ステータス"}]
const fields: FinField[] = [{"prop": "journal_no", "label": "仕訳番号", "type": "text", "required": false}, {"prop": "entry_date", "label": "仕訳日", "type": "date", "required": true}, {"prop": "period_ym", "label": "計上年月", "type": "text", "required": false}, {"prop": "entry_type", "label": "entry type", "type": "text", "required": false}, {"prop": "description", "label": "摘要", "type": "text", "required": false}, {"prop": "total_debit", "label": "借方合計", "type": "number", "required": false}, {"prop": "total_credit", "label": "貸方合計", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}, {"prop": "source_id", "label": "source", "type": "number", "required": false}]
</script>
