<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinReportPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinReportPage from '@/views/fin/components/FinReportPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '総勘定元帳'
const apiBase = '/api/fin/accounting/journal-line'
const columns: FinColumn[] = [{"prop": "entry_id", "label": "親ID"}, {"prop": "line_no", "label": "行番号"}, {"prop": "account_code", "label": "勘定科目"}, {"prop": "account_name", "label": "科目名"}, {"prop": "debit", "label": "借方"}, {"prop": "credit", "label": "貸方"}, {"prop": "tax_code", "label": "税区分"}, {"prop": "tax_amount", "label": "消費税額"}, {"prop": "department_code", "label": "部門"}, {"prop": "partner_id", "label": "取引先"}]
</script>
