<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinBatchPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinBatchPage from '@/views/fin/components/FinBatchPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '仕訳取込・連携'
const apiBase = '/api/fin/accounting/journal-source'
const columns: FinColumn[] = [{"prop": "source_type", "label": "SALES_POSTED 等"}, {"prop": "source_module", "label": "source module"}, {"prop": "source_ref", "label": "source ref"}, {"prop": "event_date", "label": "事象日"}, {"prop": "amount", "label": "金額"}, {"prop": "payload_json", "label": "連携ペイロード"}, {"prop": "status", "label": "ステータス"}, {"prop": "journal_entry_id", "label": "生成された仕訳"}]
</script>
