<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinBatchPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinBatchPage from '@/views/fin/components/FinBatchPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '月次・年次決算'
const apiBase = '/api/fin/accounting/accounting-period'
const columns: FinColumn[] = [{"prop": "fiscal_year_id", "label": "会計年度"}, {"prop": "year_month", "label": "YYYY-MM"}, {"prop": "status", "label": "ステータス"}, {"prop": "closed_at", "label": "締め日時"}]
</script>
