# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""勤怠（attendance）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.attendance import models as md
from app.modules.fin.attendance import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.WorkCalendar, out_schema=sc.WorkCalendarOut, create_schema=sc.WorkCalendarCreate, update_schema=sc.WorkCalendarUpdate, resource='work-calendar', search_fields=['name'], order_by='id desc', label='WorkCalendar'))
router.include_router(build_crud_router(model=md.ShiftPattern, out_schema=sc.ShiftPatternOut, create_schema=sc.ShiftPatternCreate, update_schema=sc.ShiftPatternUpdate, resource='shift-pattern', search_fields=['name'], order_by='id desc', label='ShiftPattern'))
router.include_router(build_crud_router(model=md.EmployeeShift, out_schema=sc.EmployeeShiftOut, create_schema=sc.EmployeeShiftCreate, update_schema=sc.EmployeeShiftUpdate, resource='employee-shift', search_fields=[], order_by='shift_date desc', label='EmployeeShift'))
router.include_router(build_crud_router(model=md.AttendanceRecord, out_schema=sc.AttendanceRecordOut, create_schema=sc.AttendanceRecordCreate, update_schema=sc.AttendanceRecordUpdate, resource='attendance-record', search_fields=['employee_name'], order_by='work_date desc', label='AttendanceRecord'))
router.include_router(build_crud_router(model=md.LeaveType, out_schema=sc.LeaveTypeOut, create_schema=sc.LeaveTypeCreate, update_schema=sc.LeaveTypeUpdate, resource='leave-type', search_fields=['name'], order_by='id desc', label='LeaveType'))
router.include_router(build_crud_router(model=md.LeaveRequest, out_schema=sc.LeaveRequestOut, create_schema=sc.LeaveRequestCreate, update_schema=sc.LeaveRequestUpdate, resource='leave-request', search_fields=['employee_name'], order_by='start_date desc', label='LeaveRequest'))

__all__ = ['router']  # entities: WorkCalendar, ShiftPattern, EmployeeShift, AttendanceRecord, LeaveType, LeaveRequest
