# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""勤怠（attendance）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class WorkCalendar(Base):
    __tablename__ = "fin_work_calendar"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    calendar_date = Column(Date, nullable=False, index=True)
    day_type = Column(String(20), default="workday")
    name = Column(String(100))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ShiftPattern(Base):
    __tablename__ = "fin_shift_pattern"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(30), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    start_time = Column(String(5))
    end_time = Column(String(5))
    break_minutes = Column(Integer, default=60)
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class EmployeeShift(Base):
    __tablename__ = "fin_employee_shift"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True)
    shift_date = Column(Date, nullable=False, index=True)
    shift_code = Column(String(30))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class AttendanceRecord(Base):
    __tablename__ = "fin_attendance_record"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True)
    employee_name = Column(String(100))
    work_date = Column(Date, nullable=False, index=True)
    clock_in = Column(DateTime)
    clock_out = Column(DateTime)
    break_minutes = Column(Integer, default=0)
    work_minutes = Column(Integer, default=0)
    overtime_minutes = Column(Integer, default=0)
    status = Column(String(20), default="normal")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class LeaveType(Base):
    __tablename__ = "fin_leave_type"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(30), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    is_paid = Column(Boolean, default=True)
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class LeaveRequest(Base):
    __tablename__ = "fin_leave_request"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    employee_id = Column(Integer, index=True)
    employee_name = Column(String(100))
    leave_code = Column(String(30))
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    days = Column(Numeric(6, 2), default=0)
    reason = Column(String(255))
    status = Column(String(20), index=True, default="submitted")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

