# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""勤怠（attendance）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class WorkCalendarCreate(BaseModel):
    calendar_date: Optional[date] = None
    day_type: Optional[str] = None
    name: Optional[str] = None


class WorkCalendarUpdate(WorkCalendarCreate):
    pass


class WorkCalendarOut(WorkCalendarCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class WorkCalendarPage(BaseModel):
    items: List[WorkCalendarOut]
    total: int
    page: int
    page_size: int
    pages: int


class ShiftPatternCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    break_minutes: Optional[int] = None
    is_active: Optional[bool] = None


class ShiftPatternUpdate(ShiftPatternCreate):
    pass


class ShiftPatternOut(ShiftPatternCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ShiftPatternPage(BaseModel):
    items: List[ShiftPatternOut]
    total: int
    page: int
    page_size: int
    pages: int


class EmployeeShiftCreate(BaseModel):
    employee_id: Optional[int] = None
    shift_date: Optional[date] = None
    shift_code: Optional[str] = None


class EmployeeShiftUpdate(EmployeeShiftCreate):
    pass


class EmployeeShiftOut(EmployeeShiftCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class EmployeeShiftPage(BaseModel):
    items: List[EmployeeShiftOut]
    total: int
    page: int
    page_size: int
    pages: int


class AttendanceRecordCreate(BaseModel):
    employee_id: Optional[int] = None
    employee_name: Optional[str] = None
    work_date: Optional[date] = None
    clock_in: Optional[datetime] = None
    clock_out: Optional[datetime] = None
    break_minutes: Optional[int] = None
    work_minutes: Optional[int] = None
    overtime_minutes: Optional[int] = None
    status: Optional[str] = None


class AttendanceRecordUpdate(AttendanceRecordCreate):
    pass


class AttendanceRecordOut(AttendanceRecordCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class AttendanceRecordPage(BaseModel):
    items: List[AttendanceRecordOut]
    total: int
    page: int
    page_size: int
    pages: int


class LeaveTypeCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    is_paid: Optional[bool] = None
    is_active: Optional[bool] = None


class LeaveTypeUpdate(LeaveTypeCreate):
    pass


class LeaveTypeOut(LeaveTypeCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class LeaveTypePage(BaseModel):
    items: List[LeaveTypeOut]
    total: int
    page: int
    page_size: int
    pages: int


class LeaveRequestCreate(BaseModel):
    employee_id: Optional[int] = None
    employee_name: Optional[str] = None
    leave_code: Optional[str] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    days: Optional[float] = None
    reason: Optional[str] = None
    status: Optional[str] = None


class LeaveRequestUpdate(LeaveRequestCreate):
    pass


class LeaveRequestOut(LeaveRequestCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class LeaveRequestPage(BaseModel):
    items: List[LeaveRequestOut]
    total: int
    page: int
    page_size: int
    pages: int

