// @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND
import ja from './ja'
import zh from './zh'
import en from './en'
import vi from './vi'

export const finLocales = { ja, zh, en, vi }
