# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""設定（settings）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.settings import models as md
from app.modules.fin.settings import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.CompanySettings, out_schema=sc.CompanySettingsOut, create_schema=sc.CompanySettingsCreate, update_schema=sc.CompanySettingsUpdate, resource='company-settings', search_fields=['company_name'], order_by='id desc', label='CompanySettings'))
router.include_router(build_crud_router(model=md.ApprovalFlow, out_schema=sc.ApprovalFlowOut, create_schema=sc.ApprovalFlowCreate, update_schema=sc.ApprovalFlowUpdate, resource='approval-flow', search_fields=['name'], order_by='id desc', label='ApprovalFlow'))
router.include_router(build_crud_router(model=md.ApprovalInstance, out_schema=sc.ApprovalInstanceOut, create_schema=sc.ApprovalInstanceCreate, update_schema=sc.ApprovalInstanceUpdate, resource='approval-instance', search_fields=[], order_by='created_at desc', label='ApprovalInstance'))

__all__ = ['router']  # entities: CompanySettings, ApprovalFlow, ApprovalInstance
