# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""設定（settings）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class CompanySettings(Base):
    __tablename__ = "fin_company_settings"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    company_name = Column(String(200))
    fiscal_start_month = Column(Integer, default=4)
    tax_method = Column(String(20), default="invoice")
    rounding = Column(String(20), default="round")
    base_currency = Column(String(10), default="JPY")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ApprovalFlow(Base):
    __tablename__ = "fin_approval_flow"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    code = Column(String(30), nullable=False, index=True, unique=True)
    name = Column(String(100), nullable=False)
    target_type = Column(String(30))
    steps_json = Column(Text)
    is_active = Column(Boolean, default=True)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ApprovalInstance(Base):
    __tablename__ = "fin_approval_instance"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    flow_code = Column(String(30), index=True)
    target_type = Column(String(30))
    target_id = Column(BigInteger, index=True)
    current_step = Column(Integer, default=0)
    status = Column(String(20), default="pending")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

