# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""設定（settings）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class CompanySettingsCreate(BaseModel):
    company_name: Optional[str] = None
    fiscal_start_month: Optional[int] = None
    tax_method: Optional[str] = None
    rounding: Optional[str] = None
    base_currency: Optional[str] = None


class CompanySettingsUpdate(CompanySettingsCreate):
    pass


class CompanySettingsOut(CompanySettingsCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class CompanySettingsPage(BaseModel):
    items: List[CompanySettingsOut]
    total: int
    page: int
    page_size: int
    pages: int


class ApprovalFlowCreate(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None
    target_type: Optional[str] = None
    steps_json: Optional[str] = None
    is_active: Optional[bool] = None


class ApprovalFlowUpdate(ApprovalFlowCreate):
    pass


class ApprovalFlowOut(ApprovalFlowCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ApprovalFlowPage(BaseModel):
    items: List[ApprovalFlowOut]
    total: int
    page: int
    page_size: int
    pages: int


class ApprovalInstanceCreate(BaseModel):
    flow_code: Optional[str] = None
    target_type: Optional[str] = None
    target_id: Optional[int] = None
    current_step: Optional[int] = None
    status: Optional[str] = None


class ApprovalInstanceUpdate(ApprovalInstanceCreate):
    pass


class ApprovalInstanceOut(ApprovalInstanceCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ApprovalInstancePage(BaseModel):
    items: List[ApprovalInstanceOut]
    total: int
    page: int
    page_size: int
    pages: int

