-- SEED: email_templates
-- 生成元: scripts/export_schema_split.py
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

INSERT IGNORE INTO `email_templates` (`id`, `code`, `name`, `subject`, `body`, `event_code`, `language`, `variables`, `is_active`) VALUES
(1, 'APPROVAL_REQUEST', '承認依頼', '【要承認】{document_type} #{document_no}', '<p>{approver_name}様</p><p>以下の承認依頼が届いています。</p><p>伝票種類: {document_type}<br>伝票番号: {document_no}<br>申請者: {requester_name}<br>金額: {amount}</p><p>システムにログインして承認処理を行ってください。</p>', 'APPROVAL_REQUEST', 'ja', NULL, 1),
(2, 'APPROVAL_COMPLETE', '承認完了', '【承認完了】{document_type} #{document_no}', '<p>{requester_name}様</p><p>以下の申請が承認されました。</p><p>伝票種類: {document_type}<br>伝票番号: {document_no}<br>承認者: {approver_name}</p>', 'APPROVAL_COMPLETE', 'ja', NULL, 1),
(3, 'PASSWORD_RESET', 'パスワードリセット', '【Smart-EMAP】パスワードリセット', '<p>{user_name}様</p><p>パスワードがリセットされました。</p><p>新しいパスワードでログインしてください。</p>', NULL, 'ja', NULL, 1),
(4, 'WELCOME', 'ようこそ', '【Smart-EMAP】アカウント作成完了', '<p>{user_name}様</p><p>Smart-EMAPへようこそ！</p><p>アカウントが作成されました。以下の情報でログインしてください。</p><p>ユーザー名: {username}<br>初期パスワード: {initial_password}</p>', NULL, 'ja', NULL, 1),
(5, 'CUTTING_ACTUAL_CONFIRMED', '切断実績確定', '【Smart-EMAP】切断実績確定 {production_day}（{total_quantity}本）', '<p>切断実績が確定されました。</p><p>生産日: {production_day}<br>登録件数: {inserted_count} 件<br>数量合計: {total_quantity} 本<br>確定者: {confirmed_by}<br>確定日時: {confirmed_at}</p>{machine_summary}<p>Smart-EMAP 生産管理システム</p>', 'CUTTING_ACTUAL_CONFIRMED', 'ja', '[\"production_day\", \"inserted_count\", \"total_quantity\", \"confirmed_by\", \"confirmed_at\", \"machine_summary\"]', 1),
(6, 'CHAMFERING_ACTUAL_CONFIRMED', '面取実績確定', '【Smart-EMAP】面取実績確定 {production_day}（{total_quantity}本）', '<p>面取実績が確定されました。</p><p>生産日: {production_day}<br>登録件数: {inserted_count} 件<br>数量合計: {total_quantity} 本<br>確定者: {confirmed_by}<br>確定日時: {confirmed_at}</p>{machine_summary}<p>Smart-EMAP 生産管理システム</p>', 'CHAMFERING_ACTUAL_CONFIRMED', 'ja', '[\"production_day\", \"inserted_count\", \"total_quantity\", \"confirmed_by\", \"confirmed_at\", \"machine_summary\"]', 1),
(7, 'CUTTING_TRIAL_COMPLETED', '切断試作完了', '【Smart-EMAP】切断試作完了通知 {production_day}（{item_count}件）', '<p>切断指示（試作）の完了分をお知らせします。</p><p>対象生産日: {production_day}<br>件数: {item_count} 件<br>生産数合計: {total_quantity} 本</p>{item_list}<p>Smart-EMAP 生産管理システム</p>', 'CUTTING_TRIAL_COMPLETED', 'ja', '[\"production_day\", \"item_count\", \"total_quantity\", \"item_list\", \"item_list_text\"]', 1),
(8, 'INVENTORY_STAGNATION', '在庫停滞アラート', '【Smart-EMAP】{process_label} 在庫停滞アラート {as_of}（{item_count}件）', '<p>{process_label}工程で在庫停滞が検出されました。</p><p>基準日: {as_of}<br>閾値(&gt;): {min_quantity}<br>連続暦日: {stable_calendar_days} 日<br>検出件数: {item_count} 件<br>送信者: {sent_by}<br>送信日時: {sent_at}</p>{item_table}<p>Smart-EMAP 生産管理システム</p>', 'INVENTORY_STAGNATION', 'ja', '[\"process_label\", \"as_of\", \"min_quantity\", \"stable_calendar_days\", \"item_count\", \"item_table\", \"item_list_text\", \"sent_by\", \"sent_at\"]', 1),
(9, 'REPORT_CUTTING_DAILY_ACTUAL', '切断工程実績レポート', '【Smart-EMAP】{report_name} {period_label}（{record_count}件）', '{summary_html}<p style=\"margin:12px 0 0;font-size:11px;color:#94a3b8;\">※ 本メールは Smart-EMAP システムより自動送信されています。</p><p style=\"margin:4px 0 0;font-size:11px;color:#94a3b8;\">送信者: {sent_by}　送信日時: {sent_at}</p>', 'REPORT_CUTTING_DAILY_ACTUAL', 'ja', '[\"report_name\", \"period_label\", \"record_count\", \"summary_html\", \"sent_by\", \"sent_at\"]', 1),
(10, 'REPORT_INVENTORY_TREND_WEEKLY', '在庫推移レポート', '【Smart-EMAP】{report_name} {period_label}', '<p>{report_name}をお届けします。</p><p>対象期間: {period_label}<br>送信者: {sent_by}<br>送信日時: {sent_at}</p>{summary_html}<p>詳細は添付ファイルをご確認ください。</p><p>Smart-EMAP 生産管理システム</p>', 'REPORT_INVENTORY_TREND_WEEKLY', 'ja', '[\"report_name\", \"period_label\", \"record_count\", \"summary_html\", \"sent_by\", \"sent_at\"]', 1),
(11, 'REPORT_PLAN_ACTUAL_MONTHLY', '計画実績対比レポート', '【Smart-EMAP】{report_name} {period_label}', '<p>{report_name}をお届けします。</p><p>基準月: {period_label}<br>送信者: {sent_by}<br>送信日時: {sent_at}</p>{summary_html}<p>詳細は添付ファイルをご確認ください。</p><p>Smart-EMAP 生産管理システム</p>', 'REPORT_PLAN_ACTUAL_MONTHLY', 'ja', '[\"report_name\", \"period_label\", \"record_count\", \"summary_html\", \"sent_by\", \"sent_at\"]', 1),
(12, 'BULK_DISPOSAL_RETENTION_PENDING', '大量廃棄・保留品 未処理通知', '【Smart-EMAP】未処理 大量廃棄・保留品 {item_count}件', '<p>未処理の大量廃棄・保留品記録があります。</p>{deadline_notice}<p>件数: {item_count} 件<br>合計本数: {total_quantity} 本<br>期限超過: {overdue_count} 件<br>送信者: {sent_by}<br>送信日時: {sent_at}</p>{item_table}<p style=\"margin-top:16px;font-size:12px;color:#64748b;\">※ 保留品は処理期限までに必ず対応してください。期限超過分は至急ご確認をお願いします。</p><p>Smart-EMAP 在庫管理システム</p>', 'BULK_DISPOSAL_RETENTION_PENDING', 'ja', '[\"item_count\", \"total_quantity\", \"overdue_count\", \"item_table\", \"item_list_text\", \"deadline_notice\", \"deadline_notice_text\", \"sent_by\", \"sent_at\"]', 1),
(13, 'PRODUCT_LABEL_OUTSOURCE_ORDER', '成型用ラベル 外注注文', '【Smart-EMAP】外注ラベル注文 {item_count}件', '<p>外注ラベルの注文があります。</p><p>注文件数: <strong>{item_count}</strong> 件<br>注文数合計: <strong>{total_order_qty}</strong><br>送信者: {sent_by}<br>送信日時: {sent_at}</p>{item_table}<p>添付: 現品票PDF {attachment_count} 枚（{attachment_names}）</p><p>Smart-EMAP マスタ管理</p>', 'PRODUCT_LABEL_OUTSOURCE_ORDER', 'ja', '[\"item_count\", \"total_order_qty\", \"item_table\", \"item_list_text\", \"attachment_count\", \"attachment_names\", \"sent_by\", \"sent_at\"]', 1),
(14, 'PRODUCT_USE_LABEL_OUTSOURCE_ORDER', '製品用ラベル 外注注文', '【Smart-EMAP】製品用ラベル外注注文 {item_count}件', '<p>製品用ラベルの外注注文があります。</p><p>注文件数: <strong>{item_count}</strong> 件<br>注文数合計: <strong>{total_order_qty}</strong><br>送信者: {sent_by}<br>送信日時: {sent_at}</p>{item_table}<p>添付: ラベルPDF {attachment_count} 枚（{attachment_names}）</p><p>Smart-EMAP マスタ管理</p>', 'PRODUCT_USE_LABEL_OUTSOURCE_ORDER', 'ja', '[\"item_count\", \"total_order_qty\", \"item_table\", \"item_list_text\", \"attachment_count\", \"attachment_names\", \"sent_by\", \"sent_at\"]', 1),
(15, 'INSPECTION_NEWSPAPER_ALERT', '検査通知(防錆)', '【Smart-EMAP】検査工程：新聞紙投入のお願い（{production_day}）', '<p>切断実績が確定されました。以下の製品は最終工程（検査）で<strong>新聞紙を入れて</strong>ください。</p><p>生産日: {production_day}<br>対象製品数: {product_count} 品目<br>計画数合計: {total_quantity} 本</p>{product_table}<p>Smart-EMAP 生産管理システム</p>', 'INSPECTION_NEWSPAPER_ALERT', 'ja', '[\"production_day\", \"product_table\", \"product_count\", \"total_quantity\"]', 1);

SET FOREIGN_KEY_CHECKS = 1;
