<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '銀行口座'
const apiBase = '/api/fin/master/bank-account'
const columns: FinColumn[] = [{"prop": "code", "label": "コード"}, {"prop": "bank_name", "label": "銀行名"}, {"prop": "branch_name", "label": "支店名"}, {"prop": "account_type", "label": "account type"}, {"prop": "account_number", "label": "account number"}, {"prop": "account_holder", "label": "account holder"}, {"prop": "gl_account_code", "label": "対応勘定科目"}, {"prop": "is_active", "label": "有効"}]
const fields: FinField[] = [{"prop": "code", "label": "コード", "type": "text", "required": true}, {"prop": "bank_name", "label": "銀行名", "type": "text", "required": false}, {"prop": "branch_name", "label": "支店名", "type": "text", "required": false}, {"prop": "account_type", "label": "account type", "type": "text", "required": false}, {"prop": "account_number", "label": "account number", "type": "text", "required": false}, {"prop": "account_holder", "label": "account holder", "type": "text", "required": false}, {"prop": "gl_account_code", "label": "対応勘定科目", "type": "text", "required": false}, {"prop": "is_active", "label": "有効", "type": "switch", "required": false}]
</script>
