<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '取引先'
const apiBase = '/api/fin/master/partner'
const columns: FinColumn[] = [{"prop": "code", "label": "コード"}, {"prop": "name", "label": "名称"}, {"prop": "partner_type", "label": "partner type"}, {"prop": "customer_id", "label": "customer"}, {"prop": "supplier_id", "label": "supplier"}, {"prop": "closing_day", "label": "締め日"}, {"prop": "payment_terms", "label": "支払条件"}, {"prop": "is_active", "label": "有効"}]
const fields: FinField[] = [{"prop": "code", "label": "コード", "type": "text", "required": true}, {"prop": "name", "label": "名称", "type": "text", "required": true}, {"prop": "partner_type", "label": "partner type", "type": "text", "required": false}, {"prop": "customer_id", "label": "customer", "type": "number", "required": false}, {"prop": "supplier_id", "label": "supplier", "type": "number", "required": false}, {"prop": "closing_day", "label": "締め日", "type": "number", "required": false}, {"prop": "payment_terms", "label": "支払条件", "type": "text", "required": false}, {"prop": "is_active", "label": "有効", "type": "switch", "required": false}]
</script>
