<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '勘定科目'
const apiBase = '/api/fin/master/account'
const columns: FinColumn[] = [{"prop": "code", "label": "コード"}, {"prop": "name", "label": "名称"}, {"prop": "account_type", "label": "account type"}, {"prop": "parent_code", "label": "親科目"}, {"prop": "default_tax_code", "label": "既定税区分"}, {"prop": "is_active", "label": "有効"}, {"prop": "sort_order", "label": "sort order"}]
const fields: FinField[] = [{"prop": "code", "label": "コード", "type": "text", "required": true}, {"prop": "name", "label": "名称", "type": "text", "required": true}, {"prop": "account_type", "label": "account type", "type": "text", "required": true}, {"prop": "parent_code", "label": "親科目", "type": "text", "required": false}, {"prop": "default_tax_code", "label": "既定税区分", "type": "text", "required": false}, {"prop": "is_active", "label": "有効", "type": "switch", "required": false}, {"prop": "sort_order", "label": "sort order", "type": "number", "required": false}]
</script>
