<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '税区分'
const apiBase = '/api/fin/master/tax-code'
const columns: FinColumn[] = [{"prop": "code", "label": "コード"}, {"prop": "name", "label": "名称"}, {"prop": "rate", "label": "税率(%)"}, {"prop": "kind", "label": "kind"}, {"prop": "is_active", "label": "有効"}]
const fields: FinField[] = [{"prop": "code", "label": "コード", "type": "text", "required": true}, {"prop": "name", "label": "名称", "type": "text", "required": true}, {"prop": "rate", "label": "税率(%)", "type": "number", "required": false}, {"prop": "kind", "label": "kind", "type": "text", "required": false}, {"prop": "is_active", "label": "有効", "type": "switch", "required": false}]
</script>
