# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND
"""FIN（経理・原価・人事）モジュール集約ルーター。"""
from fastapi import APIRouter
from app.modules.fin.accounting.api import router as accounting_router
from app.modules.fin.receivables.api import router as receivables_router
from app.modules.fin.payables.api import router as payables_router
from app.modules.fin.expense.api import router as expense_router
from app.modules.fin.attendance.api import router as attendance_router
from app.modules.fin.payroll.api import router as payroll_router
from app.modules.fin.hr.api import router as hr_router
from app.modules.fin.master.api import router as master_router
from app.modules.fin.settings.api import router as settings_router
from app.modules.fin.integration.api import router as integration_router
from app.modules.fin.common.api import router as common_router

router = APIRouter()
router.include_router(accounting_router, prefix="/accounting")
router.include_router(receivables_router, prefix="/receivables")
router.include_router(payables_router, prefix="/payables")
router.include_router(expense_router, prefix="/expense")
router.include_router(attendance_router, prefix="/attendance")
router.include_router(payroll_router, prefix="/payroll")
router.include_router(hr_router, prefix="/hr")
router.include_router(master_router, prefix="/master")
router.include_router(settings_router, prefix="/settings")
router.include_router(integration_router, prefix="/integration")
router.include_router(common_router, prefix="/common")

__all__ = ['router']
