# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""仕入・支払（payables）汎用 CRUD API。"""
from fastapi import APIRouter

from app.modules.fin.payables import models as md
from app.modules.fin.payables import schemas as sc
from app.modules.fin.common.crud import build_crud_router

router = APIRouter()

router.include_router(build_crud_router(model=md.ApBill, out_schema=sc.ApBillOut, create_schema=sc.ApBillCreate, update_schema=sc.ApBillUpdate, resource='ap-bill', search_fields=['bill_no', 'partner_name'], order_by='bill_date desc', label='ApBill'))
router.include_router(build_crud_router(model=md.ApBillLine, out_schema=sc.ApBillLineOut, create_schema=sc.ApBillLineCreate, update_schema=sc.ApBillLineUpdate, resource='ap-bill-line', search_fields=['item_name'], order_by='id desc', label='ApBillLine'))
router.include_router(build_crud_router(model=md.ApPayment, out_schema=sc.ApPaymentOut, create_schema=sc.ApPaymentCreate, update_schema=sc.ApPaymentUpdate, resource='ap-payment', search_fields=['payment_no'], order_by='payment_date desc', label='ApPayment'))
router.include_router(build_crud_router(model=md.ApPaymentAllocation, out_schema=sc.ApPaymentAllocationOut, create_schema=sc.ApPaymentAllocationCreate, update_schema=sc.ApPaymentAllocationUpdate, resource='ap-payment-allocation', search_fields=[], order_by='id desc', label='ApPaymentAllocation'))

__all__ = ['router']  # entities: ApBill, ApBillLine, ApPayment, ApPaymentAllocation
