# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""仕入・支払（payables）SQLAlchemy モデル。"""
from sqlalchemy import (Column, Integer, BigInteger, String, Text, Date, DateTime,
                        Boolean, ForeignKey)
from sqlalchemy.types import Numeric
from sqlalchemy.sql import func

from app.core.database import Base


class ApBill(Base):
    __tablename__ = "fin_ap_bill"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    bill_no = Column(String(40), index=True)
    partner_id = Column(Integer, index=True)
    partner_name = Column(String(200))
    bill_date = Column(Date, nullable=False)
    due_date = Column(Date)
    subtotal = Column(Numeric(18, 2), default=0)
    tax_amount = Column(Numeric(18, 2), default=0)
    total_amount = Column(Numeric(18, 2), default=0)
    paid_amount = Column(Numeric(18, 2), default=0)
    status = Column(String(20), index=True, default="draft")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ApBillLine(Base):
    __tablename__ = "fin_ap_bill_line"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    bill_id = Column(BigInteger, ForeignKey("fin_ap_bill.id", ondelete="CASCADE"), nullable=False)
    line_no = Column(Integer, default=1)
    item_name = Column(String(200))
    quantity = Column(Numeric(18, 4), default=0)
    unit_price = Column(Numeric(18, 4), default=0)
    tax_code = Column(String(20))
    amount = Column(Numeric(18, 2), default=0)
    account_code = Column(String(50))
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ApPayment(Base):
    __tablename__ = "fin_ap_payment"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    payment_no = Column(String(40), index=True)
    partner_id = Column(Integer, index=True)
    payment_date = Column(Date, nullable=False)
    amount = Column(Numeric(18, 2), default=0)
    method = Column(String(30))
    bank_account_id = Column(Integer)
    status = Column(String(20), index=True, default="scheduled")
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ApPaymentAllocation(Base):
    __tablename__ = "fin_ap_payment_allocation"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    payment_id = Column(BigInteger, ForeignKey("fin_ap_payment.id", ondelete="CASCADE"), nullable=False)
    bill_id = Column(BigInteger, index=True)
    allocated_amount = Column(Numeric(18, 2), default=0)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

