# @generated by scripts/fin/fin_codegen.py -- DO NOT EDIT BY HAND

"""仕入・支払（payables）Pydantic スキーマ。"""
from __future__ import annotations
from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class ApBillCreate(BaseModel):
    bill_no: Optional[str] = None
    partner_id: Optional[int] = None
    partner_name: Optional[str] = None
    bill_date: Optional[date] = None
    due_date: Optional[date] = None
    subtotal: Optional[float] = None
    tax_amount: Optional[float] = None
    total_amount: Optional[float] = None
    paid_amount: Optional[float] = None
    status: Optional[str] = None


class ApBillUpdate(ApBillCreate):
    pass


class ApBillOut(ApBillCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ApBillPage(BaseModel):
    items: List[ApBillOut]
    total: int
    page: int
    page_size: int
    pages: int


class ApBillLineCreate(BaseModel):
    bill_id: Optional[int] = None
    line_no: Optional[int] = None
    item_name: Optional[str] = None
    quantity: Optional[float] = None
    unit_price: Optional[float] = None
    tax_code: Optional[str] = None
    amount: Optional[float] = None
    account_code: Optional[str] = None


class ApBillLineUpdate(ApBillLineCreate):
    pass


class ApBillLineOut(ApBillLineCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ApBillLinePage(BaseModel):
    items: List[ApBillLineOut]
    total: int
    page: int
    page_size: int
    pages: int


class ApPaymentCreate(BaseModel):
    payment_no: Optional[str] = None
    partner_id: Optional[int] = None
    payment_date: Optional[date] = None
    amount: Optional[float] = None
    method: Optional[str] = None
    bank_account_id: Optional[int] = None
    status: Optional[str] = None


class ApPaymentUpdate(ApPaymentCreate):
    pass


class ApPaymentOut(ApPaymentCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ApPaymentPage(BaseModel):
    items: List[ApPaymentOut]
    total: int
    page: int
    page_size: int
    pages: int


class ApPaymentAllocationCreate(BaseModel):
    payment_id: Optional[int] = None
    bill_id: Optional[int] = None
    allocated_amount: Optional[float] = None


class ApPaymentAllocationUpdate(ApPaymentAllocationCreate):
    pass


class ApPaymentAllocationOut(ApPaymentAllocationCreate):
    model_config = ConfigDict(from_attributes=True)
    id: int
    created_by: Optional[str] = None
    updated_by: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ApPaymentAllocationPage(BaseModel):
    items: List[ApPaymentAllocationOut]
    total: int
    page: int
    page_size: int
    pages: int

