<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinWorkflowPage :title="title" :api-base="apiBase" :columns="columns" />
</template>

<script setup lang="ts">
import FinWorkflowPage from '@/views/fin/components/FinWorkflowPage.vue'
import type { FinColumn } from '@/views/fin/components/types'

const title = '休暇申請'
const apiBase = '/api/fin/attendance/leave-request'
const columns: FinColumn[] = [{"prop": "employee_id", "label": "employee"}, {"prop": "employee_name", "label": "employee name"}, {"prop": "leave_code", "label": "休暇区分"}, {"prop": "start_date", "label": "start date"}, {"prop": "end_date", "label": "end date"}, {"prop": "days", "label": "日数"}, {"prop": "reason", "label": "reason"}, {"prop": "status", "label": "ステータス"}]
</script>
