<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = 'シフト'
const apiBase = '/api/fin/attendance/employee-shift'
const columns: FinColumn[] = [{"prop": "employee_id", "label": "employee"}, {"prop": "shift_date", "label": "shift date"}, {"prop": "shift_code", "label": "シフト"}]
const fields: FinField[] = [{"prop": "employee_id", "label": "employee", "type": "number", "required": false}, {"prop": "shift_date", "label": "shift date", "type": "date", "required": true}, {"prop": "shift_code", "label": "シフト", "type": "text", "required": false}]
</script>
