<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '勤務カレンダー'
const apiBase = '/api/fin/attendance/work-calendar'
const columns: FinColumn[] = [{"prop": "calendar_date", "label": "日付"}, {"prop": "day_type", "label": "day type"}, {"prop": "name", "label": "名称"}]
const fields: FinField[] = [{"prop": "calendar_date", "label": "日付", "type": "date", "required": true}, {"prop": "day_type", "label": "day type", "type": "text", "required": false}, {"prop": "name", "label": "名称", "type": "text", "required": false}]
</script>
