<!-- @generated by scripts/fin/fin_codegen.py -->
<template>
  <FinCrudPage :title="title" :api-base="apiBase" :columns="columns" :fields="fields" />
</template>

<script setup lang="ts">
import FinCrudPage from '@/views/fin/components/FinCrudPage.vue'
import type { FinColumn, FinField } from '@/views/fin/components/types'

const title = '勤怠記録'
const apiBase = '/api/fin/attendance/attendance-record'
const columns: FinColumn[] = [{"prop": "employee_id", "label": "社員"}, {"prop": "employee_name", "label": "employee name"}, {"prop": "work_date", "label": "勤務日"}, {"prop": "clock_in", "label": "出勤"}, {"prop": "clock_out", "label": "退勤"}, {"prop": "break_minutes", "label": "休憩分"}, {"prop": "work_minutes", "label": "実働分"}, {"prop": "overtime_minutes", "label": "残業分"}]
const fields: FinField[] = [{"prop": "employee_id", "label": "社員", "type": "number", "required": false}, {"prop": "employee_name", "label": "employee name", "type": "text", "required": false}, {"prop": "work_date", "label": "勤務日", "type": "date", "required": true}, {"prop": "clock_in", "label": "出勤", "type": "datetime", "required": false}, {"prop": "clock_out", "label": "退勤", "type": "datetime", "required": false}, {"prop": "break_minutes", "label": "休憩分", "type": "number", "required": false}, {"prop": "work_minutes", "label": "実働分", "type": "number", "required": false}, {"prop": "overtime_minutes", "label": "残業分", "type": "number", "required": false}, {"prop": "status", "label": "ステータス", "type": "text", "required": false}]
</script>
